### ISSUE TITLE
Issue with make on windows machine

### ISSUE THREAD

**Issue by baracus37** [pachterlab/kallisto#119]
Hello,

I am trying to install kallisto on a Windows 7 machine (x64) with cygwin64. I am following the instructions here: [http://pachterlab.github.io/kallisto/local_build.html](url)
Here is what I do and the error I get using make:

cmake seems to be running fine

>$ cmake -DCMAKE_INSTALL_PREFIX=$HOME ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
shared build
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: hdf5_cpp;hdf5;z;dl;m (found version "1.8.17")
-- Found ZLIB: /usr/lib/libz.dll.a (found version "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/e/tools/kallisto-0.43.0/build

when trying to run make i get this error:

>$ make
Scanning dependencies of target kallisto_core
[  5%] Building CXX object src/CMakeFiles/kallisto_core.dir/Bootstrap.cpp.o
In file included from /cygdrive/e/tools/kallisto-0.43.0/src/H5Writer.h:6:0,
                 from /cygdrive/e/tools/kallisto-0.43.0/src/Bootstrap.h:12,
                 from /cygdrive/e/tools/kallisto-0.43.0/src/Bootstrap.cpp:1:
/cygdrive/e/tools/kallisto-0.43.0/src/h5utils.h:42:5: error: ‘uint’ has not been declared
     uint compression_level = 6
     ^
In file included from /cygdrive/e/tools/kallisto-0.43.0/src/Bootstrap.h:12:0,
                 from /cygdrive/e/tools/kallisto-0.43.0/src/Bootstrap.cpp:1:
/cygdrive/e/tools/kallisto-0.43.0/src/H5Writer.h:15:106: error: ‘uint’ has not been declared
       const std::vector<int>& fld, const std::vector<int>& preBias, const std::vector<double>& postBias, uint compression, size_t index_version,
                                                                                                          ^
In file included from /cygdrive/e/tools/kallisto-0.43.0/src/Bootstrap.h:12:0,
                 from /cygdrive/e/tools/kallisto-0.43.0/src/Bootstrap.cpp:1:
/cygdrive/e/tools/kallisto-0.43.0/src/H5Writer.h:28:5: error: ‘uint’ does not name a type
     uint compression_;
     ^
make[2]: *** [src/CMakeFiles/kallisto_core.dir/build.make:63: src/CMakeFiles/kallisto_core.dir/Bootstrap.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:88: src/CMakeFiles/kallisto_core.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

Can anyone help?

**Comment by pmelsted** [comment]
You might try to include <stdint.h> where the errors occur. See http://stackoverflow.com/questions/11069108/uint32-t-does-not-name-a-type
for more.

**Comment by baracus37** [comment]
Hi, thanks for the quick reply! I also found the post you mentioned, but unfortunaltey i don't know how to do this. Could you give some further instructions? Would be greatly appreciated.
