### ISSUE TITLE
No need to create build directory as instructed in INSTALL.md

### ISSUE THREAD

**Issue by sammyjava** [pachterlab/kallisto#124]
Since CMakeLists.txt, src, etc. are all under the root directory, make doesn't work if you mkdir build; cd build and then run it. It runs fine from the root, creating Makefile, cmake_install.cmake, CMakeFiles, libkallisto_core.a and kallisto just fine under src. I recommend removing
```
1. Make a build directory and move there...
```

**Comment by pmelsted** [comment]
This is optional, but I tend to use this pattern since it makes less of a clutter in my development directory.
