### ISSUE TITLE
ENST to ENSG: issues with BAM output

### ISSUE THREAD

**Issue by wyattmcdonnell** [pachterlab/kallisto#125]
Hi there!

Currently using HG38.86 as my index in Kallisto. I've successfully piped everything through and into a BAM file, and have been able to sort by coordinates in that BAM file, but the issue that keeps popping up is that my other software (namely, Qlucore) doesn't recognize ENST gene IDs -- it only recognizes ENSG gene names. Is there a way to get the ENSG name into stdout for piping into a BAM file? Otherwise the Kallisto pipeline doesn't seem to be usable with anything besides Sleuth for downstream analysis (unless I'm wrong). Thanks a ton!

WJM

**Comment by maximilianh** [comment]
I just go over every gene, sum up its ENSTs' tpm values and output a new table for the third party tool.
