### ISSUE TITLE
Error: index output file could not be opened!

### ISSUE THREAD

**Issue by Fhennig94** [pachterlab/kallisto#129]
Hello,
I was wondering if you could help me with this error. I have run this line of code before and it has worked but now I get this error message and I'm not sure why. This is my code:

kallisto index -i Homo_sapiens.GRCh38.cdna.all.HBmain.k_idx Homo_sapiens.GRCh38.cdna.all.HBmain.fa.gz

[build] loading fasta file Homo_sapiens.GRCh38.cdna.all.HBmain.fa.gz
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 1415 target sequences
[build] warning: replaced 85 non-ACGUT characters in the input sequence
        with pseudorandom nucleotides
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done 
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 1070249 contigs and contains 105684612 k-mers 
Error: index output file could not be opened!

**Comment by mschilli87** [comment]
Are you sure thi is a `kallisto` error? Can you `touch Homo_sapiens.GRCh38.cdna.all.HBmain.k_idx` without error?

**Comment by Fhennig94** [comment]
Ah thank you!
