### ISSUE TITLE
Provide option to name output file

### ISSUE THREAD

**Issue by humburg** [pachterlab/kallisto#131]
It would be useful (to me at least) to have the option to provide a custom name for the output files. Being able to name the abundance files based on the name of the input fastq files would not only allow abundances for multiple samples to be written to the same directory, it also makes it easier to move those files without losing track of associated sample names.

**Comment by skurscheid** [comment]
I personally would suggest looking into workflow management with e.g. snakemake (http://snakemake.readthedocs.io/en/stable/ - no affiliations, but very happy user) - that allows you to create persistent links between input and output files, and I find it not very problematic that the kallisto output is a directory. BTW changing output filenames could also throw a spanner in the sleuth workflow...

**Comment by humburg** [comment]
Thanks @skurscheid. I actually use [CWL](http://www.commonwl.org/v1.0/index.html) and [toil](http://toil.readthedocs.io/en/releases-3.6.x/) to run my workflow. Unfortunately, it is a bit of a problem there. Admittedly the CWL/toil combination could have better support for handling directories but that is a different issue.

Leaving aside the question of varying preferences for workflow management, it seems like an unnecessary restriction to hard code the name of output files. Apart from the issue that it seems too easy for results to be separated from vital information, like the associated sample, it also promotes the use of unnecessarily deep directory trees where the lowest directory mostly contains a single file of interest. I freely admit that this is mostly personal preference but why not provide some flexibility? It should be relatively easy to do. It is true that sleuth would need some adjustment but that too wouldn't be hard. In the case of sleuth I'd happily volunteer to submit a pull request (I'd do the same for kallisto but my C++ is a bit too rusty to be comfortable messing with other people's code base).

**Comment by pmelsted** [comment]
Since there are a few files written to the output directory (more if you run other options like `pseudo`), we prefer to have the output directory name be user specified and keep the filenames fixed. This convention means less work than allowing for an arbitrary configuration.

Any moving or renaming of files can be done with either a shell script or in snakemake as @skurscheid points out.

**Comment by pimentel** [comment]
fwiw, `sleuth_prep` can take either a directory or a file with an *.h5 extension in the `path` argument

**Comment by humburg** [comment]
@pimentel That is good to know, thanks.

@pmelsted If you don't think providing a better user interface is worth your time, that's your choice. I can certainly understand that you might have different priorities. However, before I go away, I feel compelled to point out that your justification for this choice seems a bit dubious, considering that `pseudo` writes to stdout (somewhat ironically making it easy to give it an arbitrary name). A better argument might be the use of `plaintext` in combination with bootstrapping, which can indeed produce a lot of files. I would maintain though that allowing users to provide a file prefix, which may include a directory as well as part of the file name, would in no way create more work (once implemented) than the current implementation and be fully backwards compatible.

**Comment by lakigigar** [comment]
Hi Peter,

I appreciate your thoughtful input regarding the naming of files. Please
let us know if you have any other questions about kallisto.
Thanks,
Lior
