### ISSUE TITLE
Multithreaded pseudoalignment

### ISSUE THREAD

**Issue by GinnyAquarius** [pachterlab/kallisto#132]
I have downloaded source code of version 0.42.4 for multithreaded pseudoalignment but I still received this error while running:
Error: pseudobam is not compatible with running on many threads.
Have I made anything wrong?

**Comment by biobenkj** [comment]
Hi Ginny, 
Unfortunately, you can't write out pseudobams in a multi-threaded fashion. If you want to output a pseudobam, remove the threading option from the kallisto quant call.

Hope this helps!

**Comment by pmelsted** [comment]
Just an update, we are working on fixing this in the next version so that you can get multithreaded pseudobam.

**Comment by laserson** [comment]
Great!  This is definitely a requirement for me.  I noticed you closed this issue...is the fix already in `master`?

**Comment by laserson** [comment]
Just wanted to check in on this, @pmelsted
