### ISSUE TITLE
fragment length distribution data in abundance.h5

### ISSUE THREAD

**Issue by skurscheid** [pachterlab/kallisto#134]
Hi,

this is a request for clarification on the "aux/fld" object stored in the h5 output of kallisto --quant. I am in the process of preparing RNA-Seq data for submission to repositories, and one of the requested pieces of data is the mean insert size length in paired end data. As I have completely switched over to kallisto/sleuth in my RNA-Seq workflows (and am desperately hoping that this wasn't premature, as there seems to be a bit of stalling after the initial development rush), I would prefer to use the kallisto generated data rather than having to run an aligner for the sole purpose of estimating the fragment sizes.

What I deduce from the "aux/fld" data is, that it is effectively the count table of observed fragments in a size range from 1 to 1000 bp, based on taking 40000 samples. Is this correct? Is the actual estimated mean fragment/insert size stored somewhere in the h5 file? I've seen a pull request where you have incorporated the fragment/insert size estimation into kallisto, but I haven't found any indication that this single value is actually stored.

Thanks in advance!

**Comment by mschilli87** [comment]
Not sure about the h5 but the log output (`stderr` by default iirc) contains a line like

> `[quant] estimated average fragment length: 178.932`

when run in paired-end mode.

So if you run `kallisto --quant` with `2>log.file`, you don't need to run a mapper just to get that number.

---
That said, this information should be (and probably is) recorded in the output file, too.

**Comment by vals** [comment]
Hi @skurscheid , if you're talking about ENA/ArrayExpress, the fragment length distribution should be the one expected _experimentally_. Based on size selection or fragment analysis or Bioanalyzer traces. The reason they ask you to provide FLD is to use it as an input parameter to alignment.

**Comment by skurscheid** [comment]
@mschilli87 thanks for the hint - I knew that I saw it somewhere before but I habitually redirect stderr > /dev/null

@vals yes, I was referring to ArrayExpress - I will keep this in mind.

I guess it still would be nice to actually output the mean fragment length to the h5 file (instead of stderr), considering that it is a pretty important piece of data.

**Comment by vals** [comment]
Yes it's a pretty good QC statistic :), and I think it can help assessing RNA quality if you e.g. use stored samples.

**Comment by pmelsted** [comment]
@skurscheid the aux/fld stores the observed fragment length distribution. Internally we use the distribution to compute the effective length not the mean fragment length. 

This value is not stored, but printed to stderr, we should output it in plaintext but right now the "easiest" way to get it is to compute it from the distribution.

The following python script will extract this from the hdf5 file

```
import h5py
import numpy as np
import sys

fn = sys.argv[1]
f = h5py.File(fn)
x = np.asarray(f['aux']['fld'], dtype='float64')
t = np.arange(0,len(x),1)

mean = np.sum(x*t)/np.sum(x)
print(mean)
```

and run it as
```
>>python mean_fld.py out/abundance.h5
178.096577381
```

**Comment by maximilianh** [comment]
random note: in my experience it is crucial to store the stderr output. In
our pipelines, we absolutely need to store the % of alignable reads and the
computed fragment length, so I'm parsing it from the stderr logs. It may be
nice (but not important) if these values could be output to a separate file
(or in an existing file) that is easier to parse.

**Comment by skurscheid** [comment]
@maximilianh fair point. Philosophically (and from a UNIX system programmer's point of view) however, it is a bit questionable to output "normal" information via stderr. Anyway, thanks for all the suggestion!

**Comment by skurscheid** [comment]
thank you @pmelsted!
