### ISSUE TITLE
Kallisto exits prematurely on encountering a zero-length read

### ISSUE THREAD

**Issue by jstaf** [pachterlab/kallisto#135]
Not really a bug per se, but a bit of a weird circumstance that can lead to some confusion with Kallisto's output. If Kallisto encounters a zero-length read (see below), it exits prematurely with no warning what occured, and you miss out on any remaining reads in a sample. 

```
@HWI-ST300:393:C5YVGACXX:3:1101:5136:2240 1:N:0:CTTGTA

+

```

Granted, there should be no zero-length reads in a sample (this was caused by me forgetting to tell cutadapt to discard reads shorter than X bases after adapter trimming), but it seems like a good idea to spit out a warning and then exit, rather than just say it processed X number of reads and leave it to the user to figure out why this number was so much different than the number in the original FASTQ.

**Comment by dlaehnemann** [comment]
I have just had the same problem with empty reads in one of the read pairs due to cutadapt not discarding them by default. And I also agree, that such reads can easily be filtered.

But for debugging such issues, it would be great if kallisto would throw some sort of warning if it stops processing fastq input files early because it encounters an empty record.

**Comment by outpaddling** [comment]
We just hit the same issue here.  Trimming out 3' adapters left a few reads completely empty.  Maybe a few 3' adapters floating around in the solution got attached directly to 5' adapters...

We fixed it by adding a --minimum-length=30 to our cutadapt command.

I don't think kallisto should tolerate this, but maybe it should flag it.

How about printing an error message something like:

"Empty read encountered, aborting...  Please clean up your sample files and try again."

Cheers,

   Jason
