### ISSUE TITLE
--pseudobam should make -o optional

### ISSUE THREAD

**Issue by laserson** [pachterlab/kallisto#137]
When running `kallisto pseudo --pseudobam`, I'd like to simply have kallisto as part of a unix pipeline and not require anything written to disk.  Is there a reason `-o` continues to be forced in this situation?

**Comment by pmelsted** [comment]
Since `--pseudobam` is an option and not a "mode", I am hesitant to change this behaviour. The output also contains metadata in `run_info.json` which is nice to have.

If you don't need it in a workflow you can remove it at the end.
