### ISSUE TITLE
Stddev of 0 not acceptable

### ISSUE THREAD

**Issue by laserson** [pachterlab/kallisto#138]
I have a synthetic library that I am quantifying and so I know that all the library members have the exact same length.  I'd like to supply `-s 0` but cannot.  Should I just use a very small number as a workaround?

**Comment by mschilli87** [comment]
I ran into the same issue and used `-s 1` getting reasonable results.

**Comment by pmelsted** [comment]
For synthetic libraries this is a decent workaround, if you need smaller values you can also supply a float, e.g. `-s 0.01`.
