### ISSUE TITLE
QA: Where can I find bootstrap summary statistics?

### ISSUE THREAD

**Issue by holgerbrandl** [pachterlab/kallisto#142]
I managed to run kallisto with bootstrapping. Now I'm struggling to get some summary statistics. I can read the raw bootstrap results (e.g. in R) with
```
require(rhdf5)
bs_data = h5read(files[1],"bootstrap/bs0")
```
I've tried `tximport` package already but could not find a corresponding method.

However, I'd be rather curious to get gene-level summary estimates about the uncertainty of expression estimates. Is this part of the hdf5 or do I need to calculate those numbers myself? If the latter applies, are there some public code-bits I could reuse?

**Comment by holgerbrandl** [comment]
I'd be still curious to learn more about bootstrapping support in kallisto, so feel welcome if you need more info to process my request.

**Comment by pmelsted** [comment]
Gene level estimates are not stored in the hdf5 files, but are computed with sleuth, https://github.com/pachterlab/sleuth

The user group, https://groups.google.com/forum/#!forum/kallisto-sleuth-users is a better place to get help on using the sleuth functions. Also take a look at http://pachterlab.github.io/sleuth/ and the sleuth walk-throughs to see how sleuth is used.

**Comment by holgerbrandl** [comment]
Ok, thanks. Actually I was briefly looking into the sleuth-repo already but its REAMDE stated that 
> It makes use of quantification uncertainty estimates obtained via kallisto for accurate differential analysis of isoforms

That's why I ended up here.

**Comment by mschilli87** [comment]
@holgerbrandl: Both can be correct as you asked for gene level estimates. IRC, `kallisto` estimates transcript (isoform) level uncertanties, which are read by `sleuth` and summarized to the gene-level.

**Comment by holgerbrandl** [comment]
My bad, I actually wanted to to access the "transcript level uncertainties". Where are they stored? I somehow can not find them when reading in h5 or tsv output from kallisto.

**Comment by pmelsted** [comment]
The h5 files contain the complete quantifications of each bootstrap. If you want summaries I recommend using sleuth to compute them, take a look at   `get_bootstrap_summary` in sleuth, which should give you what you need.

**Comment by holgerbrandl** [comment]
Cool, thanks (also for your patience), that's the answer I was looking for.
