### ISSUE TITLE
Kallisto pseudo Error 

### ISSUE THREAD

**Issue by hansparkdgist** [pachterlab/kallisto#145]
I tried kallisto pseudo with pseudobam option but it doesn't work. So I erased pseudobam option, but also the same error message occur. 
![image](https://user-images.githubusercontent.com/31980326/30533453-583a3f46-9c94-11e7-95b6-bc7d3bc123a4.png)

**Comment by pmelsted** [comment]
From this we can't see what happened, whether it was an error or if it consumed too much memory. Please post to the https://groups.google.com/forum/#!forum/kallisto-sleuth-users to get help with errors like this. If it turns out to be a bug in the program you can file an issue here again.
