### ISSUE TITLE
Windows download file does not work

### ISSUE THREAD

**Issue by joycerigal** [pachterlab/kallisto#146]
Hi,

I downloaded the windows installer but when I try to run it a black command box flashes briefly and then disappears. It does not install the program. I tried different computers, and the two versions available for download. Both were unable to installed. 

Thanks

**Comment by pmelsted** [comment]
There is no installer. The (windows) kallisto program is a command line program that you run from the windows shell. When you double click it, the program runs, shows the help message for a split second and windows closes the shell immediately.

If you want to run it from any folder, simply copy it to a folder in your path or set the path on your machine to where the download is stored. For more examples look at the website https://pachterlab.github.io/kallisto/ or the user group https://groups.google.com/forum/#!forum/kallisto-sleuth-users
