### ISSUE TITLE
Kallisto runs very slowly / fails to finish after hours of processing

### ISSUE THREAD

**Issue by jma1991** [pachterlab/kallisto#149]
I ran this command to quantify transcript abundances:

`kallisto quant -i Data/Transcriptome/Sequence/Indexes/Kallisto/knownGene.idx -o Data/Samples/ESC_Rep1 --single -l 200 -s 20 Data/Samples/ESC_Rep1/SRR2061718_cutadapt.fastq.gz 2> Data/Samples/ESC_Rep1/ESC_Rep2_kallisto.log`

But it hasn't finished after ~11 hours of running. The log file contains this information:

```
[quant] fragment length distribution is truncated gaussian with mean = 200, sd = 20
[index] k-mer length: 31
[index] number of targets: 63,759
[index] number of k-mers: 980,659,077
[index] number of equivalence classes: 3,309,210
[quant] running in single-end mode
[quant] will process file 1: Data/Samples/ESC_Rep1/SRR2061718_cutadapt.fastq.gz
[quant] finding pseudoalignments for the reads ...
```
Overall kallisto seems to run very slowly, it can take at least an hour just to get to the finding pseudoalignments stage. The files typically contain ~40M reads. I'm using version 0.43.1 which was installed through bioconda.

**Comment by mschilli87** [comment]
@jma1991: Any chance you can try complie the same version yourself?
This could help to figure out if this is related to kallisto itself or a bioconda issue.

**Comment by pmelsted** [comment]
From the number of k-mers in your transcriptome it seems you would need a lot of memory more than 16G at least, can you make sure you have that amount of RAM on your machine and that you are not swapping to disk. You can run top while running kallisto to see the memory usage and CPU %.

Also, where is the transcriptome from, it seems awfully large?

**Comment by jma1991** [comment]
1. I'm running it on a machine with 500G of RAM.
2. The transcriptome was made using the following script:
```
library("TxDb.Mmusculus.UCSC.mm10.knownGene")
library("BSgenome.Mmusculus.UCSC.mm10")
db <- TxDb.Mmusculus.UCSC.mm10.knownGene
bs <- BSgenome.Mmusculus.UCSC.mm10
tx <- transcripts(db)
nt <- getSeq(bs, tx)
names(nt) <- tx$tx_id
writeXStringSet(nt, file = "knownGene.fasta", format = "fasta")
```
3. Regardless of the number of threads I specify, the command always runs on 1 CPU (100%) and uses 27G of RAM.

**Comment by pmelsted** [comment]
Can you verify that you are only getting transcripts sequences without introns. Also rather than using the bioconda version, you can download a linux binary under releases.

**Comment by jma1991** [comment]
You are right, my script produces sequences with the introns. [Do you suggest I use the exon sequences (including 5' and 3' UTR) or the CDS sequences (do not include 5' and 3 UTR)?
](https://ibb.co/jdV6nw)

I'll download the binary and try with the new annotation.

**Comment by mschilli87** [comment]
@jma1991: Typically RNA-seq protocols capture the whole (mature)  transcript.
That means sequencing reads can cover the whole CDS and the UTRs.
So your `exonsBy`-approach would be the most reasonable.

---

@pmelsted: Any chance to get kallistio run on an extended transcriptome containing *both*, mature *and* primary transcripts? This could be very interesting when trying to study processing by calculating spliced vs. unspliced ratios (see https://doi.org/10.1101/206052 for a recent example).

**Comment by jma1991** [comment]
@pmelsted Kallisto works great now. It was the enormously large index which was causing problems.
