### ISSUE TITLE
quantification aborted following std::bad_alloc

### ISSUE THREAD

**Issue by MattMyint** [pachterlab/kallisto#153]
Hi,

I've been running kallisto on 3 sets of data, two mouse and one human.
I successfully built the indexes for both, in fact the quantification worked well for both mouse data sets.

However, my problem arises when I try to quantify the human fastq, estimating the single read fragment length as 200 and s.d as 20.

```
kallisto quant -i /home/mattmyint/FYP/human.idx -o /home/mattmyint/FYP/kallisto_out//lymphoid_SRR2088080 -b 0 --single -l 200 -s 20 --bias /home/mattmyint/FYP/fastq/lymphoid/SRR2088080_1.fastq

[quant] fragment length distribution is truncated gaussian with mean = 200, sd = 20
[index] k-mer length: 31
[index] number of targets: 200,401
[index] number of k-mers: 126,160,363
[index] number of equivalence classes: 139,908,631,968,824
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

Here's the lines from a successful run
```
kallisto quant -i /home/mattmyint/FYP/mouse.idx -o /home/mattmyint/FYP/kallisto_out//cortex_SRR1544745 -b 0 --single -l 200 -s 20 --bias /home/mattmyint/FYP/fastq/cortex/SRR1544745_1.fastq

[quant] fragment length distribution is truncated gaussian with mean = 200, sd = 20
[index] k-mer length: 31
[index] number of targets: 133,849
[index] number of k-mers: 115,634,175
[index] number of equivalence classes: 473,742
[quant] running in single-end mode
[quant] will process file 1: /home/mattmyint/FYP/fastq/cortex/SRR1544745_1.fastq
[quant] finding pseudoalignments for the reads ... done
[quant] learning parameters for sequence specific bias
[quant] processed 1,520,393 reads, 629,778 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,106 rounds
```

I noticed that there's orders of magnitude difference in the number of equivalence classes obtained.

Is there any misstep I took? If this info helps, I obtained the index by running gencode genome fasta (3.2gb) and annotation GTFs (1.2gb) through gffread to obtain transcriptome fasta (310mb).

**Comment by mschilli87** [comment]
@MattMyint: What was the exat `gffread` command?
My guess guess would be that your FASTA contains introns which would explain the enormous index size and resulting out-of-memory error.

**Comment by MattMyint** [comment]
gffread your_transcripts.gff -g genomic_reference.fasta -w your_transcripts.fasta​

Are there alternatives to producing a transcriptome fasta? My intent was to have transcriptome references created from the same source for a fair comparison in results between RSEM and kallisto

**Comment by mschilli87** [comment]
@MattMyint: Your command looks valid to me. The FASTA shouldn't contain any introns.

---
Comparing your two runs, the successful one has much less equivalence classes than the unsuccessful one, beyond what I would have expected from the differences in target number.

How did you obtain the human and mouse GFF files used for these runs? Are there any obvious differences?

**Comment by MattMyint** [comment]
I used the latest GENCODE human “comprehensive gene annotation” GTF, and the transcript sequences FASTA. 

On the site, they’re the first entries on their lists.

**Comment by vllorens** [comment]
I had a similar error when working with my own indexed (meta-)transcriptomes. I solved it just by asking for much more memory in our computing cluster. 90G was the minimum that worked for me after a few trials.

In my case the number of equivalence classes was not as high but the number of targets and kmers was quite large, here's the log of one sample run:
```
[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 1,981,346
[index] number of k-mers: 1,021,240,129
[index] number of equivalence classes: 5,260,894
[quant] running in paired-end mode
[quant] will process pair 1: sample_08_1.fasta
                             sample_08_2.fasta
[quant] finding pseudoalignments for the reads ... done
[quant] learning parameters for sequence specific bias
[quant] processed 500,000 reads, 499,457 reads pseudoaligned
[quant] estimated average fragment length: 239.737
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 663 rounds
```

**Comment by MattMyint** [comment]
Anyway, as @mschilli87 suggested, there was some problem with the transcriptome fasta generated.

Instead of using a fasta generated by gffread, I used one that was generated by RSEM and that was successful.

Thanks for the help! I'll close the issue
