### ISSUE TITLE
Problem with new --genomebam feature

### ISSUE THREAD

**Issue by Rhinogradentia** [pachterlab/kallisto#155]
Hi there,

The new version you published yesterday is something I really need at the moment! My problem is that I tried to generate a genome-position-based bam file and IGV is not displaying anything. 

Here is how I called kallisto:
```
../kallisto quant -i ../../../transcripts.idx -o out -b 100 --fr-stranded --genomebam --gtf ../transcripts.gtf --chromosomes ../chrom.info sample1.1_trimmed.fq sample1.2_trimmed.fq 

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 5,344
[index] number of k-mers: 7,343,245
[index] number of equivalence classes: 5,435
[quant] running in paired-end mode
[quant] will process pair 1: sample1.1_trimmed.fq
                             sample1.2_trimmed.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 14,728,004 reads, 136,735 reads pseudoaligned
[quant] estimated average fragment length: 315.988
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 52 rounds
[bstrp] running EM for the bootstrap: 100
[  bam] writing pseudoalignments to BAM format .. done
[  bam] sorting BAM files .. done
[  bam] indexing BAM file .. done
```
I've also checked with samtools if any reads are marked as mapped:

```
# mapped
samtools view -F 4 pseudoalignments.bam | wc -l
136824
# not mapped
samtools view -f 4 pseudoalignments.bam | wc -l
29319184

```

But if I take a look into the bam-file itself (only the "mapped" reads), there is no information on the position assigned:

```
samtools view -F 4 pseudoalignments.bam | head 
7001253F:408:C9KJ3ANXX:5:2303:5764:2046#44942_GGCTAC/1	67	*	0	0	49M	*	0	0	CNCCCCAACATGATCGACTCTGGAAGAAAATCATTGCTCTCTGACACGG	B#<<BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:5764:2046#44942_GGCTAC/2	131	*	0	0	50M	*	0	0	AAAGAAAGCTGTTACGAGCAGCACCGGCCGTAACTTCTCCAAACGTTCGC	FFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFBFBFFFFFFFFBBBBB	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:18254:2202#44942_GGCTAC/1	67	*	0	0	50M	*	0	0	CAGTATTATAGGAGACAAAGACTATGTCCCCGATGTCAATGAAAACTTTG	BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:18254:2202#44942_GGCTAC/2	131	*	0	0	50M	*	0	0	AATTCTCTGTGGTACATTGAAGAGAATACACACCCACTTTTCAACCAAAC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBB	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:20088:2078#44942_GGCTAC/1	67	*	0	0	50M	*	0	0	CGAGGCGTATTTGGGAACTATGTGGCTCCTCTGAGGAAGTAATTGATGTT	BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:20088:2078#44942_GGCTAC/2	131	*	0	0	50M	*	0	0	CAAGAAAACCAATTTCGTCTTTTGGATGGTGACAAGATTGCAACACTATT	FFFFFFFFFFFFFF/FFFFFFFFFFFFFFFFFFFBFFFFFFFFFFBBBBB	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:4385:2367#44942_GGCTAC/1	67	*	0	0	50M	*	0	0	GGCGGACTATCTAGTGTGTGGGGAAAATGATTTGGCCAAGATTGACTTTT	BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBBFFFFFFFF	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:4385:2367#44942_GGCTAC/2	131	*	0	0	50M	*	0	0	GGATTTTAATCTTTTGAAGGCACAGTACAGGAATGCATCTCCTAAGGGTG	F<FFFFFFFFFFFFF<FFFFFFFF<FFF/FFFFFFFFFBF/FBFFBBBBB	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:4836:2473#44942_GGCTAC/1	67	*	0	0	49M	*	0	0	CCTCAACTATTCAAACTATCCAAATACAATCGTACCCATTTTTAATAGT	BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	ZW:f:0
7001253F:408:C9KJ3ANXX:5:2303:4836:2473#44942_GGCTAC/2	131	*	0	0	49M	*	0	0	TCCAGAACTGTTCCCATCATCGCTAATGTACACTATAGCGTTTCCAATC	FFFFFFFFFFFFFBFFFFFBFFFFFFFFFFFFFBFFFFFFFFFFBBBBB	ZW:f:0
```
My chromosome information file looks like this:

```
chr1    2891190
chr2    2399323
chr3    2256069
chr4    1820458
mt      35683
```

My gtf looks like this:
```
[...]
chr1    GenBank exon    5023    6504    .       +       .       transcript_id "Chr1-0001"; gene_id "Chr1-0001"; gene_name "Chr1-0001";
chr1    GenBank CDS     5023    6504    .       +       0       transcript_id "Chr1-0001"; gene_id "Chr1-0001"; gene_name "Chr1-0001";
chr1    GenBank exon    10244   11740   .       -       .       transcript_id "Chr1-0002"; gene_id "Chr1-0002"; gene_name "Chr1-0002";
chr1    GenBank CDS     10244   11740   .       -       0       transcript_id "Chr1-0002"; gene_id "Chr1-0002"; gene_name "Chr1-0002";
chr1    GenBank exon    12203   13330   .       +       .       transcript_id "Chr1-0003"; gene_id "Chr1-0003"; gene_name "Chr1-0003";
chr1    GenBank CDS     12203   13330   .       +       0       transcript_id "Chr1-0003"; gene_id "0003"; gene_name "Chr1-0003";
chr1    GenBank exon    14955   15368   .       -       .       transcript_id "Chr1-0004"; gene_id "Chr1-0004"; gene_name "Chr1-0004";
chr1    GenBank CDS     14955   15368   .       -       0       transcript_id "Chr1-0004"; gene_id "Chr1-0004"; gene_name "Chr1-0004";
[...]
```
And the transcript.idx file is based on a fasta-file (abbreviated) looking like this:

```
[...]
>Chr1-0001
ATGCTTGCTGAGATTGGGGACTATTTCAGGACAAATAGTAGCAATGGATTCAGTTCTAGC
[...]
>Chr1-0002
ATGAACTACGAATACAAACACATATCCAAACTAGTCCCTCGCCATAGAGTGCCCTTTTTT
[...]
>Chr1-0003
ATGGTTAGTACCGTTCAGACAGTCAAAATTGATGTTAACGCTCATGATGCCTCTACCCAA
[...]
>Chr1-0004
ATGTCGCTCGCACTCAATGATCTGGTGAACTCTTACGACGCTCTCACTTTCGGTATGTGG
[...]
```

In the end I want to visualize it using JBrowse - which needs the same formats. Additionally I want to convert it into BigWig (via BED). This also does not work with this BAM-files.

Is there something I'm doing wrong?

Any help really appreciated!

Best Regards,
Nadine

**Comment by pmelsted** [comment]
I think the culprit is that it is not pseudoaligning any reads as you can see in this output

```
processed 14,728,004 reads, 136,735 reads pseudoaligned
```

You specified `--fr-stranded`, i.e. that the first pair in the read is on the forward strand. Could it be that you wanted to use the opposite, you can check this by blatting the first few pairs of your reads to the reference (which species is this?).  My guess is that if you switch to `--rf-stranded` you should see a lot more reads pseudoaligning and get non-empty BAM files

**Comment by Rhinogradentia** [comment]
Mh - but doesn't ` 136,735 reads pseudoaligned` mean, that ~ 136000 reads are aligned? Do I misinterpret this?

Anyway - I will try your suggestions wit `--rf-stranded`.

It is a yeast by the way.

Thank you

**Comment by pmelsted** [comment]
I think there might be an issue with the GTF, is it publicly available and the CDNA fasta file as well? Can you send the link or if they were generated inhouse, can they be shared?

**Comment by Rhinogradentia** [comment]
The GTF ist inhouse generated using gffread from a [gff](http://pichiagenome-ext.boku.ac.at:8080/apex/f?p=100:16:15862207971178::NO:::) which is available online 

[CBS7435_21102016.txt](https://github.com/pachterlab/kallisto/files/1681909/CBS7435_21102016.txt) (I changed the file-extension for the upload).

The organism is K.phaffi (formerly known as Pichia Pastoris) CBS7435. All the sequences available should be on the [NCBI](https://www.ncbi.nlm.nih.gov/nuccore/?term=pichia%20pastoris%20CBS7435).

Only thing I changed is, that I replaced the Chromosome-IDs with cbs7435_chr1, cbs7435_chr2,cbs7435_chr3, cbs7435_chr4, cbs7435_mt, because I need this for my JBrowse instance.

**Comment by pmelsted** [comment]
I looked at the GTF file and it does not include enough information (at least in the format kallisto expects) to construct the mapping from transcripts to gene coordinates.

The required types are `gene`, `transcript` and `exon`, anything else is ignored. Each type must have the required fields of a GTF file, `chromosome, start, stop, strand` etc.

The optional fields used are `transcript_id`, `gene_id` and optionally `transcript_version` and `gene_version`, which have to match respectively. The `transcript_id` (or `transcript_id + '.' + transcript_version`) have to match the transcript names in the FASTA file used to construct the index. 

The chromosome file must also match the chromosome names in the GTF file, if there is no chromosome file we'll guess the chromosomes from the GTF, but the lengths are false.

To fix your GTF file you can modify it to create a `gene` and `transcript` entry corresponding to the exon entries you have. The original file had `gene` records and presumably was single exon only, so this can be copied to a `transcript` entry. 

```
chr1    GenBank gene    5023    6504    .       +       .       gene_id "Chr1-0001"; gene_name "Chr1-0001";
chr1    GenBank transcript    5023    6504    .       +       .       transcript_id "Chr1-0001"; gene_id "Chr1-0001"; gene_name "Chr1-0001";
chr1    GenBank exon    5023    6504    .       +       .       transcript_id "Chr1-0001"; gene_id "Chr1-0001"; gene_name "Chr1-0001";
```

I think this should take care of the issues, but without the cdna transcript file I can't see what else there is.

**Comment by Rhinogradentia** [comment]
Thank you for the hint. The gff file from which the gtf is generated contains all this information. I will adjust it and try the workflow again.

For now I will close this issue - if it does not work with the changed gtf I will reopen it.

Thanks a lot again

kind regards
Nadine

**Comment by Rhinogradentia** [comment]
Hi there,
I tried the run again with the mentioned changes, but the result stayed the same. Now I think I have another hint. The kallisto output states a Warning that 6023 transcripts from the GTF are not in the index. Counting the transcript entries 6023 is the amount of all transcripts in the GTF. And this I do not understand.

```
[quant] fragment length distribution is truncated gaussian with mean = 49.5, sd = 0.9
[index] k-mer length: 31
[index] number of targets: 5,341
[index] number of k-mers: 7,341,430
[index] number of equivalence classes: 5,432
Warning: 6023 transcripts were defined in GTF file, but not in the index
[quant] running in single-end mode
[quant] will process file 1: ../fastq_trimmed/60326_trimmed.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 14,936,206 reads, 10,843,287 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 52 rounds
[bstrp] running EM for the bootstrap: 100
[  bam] writing pseudoalignments to BAM format .. done
[  bam] sorting BAM files .. done
[  bam] indexing BAM file .. done
```


Here is an excerpt from the new gtf. 
```
cbs7435_chr1    GenBank gene    5023    6504    .       +       .       "gene_id ""PP7435_Chr1-0001""; gene_name ""PP7435_Chr1-0001"""
cbs7435_chr1    GenBank transcript      5023    6504    .       +       0       "transcript_id ""PP7435_Chr1-0001"";gene_id ""PP7435_Chr1-0001"";"
cbs7435_chr1    GenBank exon    5023    6504    .       +       .       "gene_id ""PP7435_Chr1-0001"";gene_name ""PP7435_Chr1-0001""; gene_name  ""PP7435_Chr1-0001"";"
cbs7435_chr1    GenBank gene    10244   11740   .       -       .       "gene_id ""PP7435_Chr1-0002""; gene_name ""PP7435_Chr1-0002""; "
cbs7435_chr1    GenBank transcript      10244   11740   .       -       0       "transcript_id ""PP7435_Chr1-0002"";gene_id ""PP7435_Chr1-0002"";"
cbs7435_chr1    GenBank exon    10244   11740   .       -       .       "transcript_id ""PP7435_Chr1-0002"";gene_id ""PP7435_Chr1-0002"";gene_name ""PP7435_Chr1-0002"";"
```
And those IDs are also in the fasta which was used for the Index.

```
[...]
>PP7435_Chr1-0001
ATGCTTGCTGAGATTGGGGACTATTTCAGGACAAATAGTAGCAATGGATTCAGTTCTAGC
TGCTATAACAAAGAGAAGCTTTCAGGAGACCTCTTGGAGTCCGATTTTGTGAATTCATCA
TTCGATGACACAACACTCCACTCTATGCTATCTTCTTCAATAAATGCTGATCCGGAGCAA
TCCCAGAAACCACAACAAAGACACAAGAATCAATCCAGTTGCCATCAGGAACTCAAGATT
GAAACAGAAGATCAGCAAGAACCGTATCTATTGCCTGATATGCTTACCAAAAACATATTC
AACTCACAGTCTTCTATGTTTGTCTACTCCAGCATCCCACAAATAAGCTCAGTGCAATCG
TTTATAGACACAAACACCTTTTCCGCTGTTGATGGTGGTGCCGCCCCGGAAGGAAATTCA
TTGTCTGTGGACTCAACTTTAGGTCTATCTTCTGACCAATCATTTGAGAAGCTATACTCT
TACGACCAAAACTTTGAGAAAGAACCACAATCGCCAGCATGTCCCTTAGTAAAATGTGAC
CCAGTAAGCATCATGAAAACATCCACAAACTCATTGGAGACAGCTGTCAACACCAAAAGA
CGAATGTTTCAGCTTAGAAACCAAAATGAAATTGAAAGTCTCAATGTTTCTAGTGACATC
GTTGTTGCGACATCAAAATTTCTCAATCATTCATGGATCCCGCTGATCCGTGGACGTAAT
TTCGGAGGAAGCAACTGCAAACCGCCCAAGAAACCATTATTTCCTGGAGCGCGCTATGTT
ACTGCCCGTCTACGATTGGAATACAGTAGCTGTAAAGATATGTGTCTACCGGAATGGAAC
GAGTATGAACTCGAAGACAGTAGAAGAATCATTCGTATTGAGAGACTGTTCGACTCCAAT
GAAATCGTAGCCTCCTTTTCCATTGTCGGGTCTGCTGTAGAGAACCCGGAAACTAGGCCT
GTATTCAATCCTAATGTCAAAGTGTTGGAAGTTTCGTGTCTAAGATGTCTTACCAACAAC
AACGAGTCTGACGAGGAGAACTGTGTCAACAAAGATTTGGATGGCCGTAACCGCGATATG
GTTAAGGACTCATTTGGATGCAAGTACTATATCACCAGTGTTGAAGTCATAAAGATTATA
GAATTACTGGTCGGAAGCTCTTCAATCTCAGATCCTCATCAAATGAGAAAAGAAAGAGGG
CGTGTGAGATCCAACTTGGCTCAGTTCTGGTCCAAACGCCTAGTTTCTTCGTCCAGGAAA
ACCATGAAACAAGGTTTCTTGCCAACATGCAACGATGATTATTTTGCAGAGCTGGCCCAT
CGTATTAACACATACGACGTCAGAAAACCACGATTATTTGACAAGTGTATAAAGATTTTG
GAATGGTCTAAACTTAAGCCAGCTCTGCAGCGGGCTATGCAAAGTTACTACATGGTTCAA
CTGGATGAATCTAGCAACAAAATTGCAACAGCAAACAATTAG
>PP7435_Chr1-0002
ATGAACTACGAATACAAACACATATCCAAACTAGTCCCTCGCCATAGAGTGCCCTTTTTT
ATTTCCATACTGCTCACTACGGTTCTTAGCCCCGTGACAATGGGGTACGACTCTTTGATG
ATGGGTAACTTGAATGCATTACCACAGTATTTGGATTACTTTCATATAAGAGATGATGCA
GCTCTCTTGGGTTGGATGTCTGCCGCTGTATGGGTCGGAAGTATACTGTCATGCTTCTTA
ATGCAACAACTCTCCGACAAATTGGGTCGTAAAAAATCCATCGTGATTTCGGTCATCGTT
GGACTTGTGGGTGTTATTCTTCAAAGTGCTGCGAAAAATATTGCGATGTTTAGTATTGGC
AGGGTGATTATTGGTTTTGGAACGCAACTGTCGGTGGCAGCGGCTCCGACACTGATCTCC
GAGCTTGCGCTCCCAAAGCACAGAGGGTTTCTAGGTGGACTTGCATTCACGTGTTTCCAA
GTTGGAGCCTTGATTGCTTCTGGTGTCACCTATGGTACCCGCAATATAACAACCACTTGG
GCCTGGAGAATTCCTTCGATTATTCAGTGTGTTCCAGCACTCTTTTCTATTGCGGCTTTG
GTCTTCATTCCCGAATCGCCCCGCTGGCTGATAAGTGTAGGACAATTTGACAAAGCTTCT
GAGGTTATATCTATTGCCGAGGGAATCGATATTGATGCGGGCATGAAACGAGTTCAGGAA
ATTCAAGTTGTTATAGAAGAAGAAAAAGCAAGAGTATCTTCCAGTCCATGGAAAGAAATC
ACAAAAGGAGTTTACAATTGGAAAAGACTTTTTATTATGCTTACTCAGGGTCTAGTGACC
GAGTTGGCTGGGTCCTCTGTTGGGACTTACTACTTTTCCCTGCTGTTGAATCAAGCTGGT
GTTACCGATGTTAGCACTGTTCTACAAGTCGGAATCATCCAATCATCATGGTGTTTAGTA
ATAGCTTTAATAGCGTGCTTTACTTTGGATATTGTTGGAAGAAAGCCCCAGGCGCTATTT
GGTACCACTGGTATGATTGTTTCCTTTTTCATCTTGGGTGGTCTCATTAAGAAATATGGA
AATTCAGACAACGTCTCTGGGTCATATGGAGCCATTGCGTGTATGTTTTTGTTTCAAGGA
TTCTACAATCTTTGCTGGACACCAATGAACACTCTGTATCCTCCGGAAATCTGGCCGTTC
AAACTTCGTTCAGCTGGAGTAACAGTTTTCAAGTTCTTCAACTGTGGTTTTGGTCTTTTC
GGAACTTTCATCTTACCAATAGGTATGTCGAACTTAGGTTGGAAGTTTTACATGCTGAAT
GCAGGATATGATATCATTTTTTTGCCCATAATCTATTTTGTGTGGGTTGAGACGAAGGGT
GTCTCACTCGAAACTCTAGATGAATTGATTGGTTGTCCAGTTGTGCTGGATGAAGAGTCA
CTAAGTTCTGTAGAGCTTGTGCAGGTTGACGGTAGAGGCAAGTCTGACAAACAATGA
[...]
```

The chromosome file is a tab delimited file, looking like this:

cbs7435_chr1 | 2891190
-- | --
cbs7435_chr2 | 2399323
cbs7435_chr3 | 2256069
cbs7435_chr4 | 1820458
cbs7435_mt | 35683

Should there be the extension of .t01 in the transcript names in the gtf or the fasta file?

According to the cDNA transcript file - do you mean the transcript file I use for the kallisto index? I have attached this now, too:

[cbs7435_transcripts.fa.gz](https://github.com/pachterlab/kallisto/files/1736422/cbs7435_transcripts.fa.gz)
[CBS7435_21102016.gtf.gz](https://github.com/pachterlab/kallisto/files/1736423/CBS7435_21102016.gtf.gz)
[seqInfoSize.csv.gz](https://github.com/pachterlab/kallisto/files/1736426/seqInfoSize.csv.gz)

**Comment by Rhinogradentia** [comment]
Just to close this - I have found my error. During the creation of the second gtf file some " where entered mistakenly. The removement of those " solved this problem. Nonetheless I now get another error message when the BAM files are to be indexed after merging.

```
[  bam] indexing BAM file .. [E::hts_idx_push] unsorted positions on sequence #1: 1 followed by 0
 invalid return code when indexing file -1 .. done
```

I have also tried to sort it with samtools and afterwards indexing, but get the same error.

I also ran kallisto quant with another dataset of another organism successfully with genomebam. The gtf file was created with a gff3 from ncbi and manual editing to fit the above requirements.

**Comment by mfansler** [comment]
I realize this is old-ish, but I hit a similar issue and took the time to identify a set of sufficient rules that get proper alignment to the genome.  Unfortunately, they are not as simple as merely sorting the GTF by chromosome, then start position.  Here's what works for me:

1) **Parent entries must come before children**. That is, each gene must come before it's transcripts, and transcripts must come before their exons.
2) **Exons must be ordered by rank, not by chromosome position**.  That is, exons on the positive strand must follow ascending chromosome position, while exons on the negative strand must follow descending chromosome position.

The way I do this is to place all gene entries first, followed by all transcript entries.  Then I append all positive strand exons, sorted in ascending order. Finally, append all negative strand exons, sorted in descending order.

In the shell, it'd go something like this:

    > awk '( $3 ~ /gene/ )' old.gtf > new.gtf
    > awk '( $3 ~ /transcript/ )' old.gtf >> new.gtf
    > awk '( $3 ~ /exon/ && $7 ~ /+/ )' old.gtf | sort -k1,1 -k4,4n >> new.gtf
    > awk '( $3 ~ /exon/ && $7 ~ /-/ )' old.gtf | sort -k1,1 -k4,4nr >> new.gtf

**Comment by inti** [comment]
Hi,
I m having similar issues here. I followed @mschilli87 suggestions and now I get proper positions on the pseudobam file. However, I still get the sorting issue at the end. 

```bash-4.2$ /home/ipedroso/anaconda2/envs/kallisto/bin/kallisto quant -i /home/ipedroso/DATA/ref_genomes/B_terrestris/Bombus_terrestris.Bter_1.0.cdna.all.kallisto_idx_v0.44.0 -o test new.gtf -c /home/ipedroso/DATA/ref_genomes/B_terrestris/Bombus_terrestris.Bter_1.0.dna.toplevel.fa.fai fastq/SRR5125102_1.fastq.gz fastq/SRR5125102_2.fastq.gz

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 22,744
[index] number of k-mers: 32,014,219
[index] number of equivalence classes: 43,034
Warning: 1857 transcripts were defined in GTF file, but not in the index
[quant] running in paired-end mode
[quant] will process pair 1: fastq/SRR5125102_1.fastq.gz
                             fastq/SRR5125102_2.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 23,509,840 reads, 20,611,370 reads pseudoaligned
[quant] estimated average fragment length: 175.995
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,237 rounds
[  bam] writing pseudoalignments to BAM format .. done
[  bam] sorting BAM files .. done
[  bam] indexing BAM file .. [E::hts_idx_push] unsorted positions on sequence #1: 1 followed by 0
 invalid return code when indexing file -1 .. done
bash-4.2$
```
sorting with samtools worked 

```
bash-4.2$ samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 1.7 (using htslib 1.7)
[...]
bash-4.2$ samtools sort -O bam -@ 10 -o test2/pseudoalignments.sort_samtools.bam test2/pseudoalignments.bam
[bam_sort_core] merging from 10 files and 10 in-memory blocks...
bash-4.2$
```

**Comment by pmelsted** [comment]
Hi @inti 

Can you point to the exact GTF and transcriptome fasta file you used for the transcriptome?

- Pall

**Comment by inti** [comment]
Hi @pmelsted , sorry for not declaring that
All files comes from Ensembl and are associated with the Bombus terrestris annotation: https://metazoa.ensembl.org/info/website/ftp/index.html

you can see the SRA id for the fastq on the command line below.

Kallisto version
```
bash-4.2$ ~/anaconda2/envs/kallisto/bin/kallisto version
kallisto, version 0.44.0
bash-4.2$
```

Let me know if any additional information can help you debug this

Build Kallisto index
```
~/anaconda2/envs/kallisto/bin/kallisto index -i ~/DATA/ref_genomes/B_terrestris/Bombus_terrestris.Bter_1.0.cdna.all.kallisto_idx_v0.44.0 ~/DATA/ref_genomes/B_terrestris/Bombus_terrestris.Bter_1.0.cdna.all.fa
```

Re sort GTF following previous comment on this issue
```
ln -s /home/ipedroso/DATA/ref_genomes/B_terrestris/Bombus_terrestris.Bter_1.0.39.gtf old.gtf
awk '( $3 ~ /gene/ )' old.gtf > new.gtf
awk '( $3 ~ /transcript/ )' old.gtf >> new.gtf
awk '( $3 ~ /exon/ && $7 ~ /+/ )' old.gtf | sort -k1,1 -k4,4n >> new.gtf
awk '( $3 ~ /exon/ && $7 ~ /-/ )' old.gtf | sort -k1,1 -k4,4nr >> new.gtf
```
Run Kallisto
```
/home/ipedroso/anaconda2/envs/kallisto/bin/kallisto quant -i /home/ipedroso/DATA/ref_genomes/B_terrestris/Bombus_terrestris.Bter_1.0.cdna.all.kallisto_idx_v0.44.0 -o test new.gtf -c /home/ipedroso/DATA/ref_genomes/B_terrestris/Bombus_terrestris.Bter_1.0.dna.toplevel.fa.fai fastq/SRR5125102_1.fastq.gz fastq/SRR5125102_2.fastq.gz
```

**Comment by mfansler** [comment]
Hi @inti

If I recall correctly, the problem I was seeing in my BAMs when they wouldn't sort/index was that kallisto was generating splice lengths larger than the chromosome sizes (something like, `10M93849007572N40M` in the CIGAR string) or at least extending the other part of the read beyond the end of the chromosome.  Perhaps it's worth checking if you're getting something similar.  I think I checked like so:

    > samtools view pseudoalignments.bam | awk '( $6 ~ /[0-9]{6,}N/ )' | head

or whatever order of magnitude (`{6,}` above) seems unusual for a gap/splice.

I was only seeing this in negative strand transcripts, which is how I guessed that imposing rank order on the exons would fix it.  (@pmelsted: Possibly caused by a negative `int` to `uint` casting issue when making the CIGAR string.)

Anyway, if you aren't seeing the huge gaps in any CIGAR strings, then it might be something else to track down.

**Comment by outpaddling** [comment]
Thanks everyone, for airing out this issue.  This thread helped me figure out how to use --pseudobam.  Can I suggest adding a paragraph to the documentation on --chromosomes explaining the exact format and content requirements, as well as where to get or how to generate one?  I used a GFF from Ensembl and

```
gzcat $gff | head -20 | tail -19 | awk '{ printf("%s\t%s\n", $2, $4); }' \
    | sort -n > chromosome-sizes.tsv
```

**Comment by mschilli87** [comment]
@outpaddling: no need for `| head -20 | tail -19 |` if you run `awk` afterwards: 

```sh
gzcat $gff | awk '(NR > 1) & (NR <= 20){ printf("%s\t%s\n", $2, $4); }' \
    | sort -n > chromosome-sizes.tsv
```

Actually many tools (*e.g.* IGV) use these `chrom.sizes` files and many annotation sources (*e.g.* UCSC) provide it with their annotation files.

**Comment by outpaddling** [comment]
Thanks, yes, there are numerous variations possible for the example command I provided.

My main concern is adding something to the documentation to save future kallisto NOOBs from having to figure out the proper file format and where to get the chromosome sizes.

I also suspect that the sizes will vary slightly depending on the source and I don't know how such variations might affect the BAMs generated.  This might also be worth mentioning in the docs.
