### ISSUE TITLE
Install kallisto v0.44.0 through brew on MacOS Sierra version 10.12.6

### ISSUE THREAD

**Issue by leonfodoulian** [pachterlab/kallisto#158]
Hi,

I would like to install the latest version of `kallisto` (version 0.44.0) through brew. However, the only available version is `kallisto` version 0.43.1. Any plans on updating that? 

Thanks,
Leon

**Comment by ilovezfs** [comment]
0.44.0 is now in Homebrew.

**Comment by pmelsted** [comment]
Thanks @ilovezfs for taking care of this.  I'll try to get the autoreconf fixed for next release so that the brew update is easier
