### ISSUE TITLE
Significant under-alignment of single-end reads

### ISSUE THREAD

**Issue by shahpr** [pachterlab/kallisto#173]
For several SE sequencing datasets, we find that Kallisto performs extremely poorly compared to Hisat2 in terms of total read alignments. For instance, in the example provided below, for a dataset with 2.8M SE reads, Hisat2 was able to align 37.7% of reads while Kallisto was able to align only 2% of reads.

### System
Platform: Ubuntu 14.04.5
Kallisto: 0.44.0
Hisat2: 2.1.0

### Files
All files for reproducing these results can be found here - https://bit.ly/2kCFCpC

### Kallisto
**Index**
`kallisto index -i human_cdna.kallisto human_appris_cdna.fa`
```
[build] loading fasta file human_appris_cdna.fa.gz
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 156 target sequences
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done 
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 157159 contigs and contains 59331715 k-mers 
```

**Run**
`kallisto quant -i human_cdna.kallisto -o ./ --single --single-overhang --fr-stranded -l 33.04 -s 13.82 -t 40 seqdata.fq`
```
[quant] fragment length distribution is truncated gaussian with mean = 33.04, sd = 13.82
[index] k-mer length: 31
[index] number of targets: 19,192
[index] number of k-mers: 59,331,715
[index] number of equivalence classes: 69,660
[quant] running in single-end mode
[quant] will process file 1: seqdata.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 2,815,112 reads, 64,091 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 544 rounds
```

### Hisat2
**Index**
`hisat2-build human_appris_cdna.fa human_cdna`

**Run**
`hisat2 -p 40 --norc --no-spliced-alignment --rna-strandness F --no-unal -x human_cdna -S hisat2.sam -U seqdata.fq --summary-file hisat2.summary --new-summary`
```
HISAT2 summary stats:
	Total reads: 2815112
		Aligned 0 time: 1753376 (62.28%)
		Aligned 1 time: 1000467 (35.54%)
		Aligned >1 times: 61269 (2.18%)
	Overall alignment rate: 37.72%
```

**Comment by pmelsted** [comment]
The input dataset consist of very short reads, the majority are 30bp or shorter. In this case kallisto cannot pseudoalign reads shorter than the `k` parameter used to construct the index, where the default is `k=31`. I ran the dataset with `k=25` and the results were much better, reporting `1009486` reads pseudoaligning. 

However I would suggest using even smaller values, I tried with `k=21`

```
kallisto index -k 21 -i ind.21 human_appris_cdna.fa.gz

[build] loading fasta file human_appris_cdna.fa.gz
[build] k-mer length: 21
[build] warning: clipped off poly-A tail (longer than 10)
        from 156 target sequences
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 371816 contigs and contains 58722062 k-mers

kallisto quant -i ind.21 -o out.21 --single --single-overhang --fr-stranded -l 200 -s 25  -t 4 seqdata.fq.gz

[quant] fragment length distribution is truncated gaussian with mean = 200, sd = 25
[index] k-mer length: 21
[index] number of targets: 19,192
[index] number of k-mers: 58,722,062
[index] number of equivalence classes: 133,369
[quant] running in single-end mode
[quant] will process file 1: seqdata.fq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 2,815,112 reads, 1,109,042 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 530 rounds
```

This results in 39.4% of the reads pseudoaligning, which is on par with what hisat2 is reporting. 

I also modified the `-l` and `-s` parameters, since they reflect the fragment length and not the read length. This information cannot be deduced from the sequencing reads but based on the library prep.
