### ISSUE TITLE
different results from same fq files and index when using different version numbers of kallisto

### ISSUE THREAD

**Issue by shenweima** [pachterlab/kallisto#183]
I use kallisto-0.44.0 and kallisto-0.42.3 to quantify SRR947005 sample. However, I get different results. 
transcript sequences were downloaded from  [IWGSC](https://urgi.versailles.inra.fr/download/iwgsc/IWGSC_RefSeq_Annotations/v1.1/).
[SRR947005_1.fastq.gz]
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR947/SRR947005/SRR947005_1.fastq.gz
[SRR947005_2.fastq.gz]
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR947/SRR947005/SRR947005_2.fastq.gz
```
kallisto index -i IWGSC_v1.1_HC_LC_kallisto IWGSC_v1.1_HC_LC_20170706_transcripts.fasta
kallisto quant -i IWGSC_v1.1_HC_LC_kallisto -t 10 -o SRR947005_kallisto SRR947005_1.fastq.gz SRR947005_2.fastq.gz
```
so which version should I use?

**Comment by mschilli87** [comment]
@shenweima: A quick look at https://github.com/pachterlab/kallisto/releases suggests the following changes might cause the differences:

>* bug fix when read maps to the end of a transcript
>* Switched to a uniform point for the EM algorithm that works better in highly ambiguous cases.

So in this case, I'd rather trust the newer version in the absense of compelling arguments against it.

---
If you decide to go for the newer version also be aware of the following new feature:

> Quantification can now be run in strand specific mode. The experiment can either be `--fr-stranded`, when the first read is on the forward strand or `--rf-stranded` when the first read is on the second strand.
