### ISSUE TITLE
Unique counts

### ISSUE THREAD

**Issue by pimentel** [pachterlab/kallisto#19]
Add unique counts column to output.

I'll do this later today

**Comment by pimentel** [comment]
Do we still want to do this, @pmelsted @lakigigar @nicolasbray

**Comment by pimentel** [comment]
I'm going to do this for the next version unless anyone objects @pmelsted @lakigigar @nicolasbray 

@ttriche does any of your code index columns by number instead of column name? i'm thinking of stuffing uniq_counts next to est_counts (possibly before)

**Comment by ttriche** [comment]
nope, I merge everything out of HDF5 and always index by name

thanks for the heads up!

Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>
