### ISSUE TITLE
Minor Issue: please list scRNA technologies

### ISSUE THREAD

**Issue by dantaki** [pachterlab/kallisto#192]
I had to dig into the source code to find the accepted strings for technology with the `bus` command

This should be in the manual. Also support for 10Xv3 in the future? 

Thanks :) 

```
  << "10Xv1            10X chemistry version 1" << endl
  << "10Xv2            10X chemistry verison 2" << endl
  << "DropSeq          DropSeq" << endl
  << "inDrop           inDrop" << endl
  << "CELSeq           CEL-Seq" << endl
  << "CELSeq2          CEL-Seq version 2" << endl
<< "SCRBSeq          SCRB-Seq" << endl
```

**Comment by lakigigar** [comment]
10xv3 is already supported (via the devel branch). It will be in the next
release. We are also working on an option to allow for command line input
of the barcode and UMI locations.
The command kallisto bus --list shows all technologies supported. But
you're absolutely right that we need to document better in the manual and
we will work on that shortly.
Thanks for the feedback.

**Comment by dantaki** [comment]
`kallisto bus --list` 

Ahh. I should have carefully read the usage better. Thanks for the quick response and for all the work you and your lab provides. :)
