### ISSUE TITLE
possible tarball checksum switcheroo on release 0.43.1 ?

### ISSUE THREAD

**Issue by odoublewen** [pachterlab/kallisto#195]
Hello, the spack project detected a changed checksum on the file [kallisto_linux-v0.43.1.tar.gz](https://github.com/pachterlab/kallisto/releases/download/v0.43.1/kallisto_linux-v0.43.1.tar.gz).

https://github.com/spack/spack/issues/10118

* Looks like kallisto v0.43.1 was [released here on 2017-08-02](https://github.com/pachterlab/kallisto/releases/tag/v0.43.1)
* And it was packaged in [this commit to the spack project on 2017-08-10](https://github.com/spack/spack/commit/ee66c3a7aadce8cd722fcdf822833a3e5c834562#diff-2078bc5581c92b00cba69facf9fc0191)

Presumably, the checksum was correct when the package was made.  Is it possible someone on your side changed this file between 2017-08-10 and now?

FYI  @adamjstewart @hartzell

**Comment by odoublewen** [comment]
Hi @pmelsted  -  Could you confirm that this kallisto tarball is uncorrupted? (and provide the md5sum, possibly)?

https://github.com/pachterlab/kallisto/releases/download/v0.43.1/kallisto_linux-v0.43.1.tar.gz

**Comment by hartzell** [comment]
That tarball unpacks to a linux binary, not a source tree like the `.../archive/...` links do.    Is that what you're looking for?

They don't seem to have uploaded a source tarball as a release artifact.

**Comment by odoublewen** [comment]
@hartzell thanks for catching my error.  This the tarball in question:

https://github.com/pachterlab/kallisto/archive/v0.43.1.tar.gz

**Comment by pmelsted** [comment]
The md5sum is `071e6bfb62be06fd76552298d4cf8144`. I've checked the file that I downloaded on March 20th 2017 on the machine where I build the binaries as well as the file served from github.

**Comment by odoublewen** [comment]
Cheers, thank you very much for confirming!
