### ISSUE TITLE
HDF5 problems

### ISSUE THREAD

**Issue by pmeran** [pachterlab/kallisto#197]
Hello,

running kallisto on a Linux server, I get a meaningful abundance.txt file but the abundance.h5 file is empty.
kallisto throws lots of HDF-DIAG errors (see below), but still manages to produce some results.
Without abundance.h5 I won't be able to feed data into Sleuth - correct ?

I wonder where to start troubleshooting - kallisto, HDF5, data... 
Reported HDF5 problems seem unrelated to my case (hope that's correct).

Here are some details:
- Running kallisto on a remote Linux server (CentOS Linux version 7, Linux 3.10.0-862.14.4.el7.x86_64 x86_64)
- kallisto installation with 'conda install kallisto' seemed to work well (installed locally under $HOME/.local/bin, don't have root access)
- kallisto index (human) downloaded from github
- HDF5 installation seems ok based on h5cc -showconfig command (version 1.10.3, within conda)
- Tried running kallisto multiple times with two different datasets, retrieved with SRA-toolkit -> same error
- Forcing kallisto process into single CPU -> same error

kallisto/Sleuth looks like a great workflow, would be great to get it working.

Thanks for any help !
-----------------------------------------------------
$ kallisto quant -i Homo_sapiens.GRCh38.cdna.all.release-94_k31.idx -o output -b 100 ERR2438108_1.fastq ERR2438108_2.fastq

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 187,626
[index] number of k-mers: 108,619,921
[index] number of equivalence classes: 752,021
[quant] running in paired-end mode
[quant] will process pair 1: ERR2438108_1.fastq
                             ERR2438108_2.fastq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 2,461,141 reads, 1,908,221 reads pseudoaligned
[quant] estimated average fragment length: 170.511
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 948 rounds
HDF5-DIAG: Error detected in HDF5 (1.10.3) thread 139640171398976:
  #000: H5F.c line 444 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1364 in H5F__create(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1615 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #003: H5FD.c line 1640 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #004: H5FDsec2.c line 939 in H5FD_sec2_lock(): file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented'
    major: File accessibilty
    minor: Bad file ID accessed
HDF5-DIAG: Error detected in HDF5 (1.10.3) thread 139640171398976:
  #000: H5G.c line 460 in H5Gopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.3) thread 139640171398976:
  #000: H5G.c line 299 in H5Gcreate2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.3) thread 139640171398976:
  #000: H5G.c line 299 in H5Gcreate2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.3) thread 139640171398976:
  #000: H5D.c line 119 in H5Dcreate2(): not a location ID
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
...

**Comment by antdlc** [comment]
I'm running into a similar problem on windows, same error message. Please advise.

**Comment by pmelsted** [comment]
I'm going to see if I can replicate this with the same version of hdf5. @pmeran Can you check whether this proplem persists if you use the linux binary available from https://github.com/pachterlab/kallisto/releases

**Comment by pmelsted** [comment]
Can you try running this again but with the environment variable `HDF5_USE_FILE_LOCKING=FALSE`

**Comment by pmelsted** [comment]
I just finished compiling hdf5 version 1.10.3 on my machine and I don't see this issue. I think this has to do with the filesystem not enabling locking. I've run into a similar problem with hdf5 files on an NFS with locking and setting the ENV variable fixed the problem.

**Comment by pmeran** [comment]
Hi pmelsted,
I set the environment variable as suggested and everything worked perfectly - no error messages and the abundance.h5 file now has a reasonable size.
Thank you so much for your help !
~ Paul

**Comment by karl616** [comment]
For reference, I got a similar error to this when I ran kallisto with an empty index (an index generated on an empty transcripts file)

**Comment by NadavArbel** [comment]
> I just finished compiling hdf5 version 1.10.3 on my machine and I don't see this issue. I think this has to do with the filesystem not enabling locking. I've run into a similar problem with hdf5 files on an NFS with locking and setting the ENV variable fixed the problem.
> 
> This is the configuration I used for hdf5
> 
> ```
> ./configure --prefix=/hbb_exe --disable-parallel --without-szlib --without-pthread --disable-shared
> ```

Hi,

how do I imply this configuration via the Matlab code ?

Thanks,
