### ISSUE TITLE
Seg Fault in v0.45.0 of pseudo module

### ISSUE THREAD

**Issue by schultzmattd** [pachterlab/kallisto#199]
I've been trying to run through the workflow described in this [paper](https://www.nature.com/articles/s41592-018-0303-9) and [git repo](https://github.com/pachterlab/scRNA-Seq-TCC-prep). The specific Kallisto command is:
`kallisto pseudo -i <path to index> -o <path to output> --umi -b <path to batch file> -t 1`. Each time I get the seg fault:`finding pseudoalignments for all files ...Segmentation fault (core dumped)`

I believe I've isolated the problem to something that changed between version 0.44.0 and 0.45.0 as I've tried the below things that all resulted in the same seg fault, but please let me know if I've missed something:

- Run with index downloaded from [here](https://github.com/pachterlab/kallisto-transcriptome-indices/releases) as opposed to the one I built
- Ran on the test data in the git repo above in addition to my own data set
- Built v0.45.0 from source on the machine I've done testing on

As soon as I reverted to 0.44.0 release, the Kallisto command from the walkthrough above worked. Interestingly, the `pseudo` command works on the test data and index provided in this repository, which is why I assumed the problem had to do with all the other things above before trying reverting to a previous version. My C++ experience is way out of date, so it's not obvious to me what might be causing this, but I wanted to flag this issue in case others have problems.

**Comment by pmelsted** [comment]
Thanks for reporting this and working out the differences in the release. I'll try to see if I can recreate the problem on my machine.

**Comment by pmelsted** [comment]
I've located the bug and am working on a fix.

**Comment by exchhattu** [comment]
I also encountered the same error message  `finding pseudoalignments for all files ...Segmentation fault (core dumped)` while going through the workflow described in this [paper](https://www.nature.com/articles/s41592-018-0303-9) and [git repo](https://github.com/pachterlab/scRNA-Seq-TCC-prep). I used v0.45.0.  Please also let me know once the bug is fixed.

**Comment by pmelsted** [comment]
This has been fixed in the latest release, 0.45.1
