### ISSUE TITLE
Warning: 34767 transcripts were defined in GTF file, but not in the index

### ISSUE THREAD

**Issue by pabloiturralde** [pachterlab/kallisto#200]
Hi, 

It's my first time using Kallisto and I get this warning:

Warning: 34964 transcripts were defined in GTF file, but not in the index

When I run:
kallisto quant -i ~/kallisto_index/bdgp6.93_kallisto_index.fa -o /volumes/piturral/fastq/learning/kallisto_output/C02plusO -b 100 --genomebam --gtf ~/gtf/Drosophila_melanogaster.BDGP6.93.gtf /volumes/piturral/fastq/learning/untrimmed/C02plusO_S4_L001_R1_001.fastq.gz /volumes/piturral/fastq/learning/untrimmed/C02plusO_S4_L001_R2_001.fastq.gz /volumes/piturral/fastq/learning/untrimmed/C02plusO_S4_L002_R1_001.fastq.gz /volumes/piturral/fastq/learning/untrimmed/C02plusO_S4_L002_R2_001.fastq.gz /volumes/piturral/fastq/learning/untrimmed/C02plusO_S4_L003_R1_001.fastq.gz /volumes/piturral/fastq/learning/untrimmed/C02plusO_S4_L003_R2_001.fastq.gz /volumes/piturral/fastq/learning/untrimmed/C02plusO_S4_L004_R1_001.fastq.gz /volumes/piturral/fastq/learning/untrimmed/C02plusO_S4_L004_R2_001.fastq.gz

And I also get these other results:
quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 3,739
[index] number of k-mers: 173,304,639
[index] number of equivalence classes: 16,422
Warning: 34767 transcripts were defined in GTF file, but not in the index
[quant] running in paired-end mode
[quant] will process pair 1: /volumes/piturral/fastq/learning/untrimmed/J02O_S1_L001_R1_001.fastq.gz
/volumes/piturral/fastq/learning/untrimmed/J02O_S1_L001_R2_001.fastq.gz
[quant] will process pair 2: /volumes/piturral/fastq/learning/untrimmed/J02O_S1_L002_R1_001.fastq.gz
/volumes/piturral/fastq/learning/untrimmed/J02O_S1_L002_R2_001.fastq.gz
[quant] will process pair 3: /volumes/piturral/fastq/learning/untrimmed/J02O_S1_L003_R1_001.fastq.gz
/volumes/piturral/fastq/learning/untrimmed/J02O_S1_L003_R2_001.fastq.gz
[quant] will process pair 4: /volumes/piturral/fastq/learning/untrimmed/J02O_S1_L004_R1_001.fastq.gz
/volumes/piturral/fastq/learning/untrimmed/J02O_S1_L004_R2_001.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 44,717,805 reads, 40,364,816 reads pseudoaligned
[quant] estimated average fragment length: 187.16
[ em] quantifying the abundances ... done
[ em] the Expectation-Maximization algorithm ran for 132 rounds
[bstrp] running EM for the bootstrap: 100
[ bam] writing pseudoalignments to BAM format .. done
[ bam] sorting BAM files .. done
[ bam] indexing BAM file .. done

Can someone please explain what does the warning mean? Is it ok to proceed or should I rebuild my indexes?

Thanks!
P.

**Comment by pmelsted** [comment]
This is fine in most cases it just means there are some transcripts that are listed in the GTF file but do not occur in the cdna FASTA file used to create the index.
