### ISSUE TITLE
Bam file is output only when (opt.bootstrap>0)

### ISSUE THREAD

**Issue by Christina-hshi** [pachterlab/kallisto#201]
https://github.com/pachterlab/kallisto/blob/0c950a3579b2691eada652f6a106d14473e4e467/src/main.cpp#L1876

This block needs to be moved out of the "if(opt.bootstrap>0)" block, otherwise the bam is ouput only when (opt.bootstrap>0) even if the "opt.pseudobam" is set. 
Or it is designed in this way to serve some purpose?

**Comment by pmelsted** [comment]
Silly mistake when reorganizing code. Fixed in the latest release.
