### ISSUE TITLE
ONT data

### ISSUE THREAD

**Issue by OxPen** [pachterlab/kallisto#202]
Hello,

I love using Kallisto on my Illumina data and I was wondering if it would be safe to use it with nanopore data?

Many thanks,

Peny

**Comment by pmelsted** [comment]
It's not going to give you any results that make sense. kallisto relies on k-mer matching, with a default of k=31, the error rate and error model of ONT data means that there are most likely no matching k-mers in your reads. I'm not sure if moving to a smaller k would help, but there are other solutions implemented for ONT datasets like minimap.
