### ISSUE TITLE
kallisto 0.45.1 but not kallisto 0.43.0 gives matrix.tcc.mtx instead of matrix.tsv file running pseudo in umi mode

### ISSUE THREAD

**Issue by AlexWeinreb** [pachterlab/kallisto#204]
I am running the scRNA-Seq-TCC-prep example using kallisto **0.45.1**. I could successfully run the `pseudo` command:

```
>>> os.system('python compute_TCCs.py '+json_path)
Running kallisto pseudo:
kallisto pseudo -i /path/mixed.cDNA.idx -o /path/TCC_output/ --umi -b /path/output_results/umi_read_list.txt -t 8
```

However at the end I have only these files:

```
32K matrix.cells
63M matrix.ec
721K matrix.tcc.mtx
582 run_info.json
```

I miss the file matrix.tsv (which is needed for the next step). I tested this with kallisto 0.43.0 and I obtained the .tsv file.

**Comment by AlexWeinreb** [comment]
One possible explanation is that in `main.cpp`, line 2161, you are calling `writeSparseBatchMatrix()`, whereas you should be calling `writeBatchMatrix()` that in turn can call `writeSparseBatchMatrix()`. Please note I am very unfamiliar with C++ and might be completely missing the point.

Alternatively, if it is intentional to only create this "matrix.tcc.mtx" file, could you provide guidance on how to interpret it and how to use it with the `prep_TCC_matrix.py` script from the scRNA-Seq-TCC-prep example?

**Comment by LeoColmet-Daage** [comment]
Hi,

Did you found a solution at this problem ?

I've run kallisto 0.46.0 and end up with the same problem with a matrix.tcc.mtx file instead of .tsv but kallisto seems to have run fine.

**Comment by AlexWeinreb** [comment]
Hi,

Kind of: the scripts established for scRNA-Seq-TCC-prep were made with chromium v1 and work with kallisto v0.43. The concepts first described with these scripts have been adapted into the `kallisto bus` command and the BUS format recently published.

So my take is: the TCC-prep scripts should be considered obsolete, and this github issue closed as wontfix. Anyone interested in using TCCs should use the latest version of kallisto and use the `bus` command.

**Comment by LeoColmet-Daage** [comment]
Well my issue is that `kallisto bus` doesn't support SplitSeq technologies as far as I know.

**Comment by amundhb** [comment]
I have a similar issue trying to run kallisto with fastq files from a Smart-seq2 experiment run without UMI.
Is Kallisto abandoning these use cases?

**Comment by Evi-050** [comment]
Hello, I have the same problem. Did you manage to solve it ?

**Comment by mrichter23** [comment]
> I have a similar issue trying to run kallisto with fastq files from a Smart-seq2 experiment run without UMI.
> Is Kallisto abandoning these use cases?

I have the same problem. Any update on this?
