### ISSUE TITLE
Output transcript-equivalence classes (and respective counts)

### ISSUE THREAD

**Issue by SimoneTiberi** [pachterlab/kallisto#207]
Hi,
I noticed kallisto only outputs transcript-equivalence classes when aligning single-cell RNA-seq.
I’d be very nice if you’d also output them (maybe with an optional tag) when aligning bulk RNA-seq data.
We have a differential splicing tool which starts from transcript-equivalence classes (https://github.com/SimoneTiberi/BANDITS/): so far it only works with salmon alignment (because it outputs equivalence classes and counts), but it would be able to also run with kallisto if equivalence classes information was outputed.

The issue was also mentioned a while ago: https://github.com/pachterlab/kallisto/issues/63

Thanks,
Simone

**Comment by pmelsted** [comment]
The pseudo subcommand does this. Running it on the example provided with the source code

```
kallisto pseudo -i transcripts.kidx -o pseudo_out reads_1.fastq.gz reads_2.fastq.gz
```

generates

```
cat pseudo_out/pseudoalignments.ec
0	0
1	1
2	2
3	3
4	4
5	5
6	6
7	7
8	8
9	9
10	10
11	11
12	12
13	13
14	6,12
15	0,1,2
16	0,1
17	6,11
18	3,12
19	1,2

> cat pseudo_out/pseudoalignments.tsv
0	13
1	319
2	9
3	62
4	664
5	55
6	77
7	47
8	42
9	228
10	4295
11	367
12	34
13	962
14	101
15	768
16	484
17	395
18	321
19	170
```

**Comment by SimoneTiberi** [comment]
Hi Pall @pmelsted ,
thanks a lot, that's what I was looking for.

Follow-up question: how do I relate the numeric transcript ids (0, 1, 2, etc...) to the actual transcript ids? Is that stored somewhere ?

Cheers,
Simone

**Comment by pmelsted** [comment]
They are in the same order as in the FASTA file. The easiest way to get them is to run a quant with a few reads that will generate abundance.tsv which contains the names.

They will be output as a file in the next release, thanks for reporting this.

**Comment by SimoneTiberi** [comment]
Great, thanks for the info!

Simone

**Comment by mapostolides** [comment]
Hi @pmelsted ,

I have a question about the meaning of the contents of the file "pseudoalignments.ec".

Based on your above description, it would seem that the number of lines in this file should be equal to the number of transcripts in the reference transcriptome fasta. However, when I use this tool, this is not the case.

The last line of the "pseudoalignments.ec" file is as follows:

```
1049832 353,354,359,364,368,372,381,383,384,385,386,389
```

This suggests to me that there should be `1049832` targets/transcripts

However, the "number of targets" in my reference transcriptome (which is the number of unique transcripts) is `237,012`

This does not make sense to me, and it seems like the  "pseudoalignments.ec" cannot be used to identify the transcripts based on these cryptic numbers. 

Am I missing something?



For reference, I am using kallisto 0.46.1, and here is the command and output of the command
```
$ kallisto pseudo -i /project/6007998/maposto/reference/kallisto/gencode.v38.transcripts.fa.idx -o ./ /project/6007998/maposto/MODULES/simReads/sim_sample.names_truth.tpm1.1mil_lib_R1.fastq.gz /project/6007998/maposto/MODULES/simReads/sim_sample.names_truth.tpm1.1mil_lib_R2.fastq.gz

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 237,012
[index] number of k-mers: 144,492,748
[index] number of equivalence classes: 1,015,345
[quant] running in paired-end mode
[quant] will process pair 1: /project/6007998/maposto/MODULES/simReads/sim_sample.names_truth.tpm1.1mil_lib_R1.fastq.gz
                             /project/6007998/maposto/MODULES/simReads/sim_sample.names_truth.tpm1.1mil_lib_R2.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 1,000,000 reads, 997,477 reads pseudoaligned
```
 
Thanks,
Michael
