### ISSUE TITLE
kallisto bus 10xv1 processing issues

### ISSUE THREAD

**Issue by yarloz** [pachterlab/kallisto#209]
Dear developers,

During processing of a sample from 10x chemistry version 1 dataset (https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.1.0/pbmc3k) I encountered a following problem: one of columns in output.sorted.txt file contains only one id. I used following order of fastq files: RA, I1, I2. Another time I tried RA, I2, I1 but got the same result except for the fact that replicated id was in a different column. I attached run_info file 
[run_info.txt](https://github.com/pachterlab/kallisto/files/3157944/run_info.txt) and a fragment of output.sorted.txt file 
[output.sorted.txt](https://github.com/pachterlab/kallisto/files/3157951/output.sorted.txt). "AAAAAAAAAAAAAAAAAAAAAAACGCGGAA" fills all first column. Am I doing anything wrong?

-Yaroslav

**Comment by pmelsted** [comment]
The data is in the old format where bcl2fastq was run but not the demux. Fortunately it's easy to fix

The RA file contains the cDNA read and the UMI, to deconvolute them you can run the following awk command

`zcat RA.fastq.gz | awk '(NR-1) % 8 < 4' > cdna_reads.fastq`
`zcat RA.fastq.gz | awk '(NR-1) % 8 >= 4' > umi_reads.fastq`

The I1 file contains the barcode. Using this you can run kallisto bus with the file order of `cdna_reads.fastq umi_reads.fastq I1.fastq`

**Comment by yarloz** [comment]
It worked. Thank you!
