### ISSUE TITLE
Does kallisto bus support single-read scRNAseq data?

### ISSUE THREAD

**Issue by Fronttooth** [pachterlab/kallisto#217]
Dear kallisto authors,
Thanks for developing such a wonderful tool. I am recently using "kallisto bus" to analyze a published scRNAseq dataset. However, the reads are single-end. My question is whether it is possible to analyze single-end data with "kallisto bus".

**Comment by lakigigar** [comment]
Which technology were these reads produced by?

**Comment by Fronttooth** [comment]
> Which technology were these reads produced by?

Thanks very much! They are actually downloaded data from SRA. From the description, these read data were produced with 10xv2 and are paired-end. However, there is only single fastq file per sample. 
In the meanwhile, bam files are provided as well. This comes to my second question, is it possible to process bam file using kallisto bus?

**Comment by lakigigar** [comment]
It is not uncommon to see data formatting that is messed up in the SRA. 

kallisto cannot currently process BAM files directly, however there is a tool for converting BAM to fastq for processing (https://support.10xgenomics.com/docs/bamtofastq)

**Comment by Fronttooth** [comment]
> It is not uncommon to see data formatting that is messed up in the SRA.
> 
> kallisto cannot currently process BAM files directly, however there is a tool for converting BAM to fastq for processing (https://support.10xgenomics.com/docs/bamtofastq)

Thanks a lot!
Have a nice weekend
