### ISSUE TITLE
Kallisto RNA velocity indices

### ISSUE THREAD

**Issue by hkanya** [pachterlab/kallisto#219]
I have samples that uses the GRCh38 reference genome and I would like to conduct RNA velocity on it. I currently have the fastq files generated by cellranger. however I was wondering where to get the cDNA and introns fasta, as well as the transcripts to capture file needed for kallisto. The one available in the getting started tools are for GRCh37 I believe.

**Comment by lambdamoses** [comment]
You can get GRCh38 genome from Ensembl's FTP download or UCSC genome browser. I you use R, you can download it from Bioconductor, with the package `BSgenome.Hsapiens.UCSC.hg38`. The cDNA fasta file can be downloaded from Ensembl. The intron fasta file is a bit more complicated. Not only should the intronic sequences be included, but also a flanking region of length L-1, where L is the biological read length of the technology used (e.g. 98 for 10x v2, 91 for 10x v3). Here's a summary of how to get the intronic fasta file with R:

1. Load a GTF file with exon annotation into R with a package like `rtracklayer` or `plyranges`. This will give you a `GRanges` object. 
2. Convert the `GRanges` object into a `TxDB` object with `makeTxDbFromGRanges` from the package `GenomicFeatures`. 
3. With the `TxDB` object, use the function `intronsByTranscript` to get genomic ranges of introns.
4. Modify the starts and ends of the intronic ranges to include the flanking regions. Also make sure to give each intron a unique name.
5. Get a GRCh38 genome somewhere, and load it into R as either a `BSgenome` or a `DNAStringSet` object.
6. Use the function `getSeqs` from the package `BSgenome` to get the intronic sequences. Make sure that the naming convention of chromosomes in the genome and the GTF file you started with match, such as consistently using just a number or X and Y or consistently using something like "chr1".
7. Then you can write the intronic sequences with flanking regions to disks as a fasta file with `writeXStringSet` in the package `Biostrings`.

Transcript to capture file is a text file with one column that has transcript IDs or intron IDs. The one with transcript IDs will be used to generate the spliced matrix. The one with intron IDs will be used to generate the unspliced matrix.

I'm implementing a new function in the R package `BUSpaRse` to generate all the files needed for Kallisto bus RNA velocity and I'm writing a more comprehensive tutorial on RNA velocity. There're more complications to the flanking regions when exons are shorter than L-1 and what to do with different isoforms of a gene, and this function will address theses complications. I still need to unit test that function before pushing it to GitHub, but you can get started with a simple case.

**Comment by hkanya** [comment]
Thank you! I will start with that

**Comment by hkanya** [comment]
Hi I am unfamiliar with some of the steps you described. How would you modify and intronic regions to include flanking regions. It would be very helpful if you happen to have a sample code available for me to refer to. Thank you again!

**Comment by sbooeshaghi** [comment]
Hello! We are working hard on a tutorial for how to generate indicies for RNA velocity using kallisto | bustools. 

We will let you know as soon as we finish! In the mean time if your reads are 98 bp long and you are using GRCh38 then the tutorial [here](https://www.kallistobus.tools/velocity_tutorial.html) should work for generating spliced and unspliced count matrices.

**Comment by lambdamoses** [comment]
Some example code:
Here `gr` is the `GRanges` from loading the GTF file into R. `fl5` is the length to flank on 5' end of the intron, and fl3 is the length to flank on 3' end of the intron. In a simplest case, you can assume that the flanking length is always L-1.

```r
library(GenomicFeatures)
txdb <- makeTxDbFromGRanges(gr)
introns <- intronsByTranscript(txdb, use.names = TRUE)
start(introns) <- ifelse(strand(gr) == "+", start(introns) - fl5,
                           start(introns) - fl3)
end(introns) <- ifelse(strand(gr) == "+", end(introns) + fl3,
                         end(introns) + fl5)
```

**Comment by hkanya** [comment]
Thank you once again, I will not be needing it until Monday so I will try the new function then

**Comment by lambdamoses** [comment]
Please install the most recent version of `BUSpaRse` (just updated this morning) with `devtools::install_github("BUStools/BUSpaRse")`, and use the function `get_velocity_files`. Example code to generate those files for mouse data:

```r
library(BSgenome.Mmusculus.UCSC.mm10)
library(tidyverse)
library(biomartr)

# Obtain mouse genome
gn <- BSgenome.Mmusculus.UCSC.mm10
# Reformat chromosome naming. OK, I suck at regex
sn <- str_remove(seqnames(gn), "^chr([\\d+XY]_)?") %>% 
  str_remove("^Un_") %>% 
  str_remove("_random$")
sn[sn == "M"] <- "MT"
sn[str_detect(sn, "^(GL)|(JH)")] <- paste(sn[str_detect(sn, "^(GL)|(JH)")], "1", sep = ".")
seqnames(gn) <- sn

# Obtainn GTF file for mice
gtf_fn <- getGTF(organism = "Mus musculus")

# Obtain mouse transcriptome
download.file("ftp://ftp.ensembl.org/pub/release-96/fasta/mus_musculus/cdna/Mus_musculus.GRCm38.cdna.all.fa.gz", "./data/mm_cdna.fa.gz", method = "wget", quiet = TRUE)

# Obtain files for RNA velocity
get_velocity_files(gtf_fn, L = 91, genome = gn, transcriptome = "./data/mm_cdna.fa.gz", 
                   out_path = "./output/out_neuron10k") # Or wherever you want to put the output
```

Alternatively, if you don't want to deal with GTF files, you can get gene annotation from packages like `TxDb.Mmusculus.UCSC.mm10.knownGene` and `TxDb.Hsapiens.UCSC.hg38.knownGene` from Biooconductor to get gene annotation. The cDNA sequences can be extracted from genomic sequences (from packages like `BSgenome.Mmusculus.UCSC.mm10` on Bioconductor) with the gene annotation. The `TxDb` way might be more convenient since `TxDb` objects have standardized names for gene IDs, transcript IDs, and so on, which are not standardized for GTF files. I'm adapting the `get_velocity_files` function for `TxDb` and the Bioconductor annotation ecosystem and it only takes some minor changes from the current version, which works on GTF files.

**Comment by hkanya** [comment]
Hi I'm wondering if the updated package requires R 3.6.0? I am having trouble calling functions after updating the package

**Comment by lambdamoses** [comment]
I don't think so. I used `get_velocity_files` and other functions on R 3.5.2, though the package is tested on R 3.6.0 as required by Bioconductor for all new packages. Which functions do you have trouble calling and what are the error messages?

**Comment by lambdamoses** [comment]
Looks like there're multiple packages exporting the function `read_gff` which I called in that function. `biomartr` also has a function called `read_gff`, and it returns a data frame. I intended to call `read_gff` from the package `plyranges`, which returns a `GRanges` object, whose metadata columns I'm manipulating with `mcols`. I just specifically called `plyranges::read_gff`. Please reinstall `BUSpaRse` and try again, see if it works. https://github.com/BUStools/BUSpaRse/commit/8c8fcedfc192ae1df21d69ccd5aab86a4a52a3c2

**Comment by hkanya** [comment]
I had troubles calling the get_velocity_files function and it seems like the packages weren't installed properly. But if it works on R 3.5.2 I will try to remove and reinstall the package to see if the problem is resolved. Thank you!

**Comment by sbooeshaghi** [comment]
Hello! One can make the velocity indices using the command line following this tutorial 

https://www.kallistobus.tools/velocity_index_tutorial.html

If you find any mistakes please let me know. Otherwise the tutorial should be straight forward.

**Comment by lakigigar** [comment]
See also https://github.com/pachterlab/kallisto-transcriptome-indices/issues/2#issuecomment-510833194

**Comment by lambdamoses** [comment]
I have made changes to the `get_velocity_files` function in `BUSpaRse`. Now you can use `TxDb` or `EnsDb` gene annotation from Bioconductor instead of GTF file, and you no longer need to supply a transcriptome; the transcriptome can be extracted from the genome using gene annotation. If you're still using that function, then please update `BUSpaRse`.

**Comment by lambdamoses** [comment]
Here's the tutorial in R: https://bustools.github.io/BUS_notebooks_R/velocity.html
