### ISSUE TITLE
species velocity indices

### ISSUE THREAD

**Issue by julien-roux** [pachterlab/kallisto#222]
Hi Lior et al.
Thanks for the good work with Kallisto and Bustools!
Do you have any plan to build and release the "velocity" indices on this page as well?

At least it would be nice to share how the unspliced transcript sequences were obtained. It is not clear in the tutorial https://www.kallistobus.tools/velocity_tutorial.html (`introns.correct_header.fa.gz` file)

Best,
Julien

**Comment by lambdamoses** [comment]
Here's the tutorial in R: https://bustools.github.io/BUS_notebooks_R/velocity.html. Again, @julien-roux thank you for your R/Bioconductor implementation!
