### ISSUE TITLE
Unable to build index 

### ISSUE THREAD

**Issue by ag1805x** [pachterlab/kallisto#228]
I am trying to build index with **Kallisto 0.46.0** for Human genome however I am getting an error.

Reference transcript source :
`ftp://ftp.ensembl.org/pub/release-97/fasta/homo_sapiens/cdna/`

Input command:
`kallisto index -i Homo_sapiens.GRCh38.97.cdna.idx Homo_sapiens.GRCh38.cdna.all.fa.gz`

Output: 
```
[build] loading fasta file Homo_sapiens.GRCh38.cdna.all.fa.gz
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 1439 target sequences
[build] warning: replaced 5 non-ACGUT characters in the input sequence
        with pseudorandom nucleotides
[build] counting k-mers ... terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```
RAM info: free -g
```
             total        used        free      shared  buff/cache   available
Mem:              3           0           2           0           0           2
Swap:             1           1           0
```
Architecture:  x86_64

Interestingly I was successful in building in one system with similar architecture while failed in another. What could be the possible reason?

**Comment by pmelsted** [comment]
The `std::bad_alloc` error indicates kallisto ran out of memory. Building the index for the Human transcriptome takes about 3.5G of memory, since you have 3 on your machine, plus a bit of swap it is hard to build. If you have the index file from another machine or system. 

Alternatively you can download a prepared index from https://github.com/pachterlab/kallisto-transcriptome-indices/releases

**Comment by AntonioGPS** [comment]
I am using 0.46.1 under WSL 2 Linux 64bits with 32Gb RAM memory
By using a 346Mb fasta.gz file, I get a std::bad_alloc error

And..
If a decompress the file to its 1.24Gb fasta file, the index is'nt created either

The file for anybody to test can be downloaded from this link
https://denovo.cnag.cat/filebrowser/download/154
