### ISSUE TITLE
Bootstrap fails when no reads map

### ISSUE THREAD

**Issue by pmelsted** [pachterlab/kallisto#23]
and all ECs have a count of 0.

Yes it is a silly input, but it is better to warn agains this, than to run code that will throw an exception.

This fails in mult_.sample()

/Users/pmelsted/work/code/kallisto/src/../ext/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type std::domain_error: nsamp must be -1 or >=1)

**Comment by chrisamiller** [comment]
+1 to this issue. Took me a minute to figure out that my input fastq was an empty file due to upstream failures.  Would be nice to kick out an informative error message when the input doesn't exist or doesn't contain any reads.

**Comment by holmrenser** [comment]
@pimentel @pmelsted I just ran into this on v0.44. It is indeed a silly input, but sometimes this happens in my snakemake workflows. Would be nice to have an informative error message so I can catch it.
