### ISSUE TITLE
10x 5-prime support

### ISSUE THREAD

**Issue by ilyakorsunsky** [pachterlab/kallisto#232]
I noticed that the available technologies for 10x are v1, v2, and v3, which from my understanding all use 3 prime chemistry. Does kallisto bus also support 5 prime chemistry?

**Comment by sbooeshaghi** [comment]
Yes. The barcode and UMI structure in the FASTQ files are the same so just pick the proper chemistry version and you're good to go. Here is a validation test on 5' data from 10x https://support.10xgenomics.com/single-cell-vdj/datasets/2.2.0/vdj_v1_hs_nsclc_5gex

![NSCLC_tumor_v2](https://user-images.githubusercontent.com/10369156/67590686-8b4b0e00-f710-11e9-89d3-d606bf12b1a4.png)

**Comment by benplm** [comment]
Thank you for providing this validation test, @sbooeshaghi !
I'm wondering if, when running "kallisto bus" on 10x 5' PE libraries, both mates are used for the pseudo-alignment on the transcriptome. From kallisto's manual I get that only the second mate will be used, am I correct?
(for example, with a configuration of [16pb barcode]+[10bp UMI]+[124bp insert] for the read1 and [150bp insert] for the read2).
