### ISSUE TITLE
bootstrap matrices only deterministic in single threaded mode

### ISSUE THREAD

**Issue by karl616** [pachterlab/kallisto#236]
There seems to be a random factor in the bootstrapping. Running kallisto in multi-threaded mode like:

```
kallisto quant -i transcripts.index -b 10 --seed=42 --fr-stranded  -t 5 -o out1 file_R1.fastq.gz file_R2.fastq.gz
kallisto quant -i transcripts.index -b 10 --seed=42 --fr-stranded  -t 5 -o out2 file_R1.fastq.gz file_R2.fastq.gz
diff <(h5dump out1/abundance.h5 ) <(h5dump out2/abundance.h5 ) | less
```

results in differences between the two instances.

For now this seems to be resolved by running with only a single thread (`-t 1`).

Would it be possible to make bootstrapping deterministic with multiple threads as well?

**Comment by pmelsted** [comment]
The seeds are passed to each bootstrap instance in a deterministic fashion. The only non-deterministic part is which bootstrap finishes first in the threading, this determines the order of the bootstraps. I suspect you can reorder the bootstrap values to get identical results.
