### ISSUE TITLE
seg fault in "single" batch mode in kallisto pseudo

### ISSUE THREAD

**Issue by roddypr** [pachterlab/kallisto#237]
Hi,

We got a seg fault with the following:
kallisto pseudo -i kallistoindex -o kallisto_out -l 50 -s 0.00001 --single -b TestBatch2.txt

This is due to the batch mode for single-end reads. It works fine adding the file directly as an argument to the command. It works fine with batch for paired-end reads.

the batch looks like:
#Cell1 file_1
cell1 file.fastq.gz

We are using 0.46.1
We had no problem using 0.46.0

Thanks

**Comment by pmelsted** [comment]
This bug has been fixed in the development branch and will make it into the next release.
