### ISSUE TITLE
writing pseudoalignments to BAM format .. Segmentation fault

### ISSUE THREAD

**Issue by A-Catarina** [pachterlab/kallisto#249]
Hi!!

I am having the weirdest error while running kallisto 0.46.1 on genomebam mode. Everything runs fine until writing pseudoalignments to bam format where the segmentation error occurs and instead of the correct output file I get a set of (empty) temporary bam files. This did not happend when running with pseudobam mode or plain quant using the same input files.

![image](https://user-images.githubusercontent.com/52798083/74385599-d2f2c400-4deb-11ea-8094-3546f48e900a.png)

Kind regards,
Catarina

**Comment by pmelsted** [comment]
Genomebam mode does two passes over the input, therefore it has to be a real file and not a stream. From the screenshot it looks like you are processing the file via `<( ..)` before inputting into kallisto. 

You can write processed fastq to disk, gzipped or not, and process directly with kallisto

**Comment by A-Catarina** [comment]
Thanks, that was indeed the problem! It's working perfectly now. 
Sorry for the dumb question and not reporting a real issue but I have been struggling with this for quite some time now.

Best wishes.

**Comment by pmelsted** [comment]
I'll try to put in code that automatically detects this and warns the user.

**Comment by Evi-050** [comment]
Hello, I face this problem: " [  bam] writing pseudoalignments to BAM format .. Segmentation fault"
and I have no idea how to fix it. I have smartseq.2 single reads, dual indexed ( this is who the fastq reads look like: 
@NB551291:160:H55CJBGXF:1:11101:12947:14932 1:N:0:TAAGGCGA+GCGATCTA
GGCGTGTCCCGCGCGTGTGGGGGGAACCTCCGCGTCGGTGTTCCCCCGCCGGGTCCGCCCCCCGGGCCGCGGTTTT
+
AAAA/EAAAEEEA/EEAEEEAEE/E/EEEEEEAEA/EEEEEEEEEEEEEAEEEE/E/EAEEAEEE6AE/</EA/// )

I run this pipeline: 
 [user@vm-129-49 mouse1.fastq_gz]$ kallisto quant -i /ad/vlachou/scRNAseq.2/kallisto_analysis/gencode.vM24.transcripts.idx --output-dir /ad/vlachou/scRNAseq.2/kallisto_analysis/kallisto_quant/gencode_indexed/mouse1 --pseudobam --genomebam --gtf /vlachou/scRNAseq.2/kallisto_analysis/gencode.vM24.annotation.gtf.gz  --single -l 530 -s 150 -t 16 *fastq.gz 

this is the outcome message:
[quant] fragment length distribution is truncated gaussian with mean = 530, sd = 150
[index] k-mer length: 31
[index] number of targets: 142,552
[index] number of k-mers: 120,672,054

[quant] finding pseudoalignments for the reads ... done
[quant] processed 482,819,438 reads, 208,880,499 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,273 rounds
[  bam] writing pseudoalignments to BAM format .. Segmentation fault
I tried the same with esnembl as reference but I get the same problem.

If anyone could help me out, it would be great!
Thanks
