### ISSUE TITLE
Unable to build index for large genome

### ISSUE THREAD

**Issue by davidfstein** [pachterlab/kallisto#271]
I am attempting to build an index for the Axolotl genome (~32 Gigabases). I started a job on my cluster with 64 GB of allocated memory. The job ran for over an hour and then was cancelled because it had consumed more than the 64 GB of allocated memory. Is this much memory consumption expected? Any idea how much memory I will need to allocate for a genome of this size?

**Comment by lakigigar** [comment]
You seem to be constructing the index from the genome sequence, whereas you should be building it from the transcriptome (mRNA) sequences.
