### ISSUE TITLE
 downstream analysis in SMART-SEQ2

### ISSUE THREAD

**Issue by jojikt2007** [pachterlab/kallisto#274]
Dear Sina  

Can you guide me how to generate count matrics after generating output from kallisto pseudo --quant -i reference/index.idx -o ./mop_SMARTseq/out/ -b smart-seq_batch.txt -t 16 for downstream analysis in SMART-SEQ2

I got this many filles from kallisto pseudo --quant 

1, matrix.abundance.mtx 
2, matrix.cells  
3, matrix.ec  
4, matrix.fld.tsv  
5, matrix.tcc.mtx   
6, run_info.json  
7, transcripts.txt

Which file I should use for generating isoform count matrices file for downstream analysis

Thanks in advance 
JKT

**Comment by winni2k** [comment]
Hi JKT, I think the paper and links mentioned in this closed issue probably answer your question:

https://github.com/pachterlab/kallisto/issues/235

**Comment by sbooeshaghi** [comment]
JKT please see this repo for how to process Smartseq2 data. We will be coming out with a tutorial soon.

https://github.com/pachterlab/BYVSTZP_2020/

**Comment by asumann** [comment]
Hi @sbooeshaghi !

I couldn't find a tutorial there. Is it available now?

All the best,
Asuman
