### ISSUE TITLE
How to generate count matrix after generating output from kallisto pseudo 

### ISSUE THREAD

**Issue by jojikt2007** [pachterlab/kallisto#275]
Can you guide me how to generate count matrix after generating output from kallisto pseudo --quant -i reference/index.idx -o ./mop_SMARTseq/out/ -b smart-seq_batch.txt -t 16 for downstream alalysis in SMART-SEQ2

I got this many files from Kallisto pseudo --quant

1, matrix.abundance.mtx
2, matrix.cells
3, matrix.ec
4, matrix.fld.tsv
5, matrix.tcc.mtx
6, run_info.json
7, transcripts.txt

Which file I should use for generating isoform count matrices file  for downstream analysis

**Comment by winni2k** [comment]
I am also looking for more information on how to interpret the output of `kallisto pseudo`, which I am also using with some single-end SMART-SEQ2 data.

**Comment by winni2k** [comment]
This issue appears to point to more information on how to handle a SMART-SEQ2 analysis: https://github.com/pachterlab/kallisto/issues/235

**Comment by winni2k** [comment]
I think this script should help you solve this question: https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/scripts/make_adata.py

**Comment by sbooeshaghi** [comment]
Yes @winni2k is right. That repo contains analysis of SmartSeq-2 data, feel free to browse and ask any questions there.

**Comment by winni2k** [comment]
I can confirm that the script above is working for me on my own SMART-Seq2 analysis.
