### ISSUE TITLE
quant ignores bootstrap flag and does not generate H5

### ISSUE THREAD

**Issue by umasstr** [pachterlab/kallisto#277]
Kallisto quant runs to completion without error on this mac laptop, but no H5 is generated (only TSV and runinfo). It seems that the bootstrap flag is also ignored as "n_bootstraps=0" despite the "-b 30". I haven't run quant on a mac and cannot reproduce the problems on various linux distros. Any tips would be greatly appreciated!

![image](https://user-images.githubusercontent.com/44478133/90418832-ab730180-e083-11ea-9a6e-99296a9fac22.png)

**Comment by boxofbox** [comment]
I had the same issue but when running quant it provided a warning message that kallisto was not compiled with hdf5 support.
If you're building from source you can specify a cmake flag  (-DUSE_HDF5=ON) to do so.

**Comment by umasstr** [comment]
thanks for the info! I brew installed, so perhaps I should try compiling myself.
