### ISSUE TITLE
kallisto pseudo

### ISSUE THREAD

**Issue by alex-d13** [pachterlab/kallisto#304]
Hi, thanks for the great tool!

I was just wondering, in what case would somebody use the `kallisto pseudo` command? Since you state, that it can be used in single cell experiments.

Cheers :)

**Comment by sbooeshaghi** [comment]
`kallisto pseudo` can be used to quantify full length SmartSeq data. Here is an example:

https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/scripts/kallisto_smart-seq.sh

**Comment by alex-d13** [comment]
Hi, I tried the following:

I ran `kallisto pseudo` 3 times, each time with a single cell in batch mode. Then I want to merge these cells with `kallisto merge` and quantify transcripts abundances. It seems like the merge command does not do this, since my result folder only has the following files:  
`matrix.cells  matrix.ec  matrix.tcc.mtx  run_info.json`
So no abundance tables..

But in the `kallisto merge` description it states, that it 

> Computes equivalence classes for reads and quantifies abundances

Can you help me out here?

**Comment by alex-d13** [comment]
Ok I guess I would have to use the `--quant` argument. Can I then merge the results?
Also, is there some documentation on the result files of `pseudo` or `merge`?

**Comment by sbooeshaghi** [comment]
To merge the results of `pseudo --quant` you can use this script: https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/scripts/make_adata.py

Also it doesn't seem like we have specific documentation for the `--quant` argument, however documentation on `pseudo` and `quant` can be found here: https://pachterlab.github.io/kallisto/manual

I hope that helps.

**Comment by alex-d13** [comment]
Hi again,

i am still testing around with the `kallisto merge` command and was wondering if it is possible to get the TPM values somehow? I was comparing the results of `kallisto pseudo --quant` with `kallisto quant` for a single fastq-pair; only the `quant` command provides me with TPMs is that right? Or can I somehow also generate TPMs with `pseudo` and `merge`?

Thanks!
