### ISSUE TITLE
kallisto for CEL-Seq2 data - low counts

### ISSUE THREAD

**Issue by dgrun** [pachterlab/kallisto#309]
I'm trying to map CEL-Seq2 data with kallisto and obtain very low UMI counts. I learned that the reason could be that kallisto/bustools discards all UMIs that occur across different genes in the same cell. To solve this for CEL-Seq2 which has a lot of these shared UMIs (UMI length 6bp) I'm trying to count using bustools project/text and a perl script to collect the UMIs per gene and cell barcode.

These are the bustool commands:

bustools project -o project -g cDNA_to_genes.txt -e matrix.ec -t transcripts.txt output.correct.sort.bus
bustools text -o text_out counts/project.bus 

To map the equivalence classes to gene IDs and count the UMIs from the text_out file, I'm assuming that the equivalence class numbers in the project.ec file correspond to the order in the project.genes.txt file created by bustools project. Is this assumption correct? The counts I'm getting do not match at all with the (reasonable) bwa output (although the total UMI count per cell is in good agreement, suggesting that only the order of the genes is wrong).

Is there another solution for such short UMI protocols?

**Comment by Yenaled** [comment]
Yes, and we expect to make this feature available in a future bustools release (which should happen very, very soon).

If you want to preview this feature, you can use my branch here (which contains several other things we plan to incorporate in a future release):
https://github.com/Yenaled/bustools/tree/smart-seq3

Briefly, when you use bustools count, specify the option --umi-gene and this will handle the "same UMI sequence, different genes" events.

**Comment by dgrun** [comment]
Thanks! Sounds great. But when I run 
bustools count --umi-gene 
from your repo it says 
count: unrecognized option '--umi-gene'


And could you please also briefly comment on my other question regarding the mapping of gene IDs to equivalence classes after bustools project?

**Comment by Yenaled** [comment]
Did you git clone the correct branch?

You need to do git clone -b smart-seq3 https://github.com/Yenaled/bustools.git

It works on my end.

And yes, that's how bustools project should work.

**Comment by dgrun** [comment]
Thanks, now it works. It improves the sensitivity, but counting from the text fill still yields substantially higher UMI counts, and is much better correlated with bwa mappings. Ist there an additional filtering?

**Comment by Yenaled** [comment]
The only other thing I can think of (which results in loss of UMI counts) is multimapping. --umi-gene handles cases where the same UMI sequence appears across multiple BUS records but the BUS records are associated with different genes. However, if a single BUS record is mapped to two different genes (i.e. kallisto pseudoaligned a single read to transcripts from two different genes), that BUS record will still be discarded in bustools count. The -m option can distribute the counts among multimapping reads (e.g. one gene gets 0.5 counts and another gene gets 0.5).

The UMI collapsing is a very basic algorithm (probably the most basic one imaginable): identical UMIs are collapsed and gene-level UMI counts are tallied up and that's it. If the --umi-gene option is specified, bustools marches through the BUS records with identical barcode+UMIs and if the intersection of those BUS records is just one gene, it adds +1 count to that gene, but as soon as it encounters a different gene (i.e. intersection 0) -- previous gene still has the +1 count from before but bustools starts again from that new gene and adds +1 count to that new gene. And this goes on until all the BUS records with that same barcode+UMI are processed.

**Comment by dgrun** [comment]
That's strange. When I'm going through the ec file in my script I'm collecting only the equivalence classes mapping to an individual gene. I thought that this would way I would get rid of multimappers. But still I obtain many more UMIs per gene...
And in my bwa pipeline I'm also discarding multimappers, and the results of the two approaches are largely consistent.

**Comment by Yenaled** [comment]
Interesting. Can you share the output of "bustools inspect" on your BUS file and also the first few lines of your matrix (.mtx) files?

**Comment by dgrun** [comment]
Sure!

Here is the output from inspect:

Read in 3357834 BUS records
Total number of reads: 12016320

Number of distinct barcodes: 192
Median number of reads per barcode: 12823.000000
Mean number of reads per barcode: 62585.000000

Number of distinct UMIs: 4096
Number of distinct barcode-UMI pairs: 436651
Median number of UMIs per barcode: 1684.000000
Mean number of UMIs per barcode: 2274.223958

Estimated number of new records at 2x sequencing depth: 1448734



And the head of my mtx:

%%MatrixMarket matrix coordinate real general
%
192 55353 171925                                                  
1 43 1
1 92 1
1 96 1
1 166 1
1 240 1
1 276 1
1 345 1
1 432 1
1 563 1
1 656 1
1 726 1
1 741 1
1 845 1
1 868 1



Just to add this - when I run my custom pipeline on 10x data, the counts are pretty much identical to the standard bustools output.

Where should I send my busfile etc.?

**Comment by Yenaled** [comment]
Thanks, if it's possible for you to attach the files via email (or send a google drive link) to dsull@ucla.edu -- that would be great; I'll look into it.

**Comment by Yenaled** [comment]
Closing this issue; there was an issue and bustools was just updated to fix it. Now, running bustools count --umi-gene will properly handle CEL-seq2 data and works as expected. Discussed this with @dgrun over email whom I thank for working with me to resolve this issue. Cheers!
