### ISSUE TITLE
Missing <limits> header import for GCC 11 in MinCollector.cpp

### ISSUE THREAD

**Issue by mmguar** [pachterlab/kallisto#319]
As highlighted here: https://stackoverflow.com/questions/4798936/numeric-limits-was-not-declared-in-this-scope-no-matching-function-for-call-t
GCC 11 and others require an explicit import of <limits>, which is not present in MinCollector.cpp and thus kallisto fails to compile.
Adding 
`#include <limits>`
fixes the problem.

**Comment by Yenaled** [comment]
Fixed in 0.48.0
