### ISSUE TITLE
run time for index and quant mode is so long...

### ISSUE THREAD

**Issue by dahun73** [pachterlab/kallisto#321]
Hello!

I first try to use kallisto. In manual, index time is just 30min ~ 1 hour in the labtop. But in my case, it takes so long time. I used mouse genome and 16 threads. 

my command here:
kallisto index -i mm10.GRCm38.kallisto mm10.gencode.fa
kallisto quant -i ~/BioResource/Reference/mm10.GRCm38.kallisto -o kallisto/rep1_Control/ --rf-strand -t 16 01.Clean/rep1_Control.R1_val_1.fq.gz 01.Clean/rep1_Control.R2_val_2.fq.gz -b 100

Is there any problem in my command..?

Thank you in advance!

Dahun

**Comment by mschilli87** [comment]
Kallisto is meant to be run indexing the transcriptome, not the genome. Does mm10.gencode.fa contain (spliced!) transcript sequences or genome contigs?

**Comment by dahun73** [comment]
@mschilli87  Thank you for reply :)

"mm10.gencode.fa" is genome contigs.

Actually, quant mode out is also something wrong.

![image](https://user-images.githubusercontent.com/52641420/129931760-6a971361-1b0f-437d-93e3-0a08a3ea6301.png)

**Comment by mschilli87** [comment]
Well by indexing the genome you basically ask `kallisto quant` to pseudoalign to the contigs. So instead of quantifying the reads coming from specifc transcripts, you assign them to chromosomes. Replace you genome.fa by a transcriptome one, re-index (much less memory required and faster than for the genome) and re-quantify.

**Comment by dahun73** [comment]
@mschilli87 Oh, I'm sorry. I forgot to use transcriptome fasta. After using transcriptome fasta, it works well!! Thanks :)

**Comment by mschilli87** [comment]
@dahun73: Gald I could help. If you problem is resolved, don't forget to close this issue so nobody else wastes time trying to help you. :wink:
