### ISSUE TITLE
problem reding output

### ISSUE THREAD

**Issue by rmsalatino** [pachterlab/kallisto#329]
Hello, 
I am new using kallisto and I was a bit confused about the output. I run the quantification with the following command: 
kallisto quant -i kallistoGRCh38.idx -o kallisto_OS3_1_out --genomebam --gtf Homo_sapiens.GRCh38.104.chr_patch_hapl_scaff.gtf.gz --chromosomes chrom.txt OS3-1-plus_S46_L001_R1_001.fastq.gz OS3-1-plus_S46_L001_R2_001.fastq.gz 

but when I examined the output looked like I got the quantification by chromosome instead to get the quantification by gene.
<img width="732" alt="Screen Shot 2021-11-01 at 2 36 35 PM" src="https://user-images.githubusercontent.com/82396361/139723276-897c5876-d8ba-4670-bc1d-f600aadd7272.png">

Maybe I am missing something really simple here but I went through the manual and I don't seem to be able to find the problem.
I would really appreciate any suggestion.

thanks!

**Comment by Yenaled** [comment]
How did you create your index? Seems to me like you indexed the reference genome rather than the reference transcriptome (i.e. cDNA sequences).

**Comment by rmsalatino** [comment]
you right, my bad. As soon as I saw your replay I realized that... you are totally right. 
thanks you very much for the quick response.
