### ISSUE TITLE
kallisto index file not found kallistoIndex/human_pc.idx

### ISSUE THREAD

**Issue by YasenHICKER** [pachterlab/kallisto#336]
Here is the command I am trying to run but the above error is appearing to me:

cd ~/workdir/kallisto_align
R1="$HOME/workdir/sample_data/HBR_Rep1_ERCC-Mix2_Build37-ErccTranscripts-chr22.read1.fastq.gz"
R2="$HOME/workdir/sample_data/HBR_Rep1_ERCC-Mix2_Build37-ErccTranscripts-chr22.read2.fastq.gz"
kallisto quant -i kallistoIndex/human_pc.idx -o human_pc_bam $R1 $R2 --pseudobam

Error: kallisto index file not found kallistoIndex/human_pc.idx
Error: file not found /home/youssef/workdir1/sample_data/HBR_Rep1_ERCC-Mix2_Build37-ErccTranscripts-chr22.read1.fastq.gz
Error: file not found /home/youssef/workdir1/sample_data/HBR_Rep1_ERCC-Mix2_Build37-ErccTranscripts-chr22.read2.fastq.gz

As a result, I need anyone to help me to fix this issue as soon as possible.

**Comment by Yenaled** [comment]
I'm closing this because this not a kallisto issue. The files you supplied simply don't exist on your computer (perhaps you put them in the wrong directory). I can't find your files for you on your own computer.
