### ISSUE TITLE
kallisto index segmentation fault on 32bit architectures

### ISSUE THREAD

**Issue by merkys** [pachterlab/kallisto#338]
func_tests for kallisto 0.48.0 runs into segmentation fault on the following:
```
./func_tests/runtests.sh: line 13: 12638 Segmentation fault      ./src/kallisto index -i ./func_tests/basic7.idx -k 7 ./func_tests/simple.fasta 2> /dev/null > /dev/null
```
Observed on i386, armel, armhf and mipsel, so seemingly on all 32bit architectures.

**Comment by Yenaled** [comment]
kallisto does not support 32-bit architectures. Even previous versions of kallisto would not work on 32-bit systems. One of the requirements for running kallisto is a 64-bit system as stated here: https://pachterlab.github.io/kallisto/source

**Comment by merkys** [comment]
Thank you for confirming. Closing the issue as resolved.
