### ISSUE TITLE
Kallisto splice lengths larger than the chromosome sizes

### ISSUE THREAD

**Issue by asolee** [pachterlab/kallisto#344]
Hi  @mfansler.

regarding this issue in Kallisto --genomebam:
https://github.com/pachterlab/kallisto/issues/155#issuecomment-434563284

I know that it is an old issue.
I'm using Kallisto for quantification analysis, but also after the re-organization of the gtf file:
```
awk '( $3 ~ /gene/ )' old.gtf > new.gtf
awk '( $3 ~ /transcript/ )' old.gtf >> new.gtf
awk '( $3 ~ /exon/ && $7 ~ /+/ )' old.gtf | sort -k1,1 -k4,4n >> new.gtf
awk '( $3 ~ /exon/ && $7 ~ /-/ )' old.gtf | sort -k1,1 -k4,4nr >> new.gtf
```
The problem of larger splices is still unsolved.
Did you manage to solve this problem?

**Comment by asolee** [comment]
Hi  @mfansler.
I know that it is an old issue.
I'm using Kallisto for quantification analysis, but also after the re-organization of the gif file:
```
awk '( $3 ~ /gene/ )' old.gtf > new.gtf
awk '( $3 ~ /transcript/ )' old.gtf >> new.gtf
awk '( $3 ~ /exon/ && $7 ~ /+/ )' old.gtf | sort -k1,1 -k4,4n >> new.gtf
awk '( $3 ~ /exon/ && $7 ~ /-/ )' old.gtf | sort -k1,1 -k4,4nr >> new.gtf
```
The problem of larger splices is still unsolved.
Did you manage to solve this problem?

**Comment by mfansler** [comment]
@asolee the GTF you uploaded is missing `gene` entries. Perhaps you used `>` instead of `>>` in the second command for reordering?

**Comment by asolee** [comment]
Hi @mfansler,
Thanks a lot for your answer.

I corrected the GTF file, but the problem persists.

This is the correct GTF file:
[kallisto_correct.gtf.txt.zip](https://github.com/pachterlab/kallisto/files/8462093/kallisto_correct.gtf.txt.zip)

**Comment by mfansler** [comment]
The negative strand exons are still in ascending order - they need to be reversed (i.e., the `r` in the `sort -k1,1 -k4,4nr`).

**Comment by asolee** [comment]
Thanks again for the answer.
I organized the negative strand exons in descending order, but I still have long larger splices in the .bam file.

new gtf file:
[kallisto.gtf.zip](https://github.com/pachterlab/kallisto/files/8466186/kallisto.gtf.zip)

**Comment by mfansler** [comment]
Not sure then without examples. Pull some out - if you don't see a pattern you can try adding some here, but this sounds like a debugging case. If you can add a small subsample of FASTQ to that gives issue, then consider posting that too.

**Comment by asolee** [comment]
sure I send you some examples on bam file and the correspondence on fastq.

[bam_example.txt](https://github.com/pachterlab/kallisto/files/8472177/bam_example.txt)
[fastq_example.txt](https://github.com/pachterlab/kallisto/files/8472188/fastq_example.txt)

**Comment by asolee** [comment]
I'm using the Kallisto version 0.48.0

**Comment by mfansler** [comment]
That is also the version I tried.

Are the FASTQs public? Can you provide a more extensive subset? (100K reads, with *both* mates)
