### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by aalajamii** [pachterlab/kallisto#350]
Hi there, 

I have been using `kb` to generate a count matrix as per the discussion in [issue 342](https://github.com/pachterlab/kallisto/issues/342). Everything had been running smoothly until the point I have put an additional gene/sequence in the cDNA.fasta file. The error message that I started receiving is the following:

```
INFO [count] Generating count matrix ./counts_unfiltered/cells_x_genes from BUS file ./output.unfiltered.bus
ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/anaconda3/lib/python3.9/site-packages/kb_python/validate.py", line 55, in validate_mtx
    scipy.io.mmread(path)
  File "/anaconda3/lib/python3.9/site-packages/scipy/io/mmio.py", line 76, in mmread
    return MMFile().read(source)
  File "/anaconda3/lib/python3.9/site-packages/scipy/io/mmio.py", line 436, in read
    return self._parse_body(stream)
  File "/anaconda3/lib/python3.9/site-packages/scipy/io/mmio.py", line 636, in _parse_body
    I[entry_number], J[entry_number] = map(int, l[:2])
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.9/site-packages/kb_python/main.py", line 1381, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/anaconda3/lib/python3.9/site-packages/kb_python/main.py", line 608, in parse_count
    count(
  File "/anaconda3/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.9/site-packages/kb_python/count.py", line 1370, in count
    count_result = bustools_count(
  File "/anaconda3/lib/python3.9/site-packages/kb_python/validate.py", line 121, in inner
    validate(path)
  File "/anaconda3/lib/python3.9/site-packages/kb_python/validate.py", line 88, in validate
    VALIDATORS[ext](path)
  File "/anaconda3/lib/python3.9/site-packages/kb_python/validate.py", line 57, in validate_mtx
    raise ValidateError(f'{path} is not a valid matrix market file')
kb_python.validate.ValidateError: ./counts_unfiltered/cells_x_genes.mtx is not a valid matrix market file
```

I have tried resolving this issue by looking into `I[entry_number], J[entry_number] = map(int, l[:2])` and changing it to _float_, but this hasn't been fruitful. Any leads please?

**Comment by Yenaled** [comment]
Can you show the full sequence of commands you're running?

If you want to add an additional sequence, I'd recommend modifying the GTF file and the FASTA file, and running kb ref to generate a new kallisto index, cDNA fasta, and T2G file. This will avoid breaking things.

**Comment by Yenaled** [comment]
When you add your new gene/sequence, did you add the gene name to the rna_t2g.txt?

**Comment by aalajamii** [comment]
Yes

**Comment by aalajamii** [comment]
Yes, I did. And then I rebuilt the index

**Comment by Yenaled** [comment]
Hmm, ok, I guess I'll need to see your rna_t2g.txt file (and possibly your fasta file as well but let's start with the t2g file since it's smaller) to diagnose the problem. Can you email them to me? (email in my github profile). Adding a sequence should not create problems.

**Comment by aalajamii** [comment]
Sent!

**Comment by Yenaled** [comment]
Closing this, but for readers out there: The issue was that a line in the .mtx file contained some hidden binary characters (\x00 aka NUL). For some reason, the computer decided to throw in a bunch of binary gibberish in the output filestream.

This issue does not occur on my computer, and the original poster tried it on a different computer and found that the issue does not occur there either. Therefore, it's a computer-specific/system-specific issue. For anyone that encounters an issue like this: Try using a different computer, or upgrading your computer to the latest OS version, or upgrading your C/C++ compiler and compiling bustools from source.
