### ISSUE TITLE
Kallisto with less Bootstrap 

### ISSUE THREAD

**Issue by SynatKeam** [pachterlab/kallisto#353]
Dear Authors, 

Hope you are well. I am running Kallisto in my laptop using paired end fastq files from bulk RNA seq data. I am very keen to run in 100 bootstraps, which is the default. However, it takes a bit longer in a normal laptop. I am not interested in isoform analysis, but just basic differentially gene expression. Therefore, I am wondering whether I can run with just 10 bootstrap instead of 100. Does this make any differences. Looking forward to hearing from you soon. Have a nice day.

Kind Regards,

Synat

**Comment by Yenaled** [comment]
Yes, you can do fewer bootstraps -- you just get better estimates when you have more bootstraps. This is not unique to kallisto but is something true of bootstrapping in general.

In the paper https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1419-z -- 30 bootstraps were used.

Bootstrapping is only used for sleuth and if you're doing differential expression using other models, bootstrapping is not necessary at all.

Also, try using more threads if it's slow.

**Comment by SynatKeam** [comment]
Thanks you, Yenaled for your insight and suggestion. Have a great day!

Regards,
synat

**Comment by SynatKeam** [comment]
Hi Author, 

Sorry to reopen the question. I used the code chunk below to run paired end alignment with 100 bootstraps. I still like to run in 100 bootstrap. if I wanted it to run faster, what addition of code should I add. 

kallisto quant -i transcripts.idx -o output -b 100 reads_1.fastq.gz reads_2.fastq.gz 

Hope you could help. Have a great day.

Kind Regards,

synat

**Comment by Yenaled** [comment]
kallisto quant --threads=12 -i transcripts.idx -o output -b 100 reads_1.fastq.gz reads_2.fastq.gz

**Comment by SynatKeam** [comment]
Dear Yenaled, 

thank for your prompt response. I will experiment it. 

Kind Regards,

Synat

**Comment by SynatKeam** [comment]
Thank you, professor. it worked faster than before. thank for your great work. 

Regards,

synat
