### ISSUE TITLE
Paired-end scRNA-seq with UMIs but no cell barcode

### ISSUE THREAD

**Issue by biobenkj** [pachterlab/kallisto#358]
Is it possible to specify the `-x` option to allow for running paired-end data with the UMI on read 2, but no cell barcode? The strandedness would be `--rf-stranded` as well.

Reads look like:

Read 1
biological read

Read 2
UMI (8bp) + Linker (6bp) + biological read

I've tried: `-x -1,-1,-1:1,0,8:0,0,0,1,14,0` with `--paired --rf-stranded` with no reads being mapped. If I strip out the UMI and place it in the header and hard trim the first 6 bp of the linker, I can map the data no problem with mapping rates >75%.

Thanks so much for a great tool!

**Comment by sbooeshaghi** [comment]
Hi Ben, I think this is possible. You'll have to make a change within `kallisto` and then recompile. The change can be made here:

https://github.com/pachterlab/kallisto/blob/83bde908c403ea4014b5092a243e5c7240f48dd5/src/main.cpp#L1303

You would have to specify a new technology (I believe by specifying the barcode as (-1,-1,-1) it will make all reads have the same barcode). 
```cpp
} else if (opt.technology == "BIOBENKJ_ASSAY") {
  busopt.nfiles = 2;
  busopt.bc.push_back(BUSOptionSubstr(-1,-1,-1));
  busopt.umi.push_back(BUSOptionSubstr(0,0,8));
  busopt.seq.push_back(BUSOptionSubstr(0,14,0));
  busopt.seq.push_back(BUSOptionSubstr(1,0,0));
  strand = ProgramOptions::StrandType::RF;
}
```

Which assay is this for?

**Comment by biobenkj** [comment]
Hi Sina,

Thanks so much! This assay would be for STORM-seq, our plate-based, ribo-reduced single-cell total RNA protocol (https://www.biorxiv.org/content/10.1101/2022.03.14.484332v3). We've updated the protocol to include UMIs and want to quantify using kallisto (also need to upload the new data to GEO/SRA).

I've just started making updates to kb-python (https://github.com/biobenkj/kb_python) and ngs-tools (https://github.com/biobenkj/ngs-tools). Are there other places that I'm missing that I'll need to make changes?

Thanks again!

**Comment by sbooeshaghi** [comment]
Super cool. And that should be it!

**Comment by Yenaled** [comment]
The -1,-1,-1 thing for barcodes might not work without the following adjustment in ProcessReads.cpp:

Under line 1642 (aka right below `for (auto &bcc : busopt.bc) {` ), insert the following piece of code

```
      if (busopt.bc[0].fileno == -1) { // Don't care about barcodes
        bad_bc = false;
        blen = BUSFORMAT_FAKE_BARCODE_LEN;
        memcpy(bc, binaryToString(0, blen).c_str(), blen); // Give each read a fake barcode
        break;
      }

```

Then you're golden. This change will automatically be included in the next release of kallisto.

**Comment by Yenaled** [comment]
Yes, the first file in the command is the 0 index file and the second file in the command is the 1 index file. I would recommend just changing the file indices in the main.cpp file (the first argument of BUSOptionSubstr), so it doesn't mess up with the --paired and --rf-stranded options that are supplied since it seems you want the R2 read to be the one mapping to the sense strand.

**Comment by biobenkj** [comment]
Great! I've modified to the following, and unfortunately, I think I must still be doing something incorrect.

I've made the following change to `main.cpp` and recompiled:

```
else if (opt.technology == "STORM-SEQ") {
        busopt.nfiles = 2;
        busopt.bc.push_back(BUSOptionSubstr(-1,-1,-1));
        busopt.umi.push_back(BUSOptionSubstr(1,0,8));
        busopt.seq.push_back(BUSOptionSubstr(0,0,0));
        busopt.seq.push_back(BUSOptionSubstr(1,14,0));
        busopt.paired = true;
        strand = ProgramOptions::StrandType::RF;
      }
```

When I run the following, it seems to still not estimate a mean fragment length:

```
~/git_repos/kallisto/build/src/kallisto bus -i hsapiens.idx -o L9_test -x STORM-seq L9_L000_R1_001.fastq.gz L9_L000_R2_001.fastq.gz

[bus] Note: Strand option was not specified; setting it to --rf-stranded for specified technology
[index] k-mer length: 31
[index] number of targets: 251,121
[index] number of k-mers: 149,770,767
[index] number of equivalence classes: 1,081,682
[quant] will process sample 1: L9_L000_R1_001.fastq.gz
                               L9_L000_R2_001.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 1,414,124 reads, 1,018,171 reads pseudoaligned
[quant] estimated average fragment length: 0
```

If I run with `kallisto quant` I see that it does estimate an average fragment length and also seems to treat them as a "pair" instead of as a sample in `kallisto bus`. Is this expected?

```
~/git_repos/kallisto/build/src/kallisto quant -i hsapiens.idx -o L9_quant_test --rf-stranded L9_L000_R1_001.umi.fastq.gz L9_L000_R2_001.umi.fastq.gz

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 251,121
[index] number of k-mers: 149,770,767
[index] number of equivalence classes: 1,081,682
[quant] running in paired-end mode
[quant] will process pair 1: L9_L000_R1_001.umi.fastq.gz
                             L9_L000_R2_001.umi.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 1,394,192 reads, 1,006,326 reads pseudoaligned
[quant] estimated average fragment length: 291
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 951 rounds
```

Thanks again!

**Comment by biobenkj** [comment]
Please note that `kallisto quant` was run after stripping the UMI out of the read, placing in the header of the fastq and hard trimming the 6 bp linker. Some reads became too short and were removed - which is why the number of reads are different between the two `kallisto bus` and `kallisto quant`.

**Comment by Yenaled** [comment]
Re: fragment length

kallisto bus doesn't give fragment lengths if you have UMIs (because UMIs don't need to be length-normalized). So what you're doing is correct. (You see that output simply because kallisto by default outputs that whenever you tell it your data is paired-end).

**Comment by biobenkj** [comment]
That makes sense! Closing for now. Thank you both!

**Comment by sbooeshaghi** [comment]
Hi @biobenkj, thank you for bringing up this issue. To help solve this kind of sequence read identification problem, we've been working on a project for specifying the sequencing-library structure for various genomics assays and I think it would be helpful and instructive if you could add STORM-seq to the catalogue via a PR.

https://github.com/IGVF/seqspec

The project is called `seqspec` and the goal is to create a machine-readable file for specifying sequencing libraries making it easier to share "read structures". If you're curious to see an example of a `seqspec` specification, take a look at the [sci-RNA-seq](https://github.com/IGVF/seqspec/blob/main/assays/sci-RNA-seq/spec.yaml). To get started we've provided a [`template.yaml`](https://github.com/IGVF/seqspec/blob/main/assays/template.yaml) in the `assays` folder. 

We envision that STORM-seq and other assays can be fully specified with `seqspec` and that FASTQ files can be easily parsed with the specification in-hand avoiding the kinds of read misidentification problems that often arise in genomics.

**Comment by biobenkj** [comment]
Hi @sbooeshaghi and @Yenaled - I have one more, naive, question to ask regarding bustools count for this type of data. Since we have a UMI, paired-end, full length protocol, is this a situation where running the EM algorithm for multi-mappers (similar to kallisto quant) isn't crazy?

So something like this:
```
bustools count -o bus_count/cell_x_gene -g ens101_ref/ens101_ercc92_t2g.txt -e matrix.ec -t transcripts.txt --umi-gene --genecounts --em output.sorted.bus
```

Apologies for all the questions and thanks in advance!

**Comment by biobenkj** [comment]
Never mind - after reading #339 it seems like I was confusing the "bulk" EM approach vs what occurs with distributing UMI counts across genes from multi-mappers. Doesn't seem like it would necessarily "hurt" to run with `--em`, just adding some run time?

**Comment by Yenaled** [comment]
I would actually not recommend using the bustools --em approach because it operates at gene-level rather than transcript-level.

We do have a workflow to do transcript-level quantification (which improves gene-level quantification as well). In `kb count`, use the --tcc option.

(If you want to see the exact kallisto/bustools commands that are run in that workflow, use the --dry-run option in `kb count`).

**Comment by Yenaled** [comment]
Don't worry about the ProcessReads.cpp change -- just include the storm-seq technology for your pull request and I'll handle the rest.
