### ISSUE TITLE
Autoconf failure with MacOS

### ISSUE THREAD

**Issue by devang-mehta** [pachterlab/kallisto#363]
Get the following error when trying to build from source so as to maintain h5 support. 

`configure: error: cannot find required auxiliary files: config.guess config.sub`

**Comment by Yenaled** [comment]
This will fix it: https://github.com/pachterlab/kallisto/issues/303#issuecomment-884612169

**Comment by devang-mehta** [comment]
It failed at `autoreconf -i` with the following error:
```
Can't exec "aclocal": No such file or directory at /opt/homebrew/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
autoreconf: error: aclocal failed with exit status: 2
```

**Comment by Yenaled** [comment]
It seems like you're missing aclocal. You need to make sure you have all the automake tools installed and that they're in your path. Try `brew install automake` 

If this doesn't work, let me know and I'll reopen the issue.
