### ISSUE TITLE
Issues with chromosome file in kallisto

### ISSUE THREAD

**Issue by st4302** [pachterlab/kallisto#369]
Hello,

I recently updated the indexes I am using for kallisto from version 93 to 96. I tried to create genomebam files and I used the same chromosome file I was using in the past. However, now I am getting the following warning:

Warning: could not find chromosomes for 491 transcripts
Warning: 25039 transcripts were defined in GTF file, but not in the index
Does that mean that I need to find a new chromosome file? Where can I find a recent one? I am interested in GRCm38. The one we had on file is from 2016. I am using the kallisto index and gtf file from the prebuilt indexes in kallisto.

I am using kallisto 0.44.0. I noticed that some people were having that issue with kallisto 0.46.2 (https://github.com/pachterlab/kallisto/issues/254). I really don't want to change the kallisto version unless I absolutely have to. I also noticed that the chromosome file that I have is the same as the one mentioned in the ticket.

Thank you

**Comment by Yenaled** [comment]
I am closing this because i responded on biostars. If you have any further questions, we can discuss further there.
