### ISSUE TITLE
Error: number of equivalence classes does not match index (kallisto quant-tcc)

### ISSUE THREAD

**Issue by shashkat** [pachterlab/kallisto#377]
Hello there, so I have an issue with the `kallisto quant-tcc` command. Basically, I have processed some tabula sapiens fastq files using kallisto, with the command `kallisto pseudo --quant`, and obtained all the typical output files like matrix.abundances.mtx, matrix.tcc.mtx, etc. The expression information in them is at the transcript level. However, I also want the information at the gene level, and I read that I can do that using the `kallisto quant-tcc` command, giving it the appropriate gtf file, the index file and the matrix.tcc.mtx file.

However, when I am running the `kallisto quant-tcc` command, giving the appropriate parameters (the index.idx file which was originally used to process the fastqs, gtf file, and tcc file), it gives the following error:

`Error: number of equivalence classes does not match index. Found 373,922, expected 372,074`

So there are 373,922 equivalence classes in the matrix.tcc.mtx file, and 372,074 in the index file.. Could someone please explain why is it expected that the equivalence classes in both the files are the same, and how I can correct it?

Thank You!

**Comment by Yenaled** [comment]
A few things here:

1) kallisto pseudo is deprecated -- I highly recommend at some point migrating to kallisto bus instead and use bustools to get your final matrix files. There's an easy workflow to do so in the kb_python package which you can pip install (simply create an index using kb ref, then use kb count -x bulk --tcc, and supply other relevant options). New features will be added to kallisto bus in future releases, and kallisto pseudo will be removed in the next release of kallisto.

2) you cannot use the original index file in quant-tcc. The reason for this is that new equivalence classes are created during the pseudoalignment. When run in bus mode, a new condensed index (containing those new ECs) is produced.

3) You can supply the GTF file to kallisto pseudo via the -g option to get gene-level abundances if you want to use kallisto pseudo.

**Comment by shashkat** [comment]
@Yenaled Thanks a lot for your response. I also have another question..

So the contents of the matrix.tcc.mtx file contains the counts of the different equivalence classes, but what exactly are the contents of the matrix.abundance.mtx file?

In many places I find that the values in the abundance file are in TPM. However, they dont sum to 1 million for any cell. Also, they are in decimal so they arent just raw reads. So what exactly are they, and how are they obtained from the tcc data?

Thanks!

**Comment by Yenaled** [comment]
@shashkat the abundance counting done at gene-level for kallisto pseudo is a naive counting method: Basically just summing up the transcript counts for each gene. An EM algorithm is NOT run to resolve ambiguities (multimapping is resolved by a simple division operation, hence the decimal values).

For kallisto quant-tcc, abundances are in TPM units and an EM algorithm is run (kallisto quant-tcc will produce identical output to kallisto quant [aka the same results as the classic bulk RNA-seq analysis that kallisto has been doing for many years])

If you want TPM abundances are your units (which requires running the quant-tcc EM algorithm), you'll need to run kallisto in bus-mode.

**Comment by Yenaled** [comment]
Actually, another thing kallisto quant-tcc can do (to get gene-level TPMs) is take in the transcript names (as ordered in the cDNA FASTA file) instead of the newly generated index.

But overall, I'd say just use the bus option if possible.

**Comment by shashkat** [comment]
Thanks a lot @Yenaled ! It makes sense now. I am gonna switch to the bus option as it seems the better long term option.
