### ISSUE TITLE
Quantify the expression of transposable elements

### ISSUE THREAD

**Issue by zhaotao1987** [pachterlab/kallisto#380]
Hi, 

We are interested in the expression of transposable elements (TE). 
An intact TE contains LTR regions and CDS region that encode transposases, which behave like polycistronic mRNA. 
I was wondering if I could use these CDS regions of each TE as the reference to quantify TE expression using Kallisto.
Another question is should I use all TE CDS as references, or TE CDS plus entire predicted genes as the reference. 
The RNA-seq data we used is just normal illumina-based RNA-seq data. 

Thanks very much!
Best, Tao

**Comment by zhaotao1987** [comment]
Thank you so much Max for the response. 
So you suggested we use all predicted TE plus predicted genes for kallisto quantification, and for the predicted TEs, we use only the coding regions (exclude the flanking LTR regions). 
And after this, I am not quite aware of the purpose you've proposed, we then further classify the mapped reads (those mapped onto TE CDS) to families, using a consensus sequence for each TE family(?) In order to have an idea such as which clade of TE highly expressed? 
Thanks very much! 
Best, Tao

**Comment by maximilianh** [comment]
If you mean "coding sequence" with CDS, I dont know why you would restrict
yourself to that. I'd use the entire sequence of all TEs.

And yes, I would first align to the TE genome sequences and then map from
that to the consensus, not align to the consensus with kallisto.

**Comment by zhaotao1987** [comment]
I see, thanks very much. 
Because I think the entire TE contains LTR regions and the coding regions, something similar as showed in this figure.
In theory, the LTR regions are not transcibed ? 
![image](https://user-images.githubusercontent.com/16197676/229766823-d7fa054a-0f63-4f79-940a-790fd9cdf766.png)

**Comment by maximilianh** [comment]
Oh LTRs probably not, but I imagine for many other elements, they have
sequences that are neither LTR nor coding and I'd keep them. Yes, probably
a detail, but also makes it easier to take the entire sequence from the
repeatmasker output rather than start to filter on CDS annotations in there.

**Comment by zhaotao1987** [comment]
I see, thanks!
