### ISSUE TITLE
libhdf5.so.7 error  with ubuntu binary

### ISSUE THREAD

**Issue by Perugolate** [pachterlab/kallisto#39]
I get the following with the ubuntu binary v0.42:

```
kallisto: error while loading shared libraries: libhdf5.so.7: cannot open shared object file: No such file or directory
```

maybe linked against an older version of libhdf5?

**Comment by pimentel** [comment]
Hello @Perugolate. Thanks for the comment. The new Linux binaries have been statically linked. Please check them out:

http://pachterlab.github.io/kallisto/download.html

This should fix the problem. Let us know if you have any issues. I'm going to close this issue for now. Please feel free to comment on it if it is unresolved with the new binaries.


Thanks,

Harold
