### ISSUE TITLE
conceptual question: assigning ambiguous reads to an isoform

### ISSUE THREAD

**Issue by saralinker** [pachterlab/kallisto#394]
Hi at Kallisto, 

First, thanks for the great tool!

I have a quick conceptual question and am not sure where to post it. It comes back to the likelihood estimator when calculating counts. In the case where Kallisto is estimating counts for a gene with more than one isoform, I'm unclear as to whether a read that is compatible with only one isoform would influence how another read that is compatible with both isoforms is counted. In short, is the information from the different reads shared within a transcript?

Here's an example to better illustrate my question:

I have a case where two isoforms are expressed:
Isoform 1: exonA-exonB-exon-C-exonD
Isoform 2: exonA-exonB-CRYPTICexon

For this experiment, RNA-seq data is coming from degraded RNA that's been pulled down with probe sets rather than the standard polyA approach so there will be some exons that have better coverage than others.

I expect Isoform 1 to be highly expressed and Isoform 2 to be more lowly expressed. However, if I don't have good coverage over exons C and D (unique to Isoform 1), then all of my reads for isoform 1 will be ambiguous for isoform 2. On the same note, the majority of my reads that are uniquely aligning to either isoform would be coming from the "CRYPTICexon." In this case, would Kallisto assume that reads that are compatible with exonA+exonB (non unique exons) are actually coming from Isoform 2? 

Is it possible that I would falsely be inflating my expression estimates for Isoform 2 if this is the case?

Any help would be very much appreciated!

**Comment by Yenaled** [comment]
If all your reads are coming from exonA and exonB and CRYPTICexon, then isoform 2 would get higher expression (because of the EM algorithm).

For isoform 1 to get higher expression, you'll need reads mapped to an exon unique to isoform 1, otherwise there's an identifiability problem. There is no way for any model to produce higher counts for isoform 1.

This is one reason why gene-level aggregation gets you more accurate results than transcript-level estimates.

**Comment by saralinker** [comment]
Thanks @Yenaled that helps a lot!

**Comment by saralinker** [comment]
Thanks @Yenaled that helps a lot!
