### ISSUE TITLE
Kallisto bustools on single end Smart-seq3 data 

### ISSUE THREAD

**Issue by kvn95ss** [pachterlab/kallisto#398]
Pretty much the title, we have smart-seq3 data which was sequenced as single ends instead of pair ends.

The method `-x SmartSeq3` requires 4 fastq.gz files as input, index R1, index R2, Read 1 and Read 2.

Can this be used for single end reads? Or is it used on paired end reads only?

**Comment by Yenaled** [comment]
Already answered here: https://github.com/pachterlab/kb_python/issues/216

**Comment by kvn95ss** [comment]
Following, will reply there if I have any further queries.
