### ISSUE TITLE
cmake_minimum_required_version

### ISSUE THREAD

**Issue by Perugolate** [pachterlab/kallisto#40]
The following error message is printed when attempting to compile with older cmake versions:
```
CMake 2.8.8 or higher is required.  You are running version 2.8.7
```
But I think this should be 2.8.12 or higher because of _add_compile_options. This is corrected in `INSTALL.md` but not in the code but caught me out (the only 12.04 cmake backport I found was 2.8.11, so I went for the laziest option...)

**Comment by pmelsted** [comment]
Thanks for letting us know. This was fixed in #38
