### ISSUE TITLE
un-aligned transcripts

### ISSUE THREAD

**Issue by tsofiya** [pachterlab/kallisto#401]
Hi,
I am using kallisto bus to align a small costume library we prepared in the lab.
I get only 62% aligned transcript, and I want to analyze what happened.
Is there a way get  or produce a list of the un-aligned transcripts so I can examine it?
Also, is there a way to get the number of UMIs per gene per cell?
Thanks!

**Comment by Yenaled** [comment]
If you want to get the reads that are unaligned, see my post here: https://www.biostars.org/p/425547/

If you want to figure out which targets (i.e. transcripts) specifically were not aligned, then you can look in the matrix.ec file -- each equivalence class contains a comma-separated set of transcripts (zero-indexed based on transcripts.txt) in the second column of that file. The equivalence class exists in the third column of the BUS file when you use bustools text.

To get the number of UMIs per gene per cell, I recommend just doing the typical downstream analysis (import the results matrix into an anndata object in python and make plots on your own).

**Comment by tsofiya** [comment]
can you refer me to what you mean by equivalence class? 
I open the files you suggested- matrix.ec and output after converting to .txt files- but how can I see which transcript were aligned?

**Comment by tsofiya** [comment]
Thank you!
I want the opposite finding the reads that are unaligned.
But when I run like you advise with -n this command:
kb count -i /index.idx -g t2g.txt -o results/bus/ -x 0,0,8:0,8,21:1,0,0 ./data/GE_S1_L001_R1_001.fastq.gz ./data/GE_S1_L001_R2_001.fastq.gz -w whitelist.txt -n --overwrite
I get the following error:
kb: error: unrecognized arguments: -n

**Comment by Yenaled** [comment]
In my post, I suggested running kallisto bus with the -n option, not kb count. kb-python is a wrapper around kallisto that enables a subset of functionalities of kallisto to be run easily; it currently does not support the -n option.

You can view the exact kallisto commands that kb count uses by using the --dry-run option or the --verbose option.

**Comment by tsofiya** [comment]
Thank you.
After running with kallisto (btw, improved the percentage of aligned transcripts for me) with -n I got the bus file and transformed it to text.
But the last column is all ones, so it can be the number of the aligned reads as you wrote in your post. (The Jason file wrote over 300K were aligned). I get 4 columns. 
I saw in this tutorial:
https://www.youtube.com/watch?v=LUX3ugvSPp8&list=PLsbYv-R7OqYyHkPjzkCyFbSWEE8BoPGgE&index=3
that the third col should be the read number, but there are a lot of different barcode+UMI that have same number.
Am I missing something?

**Comment by tsofiya** [comment]
I run kallisto now (not kb python) with -n flag and got  bus files have 4 columns, and the last col contains only ones, so it cannot be read number as you said in the post.
Am I missing something? It also produced the exact same bus file when running without -n.

**Comment by Yenaled** [comment]
What command are you using to view the BUS file?

You should be using: bustools text -pf /path/to/bus/file.bus
