### ISSUE TITLE
kallisto bustools vs. kb-python output differences 

### ISSUE THREAD

**Issue by tsofiya** [pachterlab/kallisto#402]
Hi,
I using kb to align my library with pre-built indexes, and analyzing it using transcript to genes file from the same source. 
In a different issue I was told to use kallisto bus instead, so I built a new index (using the same index gave me versions error) and while the json file indicates higher percentage of aligned transcripts, the matrix.ec file is much smaller, and when I open the results in R (tutorials from https://www.kallistobus.tools/) I only see 13 genes (I had more then 10,000 using kb). 
I used the same command as shown in the json file of kb (with -n the only addition):
kallisto bus -i Mus_musculus.GRCm39.cdna.all.idx -o results/bustools/ -x 0,0,8:0,8,21:1,0,0 -t 8 -n ./data/GE_R1_001.fastq.gz ./data/GE_R2_001.fastq.gz
Also, I don't seem to find a tutorial for creating transcripts to gene file for the specific transcriptome I used.

Thanks in advance,
Tsofiya

**Comment by Yenaled** [comment]
kb-python and kallisto bus will be consistent.

When you run kb count, run it with --dry-run or --verbose to see the exact commands being used (you can literally copy and paste those commands to obtain the same result, because all kb count does is call kallisto bus).
As for version differences, if you type kb count (without any options), you should see the path to the kallisto binary somewhere in the help menu (for me, it's /Users/dsull/miniconda3/lib/python3.8/site-packages/kb_python/bins/darwin/kallisto/kallisto). You should use that binary file when running kallisto to replicate kb count.

The reason you're seeing these version differences is that kb-python is currently at version 0.27.3 (which uses kallisto 0.48.0) while kallisto's latest version is 0.50.0.

Not relevant to addressing your issue but: For a t2g files, you shouldn't try creating the t2g file from a transcriptome -- you should run kb ref which takes in a genome and GTF and outputs a t2g file alongside a kallisto index.

This will all become less confusing when we release the new version of kb-python (alongside which we will release documentation). Sorry that we're in a sort of migration process right now and trying to update our tools.

**Comment by tsofiya** [comment]
Hi,
First thank you for the fast and גקאשןךקג שמד'קרץ
Second, I did run --dry-run to check that the command are identical, but when I copied the command I got:
Error: incompatible indices. Found version 10, expected version 12
This is why I used the new index I created with kallisto index. But the matrix I'm getting is from some reason smaller (790KB compared to ~18000KB for kb-python), and it seems like something went wrong with the alignment.  It does use the newer version of kallisto 0.50.0

**Comment by Yenaled** [comment]
Yeah, exactly, the "version 12" is only present in kallisto 0.50.0 (previous version of kallisto use "version 10" of the index). You could just try installing an older version of kallisto.

Also, you should note that when you run kallisto bus with the -n option, you can NOT use that BUS file generated (i.e. you can't do downstream analyses) -- that BUS file is specifically for looking at read numbers and extracting certain reads of interest. That's most likely why you're seeing strange results.

**Comment by tsofiya** [comment]
This doesn't explain why when I run it with version 12 kallisto I don't get a good count matrix- I only get 13 genes...
I produced the index with:
kallisto index -i cdna.idx Mus_musculus.GRCm39.cdna.all.fa.gz
and then run kallisto bus:
kallisto bus -i cdna.idx -o results/bustools/ -x 0,0,8:0,8,21:1,0,0 -t 8 ./data/GE_S1_L001_R1_001.fastq.gz ./data/GE_S1_L001_R2_001.fastq.gz
which is the same command kb-python uses when I run --dry-run.
And the gene matrix only has 13 genes.

**Comment by Yenaled** [comment]
It's difficult for me to uncover what's wrong unless you actually provide me with details.

kallisto index prints out a bunch of output. kallisto bus writes things to standard output when you run it. There is a run_info.json file in the output folder. You need to tell me which bustools commands you're running (bustools sort, bustools correct, bustools count, etc.) and what their outputs are (you haven't shown me a single bustools command that you ran).

**Comment by tsofiya** [comment]
command: kallisto index -i cdna.idx Mus_musculus.GRCm39.cdna.all.fa.gz
out put:
[build] loading fasta file Mus_musculus.GRCm39.cdna.all.fa.gz
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 653 target sequences
KmerStream::KmerStream(): Start computing k-mer cardinality estimations (1/2)
KmerStream::KmerStream(): Start computing k-mer cardinality estimations (1/2)
KmerStream::KmerStream(): Finished
CompactedDBG::build(): Estimated number of k-mers occurring at least once: 100821983
CompactedDBG::build(): Estimated number of minimizer occurring at least once: 24726371
CompactedDBG::filter(): Processed 212495854 k-mers in 116873 reads
CompactedDBG::filter(): Found 100749224 unique k-mers
CompactedDBG::filter(): Number of blocks in Bloom filter is 689214
CompactedDBG::construct(): Extract approximate unitigs (1/2)
CompactedDBG::construct(): Extract approximate unitigs (2/2)
CompactedDBG::construct(): Closed all input files

CompactedDBG::construct(): Splitting unitigs (1/2)

CompactedDBG::construct(): Splitting unitigs (2/2)
CompactedDBG::construct(): Before split: 685212 unitigs
CompactedDBG::construct(): After split (1/1): 685212 unitigs
CompactedDBG::construct(): Unitigs split: 1459
CompactedDBG::construct(): Unitigs deleted: 0

CompactedDBG::construct(): Joining unitigs
CompactedDBG::construct(): After join: 634230 unitigs
CompactedDBG::construct(): Joined 51257 unitigs
[build] building MPHF
[build] creating equivalence classes ...
[build] target de Bruijn graph has k-mer length 31 and minimizer length 23
[build] target de Bruijn graph has 634230 contigs and contains 100838597 k-mers


and then I run:
kallisto bus -n -i cdna.idx -x 0,0,8:0,8,21:1,0,0 -t 4 ./data/GE_S1_L001_R1_001.fastq.gz ./data/GE_S1_L001_R2_001.fastq.gz -o results/bustools/

[bus] Note: Strand option was not specified; setting it to --unstranded for specified technology
[index] k-mer length: 31
[index] number of targets: 116,873
[index] number of k-mers: 100,838,597
[quant] will process sample 1: ./data/GE_S1_L001_R1_001.fastq.gz
                               ./data/GE_S1_L001_R2_001.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 487,336 reads, 318,602 reads pseudoaligned

I use other bustools in the the following steps, but at this point I'm getting a very small matrix.ec.

**Comment by Yenaled** [comment]
Those steps look fine to me; run it just like that (except remove -n from kallisto bus) then move forward with your analysis.

A small matrix.ec is fine (equivalence classes are created dynamically during the run of the program).
