### ISSUE TITLE
Error message when using genomebam

### ISSUE THREAD

**Issue by olgabaranov** [pachterlab/kallisto#406]
When compiling kallisto as descibed in https://pachterlab.github.io/kallisto/source and running the command with `--genomebam -g xxx.gtf` options, following error is shown (with no further details):
```
Error: in order to use BAM, must compile with BAM option enabled
```
It is resolved when changing the CMakeLists.txt at line 8 & 9 to ON. But it was not very apparent to me from the text of the error message. It might be worth including the detail into the documentation.

**Comment by Yenaled** [comment]
Thanks, however, we're actually no longer supporting genomebam from the current version (0.50.0) onwards because it's very hard to maintain. We understand the BAM files are a good way to visualize alignments and coverage over gene bodies, so we're looking into improved alternatives.
