### ISSUE TITLE
D-list Usage Question

### ISSUE THREAD

**Issue by yvazirabad** [pachterlab/kallisto#412]
Hello,

This is more of a usage guideline ask rather than any issue in Kallisto. Since the advent of the d-list option in Kallisto, I have been wondering if it should always be turned on when running either bulk or single-cell RNA-Seq, or if the d-list finds the most utility with scRNA-Seq and using it for bulk RNA-Seq is not very helpful. 

-Ibrahim Vazirabad

**Comment by Yenaled** [comment]
I would always turn it on.

It's not a question of bulk vs. single-cell; it's a question of "what's in your sequencing reads" (which, unfortunately, no one ever really knows).

So yeah, I would always turn it on (whether bulk or single-cell or something else) -- you never know how much of your sequencing reads is contaminated with genomic DNA or whether unspliced molecules were abundantly captured by the library prep.

**Comment by yvazirabad** [comment]
Thank you so much, my intuition was to always turn it on. I appreciate your quick response!

-Ibrahim
