### ISSUE TITLE
kallisto quant trying to allocate a huge amount of data

### ISSUE THREAD

**Issue by robert-player** [pachterlab/kallisto#414]
Hi, I'm running kallisto quant with about 3GB of paired end read data, against a mm10 transcriptome index.

Here is the log output from console:

```
[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 117,667
[index] number of k-mers: 103,067,506
[quant] running in paired-end mode
[quant] will process pair 1: r1.fastq
                             r2.fastq
[progress] 21M reads processed (91.3% mapped)              done
[quant] processed 22,389,489 reads, 20,440,492 reads pseudoaligned
[quant] estimated average fragment length: 181.6
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,192 rounds

/var/lib/cwl/stg78ec0a8f-13b2-4e07-b40f-828ce0856546/kallisto-index.kdx: xrealloc: cannot allocate 18446744072888123392 bytes
```

Any ideas what could cause this? I didn't see any `kallisto quant` params that could address allocation issues such as this.

Thanks!

**Comment by Yenaled** [comment]
Can you show the entire command / shell script you're running? 

kallisto itself seems to be running and completing perfectly fine. My suspicion is that there's something in your shell script that is problematic.

**Comment by robert-player** [comment]
This was indeed a system issue, thanks for the response and sorry for the bother!
