### ISSUE TITLE
Test index fails to build - on 32 bit system

### ISSUE THREAD

**Issue by nstjhp** [pachterlab/kallisto#42]
Attempted to follow the Gettting started instructions with the test datasets but got the following abortion:

```bash
[nick@laptop test] kallisto index -i transcripts.idx transcripts.fasta.gz 

[build] loading fasta file transcripts.fasta.gz
[build] k-mer length: 31
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done 
[build] creating equivalence classes ... kallisto: /home/nick/Documents/gitRepos/kallisto/src/KmerIndex.cpp:469: void KmerIndex::FixSplitContigs(const ProgramOptions&, std::vector<std::vector<TRInfo> >&): Assertion `search != kmap.end()' failed.
Aborted
```
I'm using v0.42.1 on Linux after making from the git repo .
Any other info I can provide to help?

**Comment by pmelsted** [comment]
I can't recreate this on either my mac or linux from the binary downloads. Just to be sure the md5sum for the transcripts is
5fe34c240221ac9ea04ecaea9bca6590  transcripts.fasta.gz

**Comment by nstjhp** [comment]
Indeed from both the binary downloads and github source

```
[nick@laptop test] md5sum transcripts.fasta.gz 
5fe34c240221ac9ea04ecaea9bca6590  transcripts.fasta.gz
```

I can't check if the binary works though due to 

```
[nick@laptop kallisto_linux-v0.42.1] ./kallisto 
bash: ./kallisto: cannot execute binary file: Exec format error
```

**Comment by pmelsted** [comment]
ok, it looks like kallisto v0.42 is in your path, whereas the downloaded binary run by ./kallisto doesn't run. The released binary is 64-bit binary, is your system 32-bit by any change, you can check uname -a or uname -m to be sure.

Also if you have a 32-bit version you would have to compile from the source, see http://pachterlab.github.io/kallisto/source.html

**Comment by nstjhp** [comment]
Oh it's definitely 32-bit so that would explain why the binary doesn't work. 

I did compile from source originally which is the version that aborted in my OP when trying to follow the Getting started test examples.

**Comment by pmelsted** [comment]
Great, let me know how it goes.

**Comment by nstjhp** [comment]
But the compiled version is the one that isn't working either. I made it from the github source. It seems to `make` OK but when I came to run it that is where I found the error in the OP.

**Comment by pmelsted** [comment]
I'll see if I can track down a 32-bit system and investigate. Thanks for reporting this.

**Comment by pimentel** [comment]
@pmelsted have we decided what we're going to do with 32-bit builds?

**Comment by pimentel** [comment]
We have decided that for now we will not support 32 bit installations.

I'm closing the issue for now, but will reopen it if we change our minds.

Thanks for reporting this issue.
