### ISSUE TITLE
Kallisto abundance accuracy with pseudogenes

### ISSUE THREAD

**Issue by andrewxue98** [pachterlab/kallisto#425]
Hi,

I was wondering if kallisto estimated abundance for pseudogenes is generally accurate? We are looking at high enrichment of a mitochondrial gene as well as its pseudogene; they have non-identical sequences but share 1025/1042 bases. Is it likely that the abundance of the pseudogene is largely misalignment of reads from the original gene? And if so is there a method in kallisto to compensate (e.g. discard non-unique alignments)?

Thanks in advance and please let me know if there's a better place to ask questions like this. 

Best,
Andrew

**Comment by Yenaled** [comment]
It's accurate from a mathematical/technical standpoint. It uses an EM algorithm to probabilistically divide up read counts among the non-unique alignments in the near-best way possible. Of course, if the reference genome is wrong or not optimally annotated, then there's nothing kallisto can do about it. Additionally, if two genes overlap a significant amount, there's no possible way to divide up the counts that will get you accurate abundance.

A lot of multimapping occurs and it is suboptimal to discard all instances of it. There are hacky ways to get kallisto to do so, but that's not really what kallisto was designed for; kallisto is a probabilistic algorithm hence the term probabilistic in the original paper.

So, if your reference genome annotation has overlapping genes (like pseudogenes), the best thing to do would be to fix up your annotation (such as removing those pseudogenes). The overlapping genes problem is not a kallisto issue, it's an upstream annotation issue.
