### ISSUE TITLE
I want to build an index with a geneses I have. Kallisto index errors out. 

### ISSUE THREAD

**Issue by lcamVz** [pachterlab/kallisto#438]
I am running kallisto index and I am getting an error what this could be:

 line 27: 1493676 Illegal instruction     (core dumped) kallisto index -i genes.99.idx genes.99.fasta

I want to take my genes from a metagenome to build the index to see if I can run metakallisto is the logic works or am I missing something.

**Comment by Yenaled** [comment]
Either your FASTA file is corrupted or you need to re-install kallisto (from source)

**Comment by lcamVz** [comment]
I reinstalled from source and added the flags and it worked.
