### ISSUE TITLE
Kallisto index for ribo-depleted RNAseq libraries

### ISSUE THREAD

**Issue by MartinezRuiz-Carlos** [pachterlab/kallisto#440]
Hi all, 

I am running Kallisto on bulk RNAseq data from ribo-depleted libraries. This means that my reads will include immature RNA with intronic reads. As such, I have assumed that the index should be generated using FASTAs of the transcripts including introns, if I run an index based on transcripts only (without introns), I get a substantial reduction in read assignment. 
Is this correct? I have seen this is the approach for single-nuclei data but could not find an equivalent for bulk ribo-depleted RNAseq data.

Many thanks!

**Comment by mschilli87** [comment]
I think if I was interested in quantifying pre-mRNAs, I would create a FASTA with all spliced isoforms *and* the unspliced one(s) and index that one. This way, exon-exon junction spanning reads/fragments will be attributed to the corresponding mature isoform(s), inron-overlapping ones to the precursos(s) and intra-exon hits will be distributed by the EM accordingly. Note that this still has shortcomings as splicing can happen co-transcriptionally, so the are various potential precursor-intermediates and generating/indexing them all will probably blow up fast.
Thus, if I only cared about the mature mRNAs (and/or lncRNAs etc), I'd simply count on the precursor reads ending up unassigned and/or not biasing the mature quantification significantly, as their expression should be much lower, generally.

Just my two cents, hope this helps.

**Comment by Yenaled** [comment]
^I agree with that and that FASTA with all spliced isoforms and unspliced ones is what kb-python does when using kb ref with the --workflow=nac option.

**Comment by Yenaled** [comment]
No, please see the updated documentation here:

https://www.biorxiv.org/content/10.1101/2023.11.21.568164v2.full.pdf

The command you want is:

`kb ref --workflow=nac -i index.idx -g t2g.txt -c1 cdna.txt -c2 nascent.txt -f1 cdna.fasta -f2 nascent.fasta genome.fasta genome.gtf
`

You supply genome.fasta and genome.gtf -- the rest are output files. The cdna.fasta outputted contains your "spliced" isoforms while the nascent.fasta outputted contains your "unspliced" isoforms.

**Comment by MartinezRuiz-Carlos** [comment]
Perfect, and I see I can then simply use kb count -x BULK with the nac index for the bulk data. Ok, this sorts it then, many thanks for the quick response!
