### ISSUE TITLE
Creating index for lrKallisto

### ISSUE THREAD

**Issue by ipatop** [pachterlab/kallisto#449]
Hi,

I got super excited to try the new lrKalisto! But I am having some issues to generate the index for it. As I see in the methods section of the paper the _k-mer_ length should be set to 63 instead of the previously used 31.

But when I run the following line:
`kallisto index -k 63 -t 10 -i mm39_lrKallisto Mus_musculus.GRCm39.dna_sm.chromosome.ALL.fa`

I get the following error:
`Error: invalid k-mer length 63, minimum is 3 and maximum is 31
kallisto 0.51.0
Builds a kallisto index`

Should I run this with 31?

Thanks in advance for your time,

Ines

**Comment by Yenaled** [comment]
You have to compile from source and set the MAX_KMER_SIZE=64 option in cmake

E.g.

`cmake .. -MAX_KMER_SIZE=64`

**Comment by ipatop** [comment]
Thanks a lot. Will run it now.

**Comment by ipatop** [comment]
Hi!

I deleted the build directory, created a new one and ran the line of code you recommended and  I encountered the following error:

```
cmake .. -MAX_KMER_SIZE=64
CMake Error: Unknown argument -MAX_KMER_SIZE=64
CMake Error: Run 'cmake --help' for all supported options.
```

I tried just in case running again only: `cmake .. ` and it works

Thanks in advance,

Ines

**Comment by Yenaled** [comment]
Sorry, I made a typo, it’s actually:

cmake .. -DMAX_KMER_SIZE=64

**Comment by bound-to-love** [comment]
Hello, thank you for your interest in trying out lr-kallisto! Sounds like it may be a compilation issue. Did you compile with cmake .. -DMAX_KMER_SIZE=64?

**Comment by ipatop** [comment]
Thanks! I tried using DMAX_KMER_SIZE=64 (instead of MAX_KMER_SIZE=64) and it worked! It just finished will try running the index option now. Thanks again

**Comment by hyeon9** [comment]
Hi,

I'm happy to see lr-Kallisto!!
I had also tried "cmake .. -DMAX_KMER_SIZE=64" to increase k-mer size but after that I faced a "segmentation error". I never see it before compilation.
When I employing the test FASTA file, I got same error.

I did it like this
"""
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=${my_conda} -DMAX_KMER_SIZE=64
make
make install
"""

Best,
Hyeongu

**Comment by Yenaled** [comment]
It sure. Does it work with 32 as the max kmer size? What operating system are you using? What test file are you using?

**Comment by hyeon9** [comment]
Hi,
Thank you for your quick response!

Yes, when I use 31 size, it works.
My OS is Rocky Linux 9.
I used this file "kallisto-0.51.0/test/transcripts.fasta.gz" as TEST.

**Comment by Yenaled** [comment]
Hmm, I don't know what the issue is. I've tried it on my machines and don't encounter a segfault. 

The only suggestion I have is to run your compilation as follows:

`cmake .. -DCMAKE_INSTALL_PREFIX:PATH=${my_conda} -DMAX_KMER_SIZE=64 -DCOMPILATION_ARCH=OFF -DENABLE_AVX2=OFF`

**Comment by ipatop** [comment]
Hi! Thanks again for the help. Now it runs but I am getting the following `Segmentation fault` error. I tried using only chromosome 10 to check if this was a memory problem but still had the same error.

I am using: 20 cores, 150G of memory, and gcc (GCC) 6.2.0

```
kallisto index -k 63 -t 20 -i mm39_lrKallisto ../Mus_musculus.GRCm39.dna_sm.chromosome.10.fa.gz

[build] loading fasta file ../Mus_musculus.GRCm39.dna_sm.chromosome.10.fa.gz
[build] k-mer length: 63
[build] warning: replaced 3375102 non-ACGUT characters in the input sequence
        with pseudorandom nucleotides
KmerStream::KmerStream(): Start computing k-mer cardinality estimations (1/2)
KmerStream::KmerStream(): Start computing k-mer cardinality estimations (1/2)
KmerStream::KmerStream(): Finished
CompactedDBG::build(): Estimated number of k-mers occurring at least once: 124304157
CompactedDBG::build(): Estimated number of minimizer occurring at least once: 30947986
CompactedDBG::filter(): Processed 130530800 k-mers in 1 reads
CompactedDBG::filter(): Found 124238271 unique k-mers
CompactedDBG::filter(): Number of blocks in Bloom filter is 849737
CompactedDBG::construct(): Extract approximate unitigs (1/2)
CompactedDBG::construct(): Extract approximate unitigs (2/2)
CompactedDBG::construct(): Closed all input files

CompactedDBG::construct(): Splitting unitigs (1/2)

CompactedDBG::construct(): Splitting unitigs (2/2)
make_kallisto_idx.sh: line 57:  6551 Segmentation fault kallisto index -k 63 -t $threads -i $idxname $fasta
end
~       
```

**Comment by Yenaled** [comment]
One more request: Can you try git cloning the repo again and starting from scratch?

Sometimes there might be errors if you run cmake with max k-mer size of 32 and then run it again with max k-mer size of 64.

If that doesn’t work, let me know and I’ll try to further diagnose.

**Comment by ipatop** [comment]
I am doing it now and will let you know how it goes

**Comment by ipatop** [comment]
It worked!! I am now going to use the index and will let you know how it goes. Thanks!

**Comment by hyeon9** [comment]
Hi Yenaled,

Thanks a lot, I also solved my issue !!
