### ISSUE TITLE
About k-mer size 

### ISSUE THREAD

**Issue by border-info-nt** [pachterlab/kallisto#455]
Hi!!

MAX_KMER_SIZE: The maximum k-mer size is set to 64, but can it be changed from default 31?"
If it is possible, please provide detailed instructions.

Thank you!!

**Comment by Yenaled** [comment]
See https://github.com/pachterlab/kallisto/issues/449

Basically, max kmer size is just a parameter you set when compiling from source and running cmake.

Then, when running kallisto index, you just set the -k option to be any number between 3 and 63.

**Comment by border-info-nt** [comment]
I saw 449 but could not solve it

kallisto index -i transcripts_index_kallisto -k 63 gencode.v46.transcripts.fa.gz

Error: invalid k-mer length 63, minimum is 3 and maximum is 31
Error: FASTA file not found gencode.v46.transcripts.fa.gz
kallisto 0.51.0
Builds a kallisto index

Usage: kallisto index [arguments] FASTA-files

Required argument:
-i, --index=STRING          Filename for the kallisto index to be constructed 

Optional argument:
-k, --kmer-size=INT         k-mer (odd) length (default: 31, max value: 31)
-t, --threads=INT           Number of threads to use (default: 1)
-d, --d-list=STRING         Path to a FASTA-file containing sequences to mask from quantification
    --make-unique           Replace repeated target names with unique names
    --aa                    Generate index from a FASTA-file containing amino acid sequences
    --distinguish           Generate index where sequences are distinguished by the sequence name
-T, --tmp=STRING            Temporary directory (default: tmp)
-m, --min-size=INT          Length of minimizers (default: automatically chosen)
-e, --ec-max-size=INT       Maximum number of targets in an equivalence class (default: no maximum)

**Comment by Yenaled** [comment]
`git clone https://github.com/pachterlab/kallisto
cd kallisto
mkdir build
cd build
cmake .. -DMAX_KMER_SIZE=64
make
./src/kallisto index -i transcripts_index_kallisto -k 63 /path/to/gencode.v46.transcripts.fa.gz `

**Comment by border-info-nt** [comment]
Sorry,I create the index file, but  I can't solve the problem.

[quant] fragment length distribution will be estimated from the data
CompactedDBG::CompactedDBG(): Length k of k-mers cannot exceed or be equal to 32
CompactedDBG::CompactedDBG(): Length g of minimizers cannot exceed or be equal to 32
[index] k-mer length: 223349088
CompactedDBG::find(): Graph is invalid and cannot be searched
Error: Corrupted index; unitig not found: GTTAACTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTATTTGCTGTCTCT?

**Comment by Yenaled** [comment]
You have to use the same kallisto binary when running kallisto quant or kallisto bus.

For example:

`./src/kallisto quant -i transcripts_index_kallisto ...
`
