### ISSUE TITLE
Using lr-kallisto for quantifying long-read bulk RNA-seq

### ISSUE THREAD

**Issue by alanlamsiu** [pachterlab/kallisto#456]
Hi kallisto team,

Could you point me to the documentation showing steps for running lr-kallisto for long-read bulk RNA-seq?

**Comment by bound-to-love** [comment]
See the —long options in the manual https://pachterlab.github.io/kallisto/manual . To run lr-kallisto on bulk reads use -x bulk —long. Note there is also a —long option for quant-tcc for quantifying at the transcript level. Also, note that you will need to build kallisto from source in a new directory with cmake -DMAX_KMER_SIZE=64 ..

**Comment by bound-to-love** [comment]
Hi, just wanted to add the note that kallisto index will need run with -k 63. Let me know if you run into any issues!

**Comment by alanlamsiu** [comment]
Hi @bound-to-love, thanks for the advice. I built kallisto 0.51.0 from source by setting DMAX_KMER_SIZE=64. When I checked the help manual of quant-tcc using command line, I got the following, 
```kallisto 0.51.0
Quantifies abundance from pre-computed transcript-compatibility counts

Usage: kallisto quant-tcc [arguments] transcript-compatibility-counts-file

Required arguments:
-o, --output-dir=STRING       Directory to write output to

Optional arguments:
-i, --index=STRING            Filename for the kallisto index to be used
                              (required if file with names of transcripts not supplied)
-T, --txnames=STRING          File with names of transcripts
                              (required if index file not supplied)
-e, --ec-file=FILE            File containing equivalence classes
                              (default: equivalence classes are taken from the index)
-f, --fragment-file=FILE      File containing fragment length distribution
                              (default: effective length normalization is not performed)
--long                        Use version of EM for long reads
-P, --platform.               [PacBio or ONT] used for sequencing
-l, --fragment-length=DOUBLE  Estimated average fragment length
-s, --sd=DOUBLE               Estimated standard deviation of fragment length
                              (note: -l, -s values only should be supplied when
                               effective length normalization needs to be performed
                               but --fragment-file is not specified)
-p, --priors                  Priors for the EM algorithm, either as raw counts or as
                              probabilities. Pseudocounts are added to raw reads to
                              prevent zero valued priors. Supplied in the same order
                              as the transcripts in the transcriptome
-t, --threads=INT             Number of threads to use (default: 1)
-g, --genemap                 File for mapping transcripts to genes
                              (required for obtaining gene-level abundances)
-G, --gtf=FILE                GTF file for transcriptome information
                              (can be used instead of --genemap for obtaining gene-level abundances)
-b, --bootstrap-samples=INT   Number of bootstrap samples (default: 0)
    --matrix-to-files         Reorganize matrix output into abundance tsv files
    --matrix-to-directories   Reorganize matrix output into abundance tsv files across multiple directories
    --seed=INT                Seed for the bootstrap sampling (default: 42)
    --plaintext               Output plaintext only, not HDF5
```
 which looks different than the one in https://pachterlab.github.io/kallisto/manual. I have both the index and fastq files. What would be the steps in order to generate the `transcript-compatibility-counts-file` required by quant-tcc?

**Comment by bound-to-love** [comment]
Hello, as described in the manual "The necessary files can all be generated from bustools count in bustools." So the commands would be kallisto bus, bustools sort, bustools correct (optional), bustools count, kallisto quant-tcc with all the necessary inputs/outputs.

**Comment by alanlamsiu** [comment]
Hi @bound-to-love, I learned the steps from a kallisto issue posted by another user and here are the steps.
```
kallisto bus -i index_file -o outdir --long -x bulk sample.fastq.gz
bustools sort -o outdir outdir/output.bus
bustools count -o outdir/out -g sample.gtf -e outdir/matrix.ec -t outdir/transcripts.txt outdir/output.bus
``` 

I notice that the `outdir/output.bus` file is not empty. The beginning few lines of `outdir/matrix.ec` shows below. And the `outdir/transcripts.txt` file shows a list of transcript IDs as in the transcriptome fasta file used for making the index.
```
0       188087
1       128482,133273
2       129500
3       128482
4       128482,129500,130163,133273
``` 

However, directory `outdir/out` is empty. Could you advice on this issue? And could you give an example on how to run the quant-tcc command as I don't seem to find one in the manual?

Thanks.

**Comment by icemduru** [comment]
> Hi @bound-to-love, I learned the steps from a kallisto issue posted by another user and here are the steps.
> 
> ```
> kallisto bus -i index_file -o outdir --long -x bulk sample.fastq.gz
> bustools sort -o outdir outdir/output.bus
> bustools count -o outdir/out -g sample.gtf -e outdir/matrix.ec -t outdir/transcripts.txt outdir/output.bus
> ```
> 
> I notice that the `outdir/output.bus` file is not empty. The beginning few lines of `outdir/matrix.ec` shows below. And the `outdir/transcripts.txt` file shows a list of transcript IDs as in the transcriptome fasta file used for making the index.
> 
> ```
> 0       188087
> 1       128482,133273
> 2       129500
> 3       128482
> 4       128482,129500,130163,133273
> ```
> 
> However, directory `outdir/out` is empty. Could you advice on this issue? And could you give an example on how to run the quant-tcc command as I don't seem to find one in the manual?
> 
> Thanks.

I have the same problem. I created genemap file using kb ref. A help would be appreciated.

**Comment by bound-to-love** [comment]
Hi! The error may be twofold. First, note according to the bustools manual `-g, --genemap         File for mapping transcripts to genes` whereas a gtf was supplied. kb ref can be used to generate the appropriate transcript to gene mapping. Second, bustools sort is being supplied a directory as the output file; I would suggest supplying outdir/sorted.bus and then bustools count should be given outdir/sorted.bus (the sorted bus file instead of the direct output of kallisto bus). Apologies for my delay in responding, but fixing these two errors should fix the issue. 

Finally, if you want to have transcript quantifications you can use 

` ${path_to_lr_kallisto} quant-tcc -t 32 \
 ${output}/count.mtx \
 -i ${ref}_k-63.idx \
 -f ${output}/flens.txt \
 -e ${output}/count.ec.txt \
 -o ${output};
`

**Comment by bound-to-love** [comment]
Hi, I just wanted to give a full example to, hopefully, clear up any remaining confusion. Note that the flags --cm and -m are used with bustools count to count multiplicity (since it is bulk) and include multimapping: 

```
${path_to_lr_kallisto} bus -t 32 --long --threshold 0.8 -x bulk -i ${ref}_k-63.idx -o ${output} ${reads}


${path_to_bustools} sort -t 32 ${output}/output.bus \
 -o ${output}/sorted.bus; \
 ${path_to_bustools} count ${output}/sorted.bus \
 -t ${output}/transcripts.txt \
 -e ${output}/matrix.ec \
 -o ${output}/count --cm -m \
 -g ${ref}.t2g; \

${path_to_lr_kallisto} quant-tcc -t 32 \
	--long -P ONT -f ${output}/flens.txt \
	${output}/count.mtx -i ${ref}_k-63.idx \
	-e ${output}/count.ec.txt \
	-o ${output}; 
```

Please let me know if you run into any more difficulties!

**Comment by bound-to-love** [comment]
You're welcome! Thanks for the feedback!

**Comment by sbresnahan** [comment]
Hi @bound-to-love - this issue thread was very helpful for learning how to use lr-kallisto for bulk lrRNAseq! I had to find this in the issues rather than the manual page though to figure it out. It would be great if it could be updated to more clearly demonstrate this use case as you have done here.

**Comment by AnnikaMueller05** [comment]
Hi @bound-to-love, thank you for the code as this has already helped a lot.
Somehow I am still running into issues though. I am using the kallisto linux long-read version (not installed from source code as i had some issues here).

**Here's my issue:** 
My matrix appears to be empty. I have realised that after sorting, the file size is significantly decreased, and suspect that everything else is a result of something going wrong when sorting. One example directory below
ll ${output}/M4.output.bus
total 5.3M
-rw-r--r-- 1 85K Mar 18 21:40 flens.txt
-rw-r--r-- 1 409K Mar 18 21:40 index.saved
drwxr-sr-x 2 4.0K Mar 18 19:18 KallistoQuantTCC
-rw-r--r-- 1 0 Mar 18 21:41 M4.count.barcodes.txt
-rw-r--r-- 1 105K Mar 18 21:41 M4.count.ec.txt
-rw-r--r-- 1 115 Mar 18 21:41 M4.count.mtx
**-rw-r--r-- 1 0 Mar 18 22:03 M4.sorted.bus**
-rw-r--r-- 1 7 Mar 18 21:40 matrix.cells
-rw-r--r-- 1 105K Mar 18 21:40 matrix.ec
-rw-r--r-- 1 17 Mar 18 21:40 matrix.sample.barcodes
-rw-r--r-- 1 0 Mar 18 21:40 novel.fastq
**-rw-r--r-- 1 3.1M Mar 18 21:40 output.bus**
-rw-r--r-- 1 701 Mar 18 21:40 run_info.json
-rw-r--r-- 1 200K Mar 18 21:40 transcripts.txt

**Input files:** fastq files appear to be okay, nothing corrupted. I have repeated the indexing, but the issue remains.

**Output files:**
Here's part of the flens.txt - seems fine to me:
510 1506 1485 489 981 354 273 273 264 423 873 453 1500 2163 1005 849 711 300 744 432 246 867 816 591 1296 585 654 825 315 1440 1479 294 309 1680 891 1128 492 336 1512 2763 1461 315 426 321 648 300 294 564 474 465 363 474 270 1782 576 303 684 264 468 705 270 1929 3921 825 501 1032 396 807 684 303 1134 666 537 429 1008 753 708 657 354 315 381 1053 264 1419 1344 1467 657 246 1425 441 435 411 312 879 570 342 843

Parts of the output.bus file:
00000000: 4255 5300 0100 0000 1000 0000 0100 0000  BUS.............
00000010: 1d00 0000 4255 5320 6669 6c65 2070 726f  ....BUS file pro
00000020: 6475 6365 6420 6279 206b 616c 6c69 7374  duced by kallist
00000030: 6f00 0000 0000 0000 00ff ffff ffff ffff  o...............
00000040: ff00 0000 0001 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 00ff ffff ffff ffff  ................
00000060: ff01 0000 0001 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 00ff ffff ffff ffff  ................
00000080: ff01 0000 0001 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 00ff ffff ffff ffff  ................
000000a0: ff01 0000 0001 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 00ff ffff ffff ffff  ................

Parts of the sorted output.bus file:
xxd -c 16 -g 1 ${output}/M4.output.bus/M4.sorted.bus | head -5
00000000: 42 55 53 00 01 00 00 00 10 00 00 00 01 00 00 00  BUS.............
00000010: 1d 00 00 00 42 55 53 20 66 69 6c 65 20 70 72 6f  ....BUS file pro
00000020: 64 75 63 65 64 20 62 79 20 6b 61 6c 6c 69 73 74  duced by kallist
00000030: 6f 00 00 00 00 00 00 00 00 ff ff ff ff ff ff ff  o...............
00000040: ff 00 00 00 00 03 00 00 00 00 00 00 00 00 00 00  ................

Comparison of the two of them:
xxd -c 16 -g 1 ${output}/M4.output.bus/M4.sorted.bus | wc -l                   **20440**
(AnnikaIsoSeq)[mueannik@login23 NovoGeneData]$ xxd -c 16 -g 1 ${output}/M4.output.bus/output.bus | wc -l
**200794**

I have tried sorting a **subset** instead, but the subset doesn't work either:
head -n 1000 ${output}/M4.output.bus/output.bus > test.bus
bustools sort -t 32 -o test.sorted.bus test.bus
         all fits in buffer
         Read in 27279 BUS records
         reading time 0.000402s
         sorting time 0.001293s
         writing time 0.000351s
xxd -c 16 -g 1 test.sorted.bus | wc -l      **5360**
xxd -c 16 -g 1 test.bus | wc -l                 **54563**

The **bustools inspect** command showed the following:
{
        "numRecords": 100395,
        "numReads": 100395,
        "numBarcodes": 1,
        "medianReadsPerBarcode": 0.000000,
        "meanReadsPerBarcode": 100395.000000,
        "numUMIs": 1,
        "numBarcodeUMIs": 1,
        "medianUMIsPerBarcode": 0.000000,
        "meanUMIsPerBarcode": 1.000000,
        "gtRecords": 100395
}

The equivalence class is empty. The count matrix is empty as well.
cat ${output}/M4.output.bus/M4.count.mtx
%%MatrixMarket matrix coordinate real general
%
0 0 0

**Here's my script:**

# Indexing
$kallisto index $ref --index=${ref}_k-63.idx -t 32 -k 63 #k63 is needed for long reads

# Converting the bam files from the isoseq pipeline to fastq files for mapping
samtools bam2fq ${aligned}/Afra_${1}.alignedIsoseq.bam > ${aligned}/${1}.fastq

# Here the pipeline as described by you (above) starts
$kallisto bus -t 32 --threshold 0.8 -i ${ref}_k-63.idx \
         -o ${output}/${1}.output.bus --long -x bulk ${aligned}/${1}.fastq #supply the respective fastq file when running the script

$bustools sort -t 32 ${output}/${1}.output.bus \
         -o ${output1}/${1}.sorted.bus

$bustools count ${output1}/${1}.sorted.bus \
        -t ${output1}/transcripts.txt \
        -e ${output1}/matrix.ec \
        -o ${output1}/${1}.count --cm -m \
        -g ${ref_g}.t2g #transcript2gene

Any help would be greatly appreciated

**Comment by bound-to-love** [comment]
From what you have posted above, it looks like your file paths in bustools sort and bustools count may be incorrect: 

Instead of:
bustools sort -t 32 /path/to/output/sampleName.output.bus -o /path/to/output/sampleName.sorted.bus

bustools count /path/to/output/sampleName.sorted.bus -t /path/to/output/sampleName.transcripts.txt -e /path/to/output/matrix.ec
-o /path/to/output/sampleName.count --cm -m -g /path/to/ref.t2g #268 

should it be:
bustools sort -t 32 /path/to/output/sampleName.output.bus/output.bus -o /path/to/output/sampleName.output.bus/sampleName.sorted.bus

bustools count /path/to/output/sampleName.output.bus/sampleName.sorted.bus -t /path/to/output/sampleName.output.bus/transcripts.txt -e /path/to/output/sampleName.output.bus/matrix.ec
-o /path/to/output/sampleName.output.bus/sampleName.count --cm -m -g /path/to/ref.t2g #268 
?

**Comment by AnnikaMueller05** [comment]
Yes, you are correct. They are correct in my script though, I just edited them incorrectly here. I am usually not posting on github and it does funny things when i leave the dollar signs in for the variable names which is why i changed the variable names here.
Here's the original but the font is weird for variable names:

output1=output/S.output.bus

kallisto bus -t 32 --threshold 0.8 -i ${ref}_k-63.idx -o ${output}/${1}.output.bus --long -x bulk ${aligned}/${1}.fastq #supply the respective fastq file when running the script

bustools sort -t 32 ${output}/${1}.output.bus \
                -o ${output1}/${1}.sorted.bus
$bustools count ${output1}/${1}.sorted.bus \
               -t ${output1}/transcripts.txt \
               -e ${output1}/matrix.ec \
               -o ${output1}/${1}.count --cm -m \
               -g ${ref_g}.t2g #transcript2gene

I run this via 
for k in ${individuals[@]}; do sbatch Script.sh $k; done

And somehow the next step only runs via the command line and not in the script, so i run this manually afterwards:
for k in ${individuals[@]}; do $kallisto quant-tcc -t 32 --long -P PacBio -f ${output}/${k}.output.bus/flens.txt ${output}/${k}.output.bus/${k}.count.mtx -i ${ref}_k-63.idx -e ${output}/${k}.output.bus/${k}.count.ec.txt --matrix-to-directories -b 100 -o ${output}/${k}.output.bus/KallistoQuantTCC; done

**Comment by AnnikaMueller05** [comment]
ah wait, i may be an idiot. let me check

**Comment by bound-to-love** [comment]
bustools sort should be:

bustools sort -t 32 ${output}/${1}.output.bus/output.bus
-o ${output1}/${1}.sorted.bus

Hope this fixes it!

**Comment by AnnikaMueller05** [comment]
Yes, you are absolutely right, I didn't catch that. You are a life saver, I spent so much time staring at this script and didn't see it! 

The matrix isn't empty any more - the line number is still much lower for the sorted one though. Is that normal/okay? I would have thought the lines should be the same, just sorted in a different order, no?

xxd -c 16 -g 1 /RNASeq_Data/NovoGene/lk-kallisto/M4.output.bus/output.bus | wc -l
200794
xxd -c 16 -g 1 /RNASeq_Data/NovoGene/lk-kallisto/M4.output.bus/M4.sorted.bus | wc -l
20440

ls -lh /RNASeq_Data/NovoGene/lk-kallisto/M4.output.bus
total 5.9M
-rw-r--r-- 1 85K Mar 18 23:55 flens.txt
-rw-r--r-- 1 409K Mar 18 23:55 index.saved
drwxr-sr-x 2 4.0K Mar 18 19:18 KallistoQuantTCC
-rw-r--r-- 1 17 Mar 18 23:55 M4.count.barcodes.txt
-rw-r--r-- 1 105K Mar 18 23:55 M4.count.ec.txt
-rw-r--r-- 1 93K Mar 18 23:55 M4.count.mtx
-rw-r--r-- 1 320K Mar 18 23:55 M4.sorted.bus
-rw-r--r-- 1 7 Mar 18 23:55 matrix.cells
-rw-r--r-- 1 105K Mar 18 23:55 matrix.ec
-rw-r--r-- 1 17 Mar 18 23:55 matrix.sample.barcodes
-rw-r--r-- 1 0 Mar 18 23:54 novel.fastq
-rw-r--r-- 1 3.1M Mar 18 23:55 output.bus
-rw-r--r-- 1 701 Mar 18 23:55 run_info.json
-rw-r--r-- 1 200K Mar 18 23:55 transcripts.txt

**Comment by bound-to-love** [comment]
I've messed up file paths enough times that it's one of my go-tos for debugging, haha. When you use bustools sort, records of the same equivalence class get collapsed together, so you would expect fewer lines. :)

**Comment by mschilli87** [comment]
@AnnikaMueller05:
> I am usually not posting on github and it does funny things when i leave the dollar signs in for the variable names which is why i changed the variable names here.

Try wrapping your code/output in between two lines containing three backtick characters (`` ``` ``) only:

````
```
<your code here>
```
````
This will flag them as code blocks and not mess up your formatting.

See the [GitHub docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) for more information.
