### ISSUE TITLE
lr-kallisto not producing hdf5 files for bulk long-read RNA seq data

### ISSUE THREAD

**Issue by apsteinberg** [pachterlab/kallisto#457]
Hello there,

I am very excited to start using kallisto with some of our bulk, long-read RNA seq data. For the analysis I am conducting, I wanted to use kallisto to quantify read counts, and then use sleuth for downstream statistical analysis. However, when I follow the workflow described [here](https://github.com/pachterlab/LSRRSRLFKOTWMWMP_2024/blob/main/Figures/Figure1/run_lr_kallisto_b01.sh) and use the `-b 100` flag with `kallisto quant-tcc`, no `abundance.h5` file is produced. When I look at the output log, which I have attached here (I ran this within a snakemake pipeline):
[kallisto_logs.zip](https://github.com/user-attachments/files/16784898/kallisto_logs.zip)
It seems to suggest an HDF5 file with bootstrap replicates should be produced (see line 27 of the attached log file and below):

```
[index] k-mer length: 63
[index] number of targets: 237,664
[index] number of k-mers: 149,478,581
[index] number of equivalence classes loaded from file: 286,611
[tcc] Parsing transcript-compatibility counts (TCC) file as a matrix file
[tcc] Matrix dimensions: 1 x 286,611
[tcc] Bootstrapping will be performed and outputted as HDF5
[quant] Running EM algorithm...
[quant] Processing sample/cell 0
 done
```

The outputs I do see are as follows, and I don't know if perhaps I am confused and one of these is the HDF5 file I can use with sleuth?

```
-rw-rw-r-- 1 preskaa preskaa 347K Aug 28 10:12 matrix.abundance.gene.mtx
-rw-rw-r-- 1 preskaa preskaa 466K Aug 28 10:12 matrix.abundance.gene.tpm.mtx
-rw-rw-r-- 1 preskaa preskaa 1.3M Aug 28 10:12 matrix.abundance.mtx
-rw-rw-r-- 1 preskaa preskaa 1.5M Aug 28 10:12 matrix.abundance.tpm.mtx
-rw-rw-r-- 1 preskaa preskaa 883K Aug 28 10:12 matrix.efflens.mtx
-rw-rw-r-- 1 preskaa preskaa    6 Aug 28 10:12 matrix.fld.tsv
-rw-rw-r-- 1 preskaa preskaa 5.1M Aug 28 10:12 transcript_lengths.txt
-rw-rw-r-- 1 preskaa preskaa 4.1M Aug 28 10:11 transcripts.txt
```

Thanks in advance for your time and help.

Best,
Asher

**Comment by bound-to-love** [comment]
Hi, Asher, are you including `--matrix-to-files` in your quant-tcc command?

**Comment by apsteinberg** [comment]
Hi Rebekah,

Thanks for getting back to me! I did end up adding that option in the end and it worked. Very excited to start playing around with the results. If I may suggest, it could be useful to detail this in the description of this flag or in the manual. I ended up figuring it out by going through the old release notes on github.

Cheers,
Asher

**Comment by bound-to-love** [comment]
Let me know if you have any other questions! Thanks for the feedback, Asher!

**Comment by MustafaElshani** [comment]
Hi All
I have tried including `--matrix-to-files` but  on the out puts I do not get the `.h5` files 
Docs say 
`--matrix-to-files         Reorganize matrix output into abundance tsv files` 
Does that mean I need not include it to get h5?
Current usage
```
kallisto quant-tcc --long -P ONT -t "$SLURM_CPUS_PER_TASK" \
    -f "$OUTPUT_DIR/$SAMPLE_NAME/flens.txt" \
    -i "$INDEX_PATH" \
    -e "$OUTPUT_DIR/$SAMPLE_NAME/count.ec.txt" \
    -o "$OUTPUT_DIR/$SAMPLE_NAME" \
    --matrix-to-files \
    "$OUTPUT_DIR/$SAMPLE_NAME/count.mtx"
```

Any help appreciated

**Comment by MustafaElshani** [comment]
It looks like it needed `cmake  ..  -DUSE_HDF5=ON `
