### ISSUE TITLE
Does kallisto bus in single cell mode (-x with anything not "bulk") turn off long read mode?

### ISSUE THREAD

**Issue by raysinensis** [pachterlab/kallisto#458]
Greetings, I am trying to run lr-kallisto on single cell ONT data. The lr-kallisto preprint suggests that it should work when coupled with upstream custom barcode discovery.

After custom code to get barcode, UMI, and sequences trimmed of adaptors, I make a new fastq that is 16nt barcode + 12nt UMI + seq. However, when I specify this into "-x" for `kallisto bus`, I notice the log does not contain the line "[quant] running in long read mode", which I get in "-x bulk". Does this mean long read mode was actually not enabled here?

I tried making the fastqs in mock 10xv3 style (paired) as well, but that also did not trigger the line "[quant] running in long read mode".

Full command was:
```
kallisto bus \
  --long --threshold 0.8 -x 0,0,16:0,16,28:0,28,0 --unstranded \
  -i kallisto_long.idx \
  -o out \
  -t 10 \
  tagged.fastq
```

I'm using kallisto_version: "0.51.0", made with `-DMAX_KMER_SIZE=64`, and index `-k 63`.

I can run all downstream steps of `bustools sort`, `bustools count`, `kallisto quant-tcc` from the output bus file, but of course if the first step didn't use new modifications for long read, then all output is just nonsense.

Thanks in advance!

**Comment by bound-to-love** [comment]
Hi, thanks for the question! Is flens.txt being produced in the output directory? I've identified the source of the difference in output and the modifications for long read will still be in place even though the write out differs.

**Comment by raysinensis** [comment]
Yes, flens.txt is there in the output. Is that the indictor long read mode is working fine?

**Comment by bound-to-love** [comment]
It's an indicator that the long read mode was properly set and will be run in pseudoalignment. :)

**Comment by raysinensis** [comment]
Great to hear, thank you.
