### ISSUE TITLE
Mapping multiple runs to genomes - inconsistent results !!!

### ISSUE THREAD

**Issue by dgiovannelli** [pachterlab/kallisto#466]
Hi all,

first of all thanks for the Kallisto and Sleuth tools. I've used them for microbial transcriptomic several times and they are great. I am now attempting to use Kallisto per read mapping in metagenomes.

Basically I have several reconstructed genomes and several paired-end runs from environemntal samples.

I have combined the multiple MAGs in a single index
`kallisto index -i Bin.database Bin.001.binning.assembly.fasta Bin.002.binning.assembly.fasta Bin.003.binning.assembly.fasta`

and I have attempted to run Kallisto with the multiple sample runs like this:

`kallisto quant -i Bin.database -o output sample1_R1.fastq.gz sample1_R2.fastq.gz sample2_R1.fastq.gz sample2_R2.fastq.gz sampleN_R1.fastq.gz sampleN_R2.fastq.gz`

Kallisto seems to run well:

```quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 372
[index] number of k-mers: 6,681,661
[quant] running in paired-end mode
[quant] will process pair 1:sample1_R1.fastq.gz
                             sample1_R2.fastq.gz
[quant] will process pair 2: sample2_R1.fastq.gz
                             sample2_R2.fastq.gz
[quant] will process pair 3: sample3_R1.fastq.gz
                             sample3_R2.fastq.gz
[progress] 3M reads processed (2.2% mapped)              done
[quant] processed 3,423,908 reads, 75,894 reads pseudoaligned
[quant] estimated average fragment length: 8.0
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 52 rounds
```

However when I inspect the output I see the contigs of the multiple genomes, but only one set of quantified reads, and the counts are  identical if I run only the first pair of reads like this:

`kallisto quant -i Bin.database -o output2 sample1_R1.fastq.gz sample1_R2.fastq.gz`

<!DOCTYPE html>

<html>

<body>

target_id | length | eff_length | est_counts | tpm |  
-- | -- | -- | -- | -- | --
NODE_102_length_23682_cov_8.732679 | 23682 | 23675 | 2602 | 19262.9 |  
NODE_1043_length_4636_cov_8.135560 | 4636 | 4629 | 462 | 17492.8 |  
NODE_1077_length_4488_cov_7.219039 | 4488 | 4481 | 452 | 17679.4 |  
NODE_1087_length_4443_cov_9.138560 | 4443 | 4436 | 526 | 20782.5 |  
NODE_1098_length_4399_cov_7.111188 | 4399 | 4392 | 420 | 16760.6 |  
NODE_1103_length_4347_cov_11.190587 | 4347 | 4340 | 758 | 30611.4 |  
NODE_1165_length_4114_cov_7.823602 | 4114 | 4107 | 402 | 17155.6 |  
NODE_1190_length_4037_cov_7.139126 | 4037 | 4030 | 420 | 18266.2 |  
NODE_126_length_21081_cov_8.506611 | 21081 | 21074 | 2285.02 | 19004.1 |  
NODE_1307_length_3709_cov_11.157909 | 3709 | 3702 | 592 | 28027.8 |  
NODE_1387_length_3534_cov_7.369359 | 3534 | 3527 | 353.107 | 17547.1 |  
NODE_138_length_20529_cov_7.944368 | 20529 | 20522 | 2008 | 17149.4 |  
NODE_144_length_20182_cov_8.025538 | 20182 | 20175 | 2092.98 | 18182.6 |  
NODE_1481_length_3333_cov_6.913057 | 3333 | 3326 | 324 | 17073.7 |  
NODE_1483_length_3329_cov_9.169823 | 3329 | 3322 | 402 | 21209.5 |  
NODE_1523_length_3243_cov_8.740276 | 3243 | 3236 | 344 | 18631.7 |  
NODE_1534_length_3231_cov_8.293766 | 3231 | 3224 | 392 | 21310.6 |  
NODE_1677_length_2989_cov_6.786299 | 2989 | 2982 | 278 | 16339.6 |  

</body>

</html>

I noticed that inverting the order of the sample pair, the result do not change, and adding more samples (or doubling the number of mapped reads by douybling the read pair using copies different names does not change the total mapped reads either. Like if Kallisto is processing everything but still recording the results only of one pair of reads instead of visualizing all the results. all the test where done using --plaintext output.

While making the test, I have splited my sequencing runs artificially, and I have mappend the splitted files individually. the results are inconsistent (first 4 lines of the 3 test are presented):

The full fastq file:
<!DOCTYPE html>

<html>

<body>

target_id | length | eff_length | est_counts | tpm
-- | -- | -- | -- | --
NODE_102_length_23682_cov_8.732679 | 23682 | 23675 | 2602 | 19262.9
NODE_1043_length_4636_cov_8.135560 | 4636 | 4629 | 462 | 17492.8
NODE_1077_length_4488_cov_7.219039 | 4488 | 4481 | 452 | 17679.4
NODE_1087_length_4443_cov_9.138560 | 4443 | 4436 | 526 | 20782.5

</body>

</html>

Portion 1 of the file:
<!DOCTYPE html>

<html>

<body>

target_id | length | eff_length | est_counts | tpm
-- | -- | -- | -- | --
NODE_102_length_23682_cov_8.732679 | 23682 | 23683 | 733 | 18567.5
NODE_1043_length_4636_cov_8.135560 | 4636 | 4637 | 130 | 16818.7
NODE_1077_length_4488_cov_7.219039 | 4488 | 4489 | 132 | 17640.5
NODE_1087_length_4443_cov_9.138560 | 4443 | 4444 | 163 | 22003.9

</body>

</html>

Portion 2 of the file:
<!DOCTYPE html>

<html>

<body>

target_id | length | eff_length | est_counts | tpm
-- | -- | -- | -- | --
NODE_102_length_23682_cov_8.732679 | 23682 | 23675 | 568 | 20267.8
NODE_1043_length_4636_cov_8.135560 | 4636 | 4629 | 101 | 18432.4
NODE_1077_length_4488_cov_7.219039 | 4488 | 4481 | 94 | 17721.5
NODE_1087_length_4443_cov_9.138560 | 4443 | 4436 | 100 | 19043.9

</body>

</html>

 

Three questions:
1. How can the files with a lower est_count have a higher TPM? Why is TPM not proportional to the est_counts? Am I missing something?
2. Is there a why to run multiple pairs of samples and get the result tabulated together? Like a contig x sample table or something similar? Or do I have to run through the pairs using a for loop and then merging the different results?
4. Is there a way to get the sum of the results (TPM and est counts) by genome provided instead that by contigs?

Thank you very much for your help!

Don

**Comment by Yenaled** [comment]
1. TPM is scaled so that the sum of all TPMs in a file equals 1000000.
2. You have to use multiple for loops.
3. You would have to provide a genome FASTA rather than a contig FASTA, but rather than do that, I would just manually take the sum across contigs.

**Comment by dgiovannelli** [comment]
thank you! Yes, I'll loop through the different runs. You are right on the TPM, not sure why I did not think of it. So rather than TPM is probably better to record the est_counts directly and then deal with normalization later right? I'll do the sum for the rest.
Best and thank you!
D

**Comment by Yenaled** [comment]
Yes, I'd use the est_counts and save the normalization for later.
