### ISSUE TITLE
Read interleaved paired-end FASTQ files

### ISSUE THREAD

**Issue by sjackman** [pachterlab/kallisto#47]
The output of `sam bam2fq` of an unaligned BAM file is an interleaved paired-end FASTQ file. It would be useful to be able to read this format.

**Comment by pmelsted** [comment]
It is unfortunate that `sam bam2fq` returns interleaved files, but this is a problem better solved with scripts, e.g. https://gist.github.com/nathanhaigh/3521724

Also you can most likely specify the output to be process substitution using `mkfifo` and use with kallisto.

**Comment by ttriche** [comment]
bam2fastq will do this properly

e.g.

bam2fastq -o bamName.#.fastq bamName.hg19.bam

which will produce bamName.R_1.fa and bamName.R_2.fa

It would be nice if Kallisto could use htslib to extract these sorts of
things but as Pall noted, it's up to the aligner what ends up in the BAM,
and how.


Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

**Comment by skurscheid** [comment]
Sorry for chipping in:

It is also not very UNIX-like to cram functions into code for which already well working stand-alone solutions exist. That's what the pipe is for.

**Comment by sjackman** [comment]
Fair enough. Here's my shell snippet:
```
samtools view -uf64 x.bam |samtools bam2fq - |gzip >x_1.fq.gz
samtools view -uf128 x.bam |samtools bam2fq - |gzip >x_2.fq.gz
```

**Comment by ttriche** [comment]
So if you're going to do that, you might as well just use FIFOs and save a little space:

```
mkfifo x_R1 && samtools view -uf64 x.bam |samtools bam2fq - > x_R1 & 
mkfifo x_R2 && samtools view -uf128 x.bam |samtools bam2fq - > x_R2 & 
mkdir x_quant && kallisto quant -i indexedTxome.fa.idx -o x_quant x_R1 x_R2 
```

which will feed Kallisto directly from the extraction of the BAM files.

**Comment by sjackman** [comment]
Thanks, Tim.
