### ISSUE TITLE
Error: Fragment length distribution file contains 96 valid lines; expected: 88

### ISSUE THREAD

**Issue by Yuanqingq** [pachterlab/kallisto#471]
Hi！I met an error  when I use `kb count --tcc` to generate a transcript count matrix from paired-end SMARTSEQ data. I had 96 samples, but during processing, perhaps because some samples were of poor quality, only 88 samples were included in the result and got the error massage `Error: Fragment length distribution file contains 96 valid lines; expected: 88`.

My code
```shell
kb count --tcc -i index.idx \
 -g t2g.txt \
 -x SMARTSEQ2 --verbose \
 --parity paired \
 --strand unstranded \
 -t 24 \
 -o ./kb_genecount \
 batch.txt
``` 
The error message
```shell
[2024-12-17 18:03:10,161]   DEBUG [count] kallisto quant-tcc -o ./kb_genecount/quant_unfiltered -i index.idx -e ./kb_genecount/counts_unfiltered/cells_x_tcc.ec.txt -g t2g.txt -t 24 -f ./kb_genecount/flens.txt ./kb_genecount/counts_unfiltered/cells_x_tcc.mtx
[2024-12-17 18:03:10,478]   DEBUG [count]
[2024-12-17 18:05:44,278]   DEBUG [count] [index] k-mer length: 31
[2024-12-17 18:08:07,506]   DEBUG [count] [index] number of targets: 240,675
[2024-12-17 18:08:07,817]   DEBUG [count] [index] number of k-mers: 297,485,011
[2024-12-17 18:08:07,817]   DEBUG [count] [index] number of D-list k-mers: 6,330,163
[2024-12-17 18:08:32,016]   DEBUG [count] [index] number of equivalence classes loaded from file: 228,234
[2024-12-17 18:08:32,038]   DEBUG [count] [index] not using the D-list k-mers
[2024-12-17 18:08:32,245]   DEBUG [count] [tcc] Parsing transcript-compatibility counts (TCC) file as a matrix file
[2024-12-17 18:08:32,245]   DEBUG [count] [tcc] Matrix dimensions: 88 x 228,234
[2024-12-17 18:08:37,732]   DEBUG [count] Error: Fragment length distribution file contains 96 valid lines; expected: 88
[2024-12-17 18:08:42,935]   ERROR [count]
[index] k-mer length: 31
[index] number of targets: 240,675
[index] number of k-mers: 297,485,011
[index] number of D-list k-mers: 6,330,163
[index] number of equivalence classes loaded from file: 228,234
[index] not using the D-list k-mers
[tcc] Parsing transcript-compatibility counts (TCC) file as a matrix file
[tcc] Matrix dimensions: 88 x 228,234
Error: Fragment length distribution file contains 96 valid lines; expected: 88
[2024-12-17 18:08:42,936]   ERROR [main] An exception occurred
```
 I want to know if every line in `cells_x_tcc.barcodes.txt` corresponds one-to-one to every line in `flens.txt`, because I filtered the flens.txt file to 88 lines with the python pipeline below.

```python
def read_file(file_path):
    with open(file_path, 'r') as file:
        return [line.strip() for line in file]

cell_name1 = read_file('kb_genecount/matrix.cells')
cell_name2 = read_file('kb_genecount/matrix.sample.barcodes')
cell_name_map = dict(zip(cell_name2, cell_name1))

#get the filtered barcode list
filtered_barcodes = read_file('kb_genecount/counts_unfiltered/cells_x_tcc.barcodes.txt')

# filters entries corresponding to filtered_barcodes in cell_name1
filtered_cell_names = [cell_name_map[barcode] for barcode in filtered_barcodes if barcode in cell_name_map]

file4 = read_file('kb_genecount/flens.txt')

# create a mapping between cell_name1 and file4
cell_name_to_file4_map = dict(zip(cell_name1, file4))

filtered_file4_lines = [cell_name_to_file4_map[cell_name] for cell_name in filtered_cell_names if cell_name in cell_name_to_file4_map]

# output 
with open('kb_genecount/flens_filtered.txt', 'w') as output_file:
    for line in filtered_file4_lines:
        output_file.write(line + '\n')
``` 
And then I ran the last command like this and used the output for downstram analysis. Is it reasonable? Thank you!

```shell
kallisto  quant-tcc -f ./kb_genecount/flens_filtered.txt \
  -o ./kb_genecount/quant_unfiltered -i index.idx \
  -e ./kb_genecount/counts_unfiltered/cells_x_tcc.ec.txt -g t2g.txt \
  -t 24 ./kb_genecount/counts_unfiltered/cells_x_tcc.mtx
```

Also I have another question. When I deal with the single-end SMARTSEQ data, `kb count --tcc` requires me to provide `--fragment-l` and `--fragment-s`, but my data is from public database. Can you give some advice about this? Thank you very much!

**Comment by Yenaled** [comment]
Each of the 96 samples should correspond one-to-one to each of the 96 fragment length lines, in the order that the samples were provided.

You seem to be missing 8 samples which means that none of the reads from those samples mapped to your index. The fragment length lines for those 8 samples should look abnormal (maybe it’s all zeroes).

For single end reads, just supply 200 and 20 for those two options, respectively. It doesn’t really make a big difference. You can even do that for paired end if you’d like. Generally speaking, fragment length parameters don’t make a big difference in quantification. It’s basically a minor adjustment for transcript length.

**Comment by Yuanqingq** [comment]
Thank you very much for your reply! I'll take your advice. The paired-end data will be processed as I said above, and the single-end data will be processed  with `--fragment-l 200 --fragment-s 20`.
