### ISSUE TITLE
Please rename abundance.txt to abundance.tsv

### ISSUE THREAD

**Issue by sjackman** [pachterlab/kallisto#48]
TSV is the standard file extension for a tab-separated-values table. Having the correct file extension enables pretty rendering in GitHub.
See https://help.github.com/articles/rendering-csv-and-tsv-data/

**Comment by pimentel** [comment]
We'll do this for the next release.

Thanks

**Comment by sjackman** [comment]
Great. Thanks, Harold.

**Comment by pimentel** [comment]
Added to latest devel (4cbe76b75eae5984c22ac6ed82dbb188af7faed1), going into next release
