### ISSUE TITLE
Homebrew installation failure due to SHA mismatch

### ISSUE THREAD

**Issue by jdidion** [pachterlab/kallisto#56]
==> Installing kallisto from homebrew/homebrew-science
==> Downloading https://github.com/pachterlab/kallisto/archive/v0.42.2.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 85b89b840dae06c56f59b6ad98b7832ff965df5d259975bc19244584cf918fbf
Actual: 6107fed6089c4c4e8a3f8d16c2539736321c134b518c95600ae93ddd3d699219

**Comment by pimentel** [comment]
We actually don't maintain the homebrew installation. We fixed some bugs that were reported on our google group and updated the release so my guess is that they didn't notice and that is the old SHA sum.

Could you please open a report at https://github.com/Homebrew/homebrew-science ?

Thanks!

Harold
