### ISSUE TITLE
quant: unrecognized option '--pseudobam'

### ISSUE THREAD

**Issue by moldach** [pachterlab/kallisto#66]
It is my understanding that we should only supply one sample at a time to kallisto; therefore I ran the following command on one of my 48 Single-end FASTQ files. However, I'm getting a strange error.
 
Although 'quant' does produce three output files (abundance.h5, abundances.tsv, run_info.jso), I cannot understand why the --pseudobam command is not recognized (or executed) and why there is no SAM format output?
Hoping someone can help!
 ![troubleshoot](https://cloud.githubusercontent.com/assets/5749465/9045271/2be75880-39df-11e5-9eac-d0a6ad088289.jpg)

**Comment by moldach** [comment]
Noticed that my code got cutoff in the above image, the complete code was:

/data2/kallisto_linux-v0.42.1/kallisto quant -i transcripts.idx -o H1D1Q --single -l 180 --pseudobam H1D1Q.fq.trim.gz > H1D1Q.sam

**Comment by ttriche** [comment]
pseudobam output didn't go into kallisto until 0.42.2

so the error message is being truthful with you :-)

best,
--t

Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

**Comment by moldach** [comment]
thanks ttriche!
