### ISSUE TITLE
Linux binaries are missing from download page

### ISSUE THREAD

**Issue by jayhesselberth** [pachterlab/kallisto#68]
This returns 404:

https://github.com/pachterlab/kallisto/releases/download/v0.42.2.1/kallisto_linux-v0.42.2.1.tar.gz

Mac and source versions are fine

**Comment by lucapinello** [comment]
Yes still broken. Any update?

**Comment by pimentel** [comment]
Hey folks,

Sorry for the delay. We've unsuccessfully built a static binary for these versions that is fairly portable. The biggest problem is pthreads. We're currently working on a tutorial for building locally on Linux.

If you'd like guidance on building on a specific system, I can try to help.

You might also find this thread helpful:

https://github.com/pachterlab/kallisto/issues/65


Thanks,

Harold

**Comment by pimentel** [comment]
The tutorial for doing a local install is now available:

http://pachterlab.github.io/kallisto/local_build.html

**Comment by pimentel** [comment]
Hi folks,

We have been working really hard on this, and hope to have an answer for you soon.

Thanks,
Harold

**Comment by lucapinello** [comment]
Thanks Harold!

I know it is an hard problem, really appreciate your message.



2015-10-09 13:18 GMT-04:00 Harold Pimentel <notifications@github.com>:

**Comment by pimentel** [comment]
hi folks,

@pmelsted did some hard work and we think these might work for you:

https://pachterlab.github.io/kallisto/download.html

if you have a chance, we would greatly appreciate you testing them.


thanks,

harold

**Comment by pimentel** [comment]
these seem to be working for us, so I think I am going to close this issue for now. thanks to everyone for reporting this.
