### ISSUE TITLE
genome + annotation = good

### ISSUE THREAD

**Issue by macmanes** [pachterlab/kallisto#71]
Enhancement:  

Input a genome + annotation file. Kallisto pulls out the CDS and indexes/maps appropriately. Should be 'easy' to pull out the coding sequences given these data.

**Comment by skurscheid** [comment]
Just a hint: gffread (part of cufflinks) should be able to do that. Or, IF the genome is available in the UCSC genome browser, a query through the table browser would produce the same results...

**Comment by macmanes** [comment]
Thanks @skurscheid. I'll be hopeful that the functionality would be easy to implement.

**Comment by pimentel** [comment]
Thanks for the idea. I feel like this is beyond the scope of kallisto and there are many existing ways to do this already:

- gffread as mentioned
- gtf_to_fasta in the TopHat package 
- UCSC genome browser: http://lmcb.wikispaces.com/eXpress+Walkthrough (see "Generating a set of target sequences (with an existing annotation)")
- Probably also in bedtools (I'm not sure).

Closing for now.

**Comment by pimentel** [comment]
Btw, I should add that if we don't have to add a GTF parser, I'd rather not. The format is inherently really nasty and the parsers are hideous (just take a look at the cufflinks/top hat GTF parsers)
