### ISSUE TITLE
Linux build missing

### ISSUE THREAD

**Issue by roryk** [pachterlab/kallisto#75]
Hi everyone,

It looks like the past couple of releases are missing the Linux binaries:

https://github.com/pachterlab/kallisto/releases/download/v0.42.2.1/kallisto_linux-v0.42.2.1.tar.gz

and 

https://github.com/pachterlab/kallisto/releases/download/v0.42.2/kallisto_linux-v0.42.2.tar.gz

404-- any shot of getting those put up? I can provide builds if that would help.

Thanks!

**Comment by pimentel** [comment]
Hi @roryk,

Here is another thread on the same topic:

https://github.com/pachterlab/kallisto/issues/68

Basically, we're having trouble building portable binaries. If you have some insight, it would be much appreciated!


Thanks,

Harold

**Comment by roryk** [comment]
Sorry about the double issue, I should have checked. Will respond over there.
