### ISSUE TITLE
hdf5 files corrupted in multi-thread mode

### ISSUE THREAD

**Issue by gringer** [pachterlab/kallisto#78]
kalliso only produces correct hdf5 files in non-threaded mode. When run in threaded mode (much faster), the abundance file is fine, but the h5 file has an incorrect structure:

    ## threaded (-t 6 -b 100, about 10 mins per sample)
    kallisto h5dump 1563-01/abundance.h5 -o out 2>&1 | head -n 6
    HDF5-DIAG: Error detected in HDF5 (1.8.13) thread 24488128:
    #000: ../../../src/H5F.c line 1598 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
    #001: ../../../src/H5F.c line 1389 in H5F_open(): unable to read superblock
    major: File accessibilty

    $ ls -lh 1563-0[12]
    1563-01:
    total 20M
    -rw-rw-r-- 1 bioinfo_user bioinfo_user 4.3M Aug 24 12:02 abundance.h5
    -rw-rw-r-- 1 bioinfo_user bioinfo_user  16M Aug 24 12:02 abundance.tsv
    -rw-rw-r-- 1 bioinfo_user bioinfo_user  613 Aug 24 12:02 run_info.json

    1563-02:
    total 21M
    -rw-rw-r-- 1 bioinfo_user bioinfo_user 4.5M Aug 24 12:11 abundance.h5
    -rw-rw-r-- 1 bioinfo_user bioinfo_user  16M Aug 24 12:11 abundance.tsv
    -rw-rw-r-- 1 bioinfo_user bioinfo_user  613 Aug 24 12:11 run_info.json

    ## unthreaded (-b 50), about 40 mins per sample
    $ kallisto h5dump test2/1563-01/abundance.h5 -o out 2>&1 | head -n 6
    [h5dump] number of targets: 418753
    [h5dump] number of bootstraps: 50
    [h5dump] kallisto version: 0.42.2.1
    [h5dump] index version: 10
    [h5dump] start time: Tue Aug 25 17:20:52 2015
    [h5dump] shell call: kallisto quant -i /mnt/BigBirdShared/BioInfoProjects/GLG_Nippo/Mapping/RefSets/Nb_Trinity/kallisto_out -o /mnt/BigBirdShared/BioInfoProjects/GLG_Nippo/Mapping/MappedSets/TB-15-07_Nb/Nb_Trinity/test2/1563-01/ -b 50 /mnt/BigBirdShared/BioInfoProjects/GLG_Nippo/PreProcessing/ReadSets/TB-15-07_Nb/MIMR_Processed/1563-01-01-01_R1.fastq.gz /mnt/BigBirdShared/BioInfoProjects/GLG_Nippo/PreProcessing/ReadSets/TB-15-07_Nb/MIMR_Processed/1563-01-01-01_R2.fastq.gz

    $ ls -lh test2/1563-0[12] 
    test2/1563-01:
    total 70M
    -rw-rw-r-- 1 bioinfo_user bioinfo_user 54M Aug 25 17:54 abundance.h5
    -rw-rw-r-- 1 bioinfo_user bioinfo_user 16M Aug 25 17:28 abundance.tsv
    -rw-rw-r-- 1 bioinfo_user bioinfo_user 612 Aug 25 17:28 run_info.json

    test2/1563-02:
    total 74M
    -rw-rw-r-- 1 bioinfo_user bioinfo_user 59M Aug 25 19:08 abundance.h5
    -rw-rw-r-- 1 bioinfo_user bioinfo_user 16M Aug 25 18:40 abundance.tsv
    -rw-rw-r-- 1 bioinfo_user bioinfo_user 612 Aug 25 18:40 run_info.json

Just in case it's important, this was compiled on a different system from the one it was run on, using statically-compiled libraries. This was to work around a lack of hdf5 libraries on the running system. Here's the compilation command that I used:

    cmake -DLINK=static -DCMAKE_INSTALL_PREFIX:PATH=~/install/kallisto/kallisto-0.42.2.1 ..

And kallisto's default output:

    $ kallisto
    kallisto 0.42.2.1

    Usage: kallisto <CMD> [arguments] ..

    Where <CMD> can be one of:

        index         Builds a kallisto index 
        quant         Runs the quantification algorithm 
        h5dump        Converts HDF5-formatted results to plaintext
        version       Prints version information

    Running kallisto <CMD> without arguments prints usage information for <CMD>

This was compiled on a Debian system:

    $ uname -a
    Linux elegans 4.1.0-trunk-amd64 #1 SMP Debian 4.1.2-1~exp1 (2015-07-11) x86_64 GNU/Linux
    $ aptitude show libhdf5-dev
    Package: libhdf5-dev
    State: installed
    Automatically installed: no
    Version: 1.8.13+docs-15
    Priority: optional
    Section: libdevel
    Maintainer: Debian GIS Project <pkg-grass-devel@lists.alioth.debian.org>
    Architecture: amd64
    Uncompressed Size: 25.0 M
    Depends: libhdf5-8 (= 1.8.13+docs-15), zlib1g-dev, libjpeg-dev, hdf5-helpers,
             libhdf5-cpp-8 (= 1.8.13+docs-15)
    Suggests: libhdf5-doc
    Conflicts: libhdf5-dev
    Breaks: libhdf5-serial-dev (< 1.8.12-9~), libhdf5-serial-dev (< 1.8.12-9~)
    Replaces: libhdf5-serial-dev (< 1.8.12-9~), libhdf5-serial-dev (< 1.8.12-9~)
    Provides: libhdf5-serial-dev
    Description: Hierarchical Data Format 5 (HDF5) - development files - serial version
     HDF5 is a file format and library for storing scientific data. HDF5 was
     designed and implemented to address the deficiencies of HDF4.x. It has a more
     powerful and flexible data model, supports files larger than 2 GB, and supports
     parallel I/O. 
     
     This package contains development files for serial platforms.
    Homepage: http://hdfgroup.org/HDF5/
    
    Tags: devel::library, role::devel-lib

    $ dpkg -S libhdf5_serial
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.a
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so
    libhdf5-8:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_serialhl_fortran.so.8
    libhdf5-8:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_serial_fortran.so.8
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serial.so
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serialhl_fortran.so
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serial_fortran.so
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serial.a
    libhdf5-8:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.8
    libhdf5-8:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_serialhl_fortran.so.8.0.2
    libhdf5-8:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_serial_fortran.so.8.0.2
    libhdf5-8:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serial_fortran.a
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serialhl_fortran.a
    libhdf5-8:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.8.0.2
    libhdf5-8:amd64: /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8.0.2
    libhdf5-dev: /usr/lib/x86_64-linux-gnu/libhdf5_serial.settings

**Comment by pimentel** [comment]
hi @gringer 

thanks for the report. i wouldn't be surprised if the static build is broken. we should probably note it somewhere, but we've hiad very limited success using those flags on our machines. any chance you can try building it with shared libraries?

also, can you take a look at: `h5ls --recursive abundance.h5` on the corrupted ones?


thanks!

harold

**Comment by gringer** [comment]
Here's the ls output:

    $ h5ls 1563-01/abundance.h5 
    1563-01/abundance.h5: unable to open file

    $ h5ls test2/1563-01/abundance.h5
    aux                      Group
    bootstrap                Group
    est_counts               Dataset {418753}

Shared libraries aren't working at the moment because the hdf5 library isn't installed on the run server. I'll see if I can do anything for a local non-admin install to get the linking to work properly (any suggestions for this would be appreciated).

**Comment by pimentel** [comment]
Cool, thanks. That's a pretty big transcriptome -- was it assembled from RNA-Seq?

Anyway, do you have a C++11 compliant compiler on this machine?

**Comment by pimentel** [comment]
If you have a C++11 compliant compiler, please try these instructions:

http://pachterlab.github.io/kallisto/local_build.html

**Comment by gringer** [comment]
Yes, assembled from RNA-Seq. About half of the transcripts aren't getting any counts in kallisto.

**Comment by gringer** [comment]
Unfortunately the compiler doesn't seem to be C++11 compliant:

    $ c++ --version
    c++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
    Copyright (C) 2010 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by gringer** [comment]
I did a local bootstrap compile of gcc, and it worked in the end with a local build of kallisto version 0.42.3 and g++ version 5.2.0:

$ h5ls test3/1563-01/abundance.h5
aux                      Group
bootstrap                Group
est_counts               Dataset {418753}

We're working towards reducing that dataset down to a more reasonable size. CDHIT-EST brings it down to about 200k transcripts, and I'm working on using frameDP to [slowly] discover only those transcripts that produce protein sequences.

**Comment by pimentel** [comment]
sorry for the delay, but I notice you got it working. closing the issue for now, but will keep this in mind for future builds.

thanks,
harold
