### ISSUE TITLE
use https in _config.yml

### ISSUE THREAD

**Issue by slowkow** [pachterlab/kallisto#80]
Every time I visit the kallisto page, I have to click this button and "load unsafe scripts":

![window_and_local_build_without_root](https://cloud.githubusercontent.com/assets/209714/9658393/f948bd60-5216-11e5-8b12-8c6ae7784f63.png)

[https is supported for github pages][1] hosted on *.github.io domains.

And the console shows these errors:

```
Mixed Content: The page at 'https://pachterlab.github.io/kallisto/local_build.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://pachterlab.github.io/kallisto/assets/themes/twitter/bootstrap/css/bootstrap.2.2.2.min.css'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://pachterlab.github.io/kallisto/local_build.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://pachterlab.github.io/kallisto/assets/themes/twitter/css/style.css?body=1'. This request has been blocked; the content must be served over HTTPS.
```

[1]: https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

The fix should be as simple as changing [line 57 in your _config.yml](https://github.com/pachterlab/kallisto/blob/gh-pages/_config.yml#L57):

```yaml
  # Use https!
  #BASE_PATH : http://pachterlab.github.io/kallisto
  BASE_PATH : https://pachterlab.github.io/kallisto
```

**Comment by pimentel** [comment]
Thanks for the suggestion. I think I fixed the issue.

Please let me know if it is still an issue. Closing for now.
