### ISSUE TITLE
kallisto v0.42.3 make install not working ubuntu VM but v0.42.2.1 is

### ISSUE THREAD

**Issue by jamespblloyd** [pachterlab/kallisto#83]
I tried to install kallisto on a virtual machine of ubuntu 15.04 running on a Windows 10 machine. I had no problem getting anything to work except that last step of installing

\user@user-VirtualBox:/usr/local/bin/kallisto/build$ sudo make install
[ 92%] Built target kallisto_core
[100%] Built target kallisto
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/bin/kallisto
CMake Error at src/cmake_install.cmake:45 (file):
  file RPATH_REMOVE given FILE "/usr/local/bin/kallisto" that does not exist.
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)

Makefile:66: recipe for target 'install' failed
make: *** [install] Error 1

I got this source from github but I then tried the version before it v0.42.2.1 (from https://github.com/pachterlab/kallisto/archive/v0.42.2.1.tar.gz) and I install kallisto no problem. I would rather use the newer version but I thought I should suggest a potential bug. Also, can you do an in situ upgrade of kallisto?

James

**Comment by pimentel** [comment]
It seems like you are trying to install to /usr/local/bin/kallisto, but the
kallisto source code is already there.

Move the kallisto source to ~/src/kallisto, then it should work

On Sunday, October 4, 2015, jamespblloyd <notifications@github.com> wrote:

> I tried to install kallisto on a virtual machine of ubuntu 15.04 running
> on a Windows 10 machine. I had no problem getting anything to work except
> that last step of installing
>
> \user@user-VirtualBox:/usr/local/bin/kallisto/build$ sudo make install
> [ 92%] Built target kallisto_core
> [100%] Built target kallisto
> Install the project...
> -- Install configuration: ""
> -- Up-to-date: /usr/local/bin/kallisto
> CMake Error at src/cmake_install.cmake:45 (file):
> file RPATH_REMOVE given FILE "/usr/local/bin/kallisto" that does not exist.
> Call Stack (most recent call first):
> cmake_install.cmake:37 (include)
>
> Makefile:66: recipe for target 'install' failed
> make: *** [install] Error 1
>
> I got this source from github but I then tried the version before it
> v0.42.2.1 (from
> https://github.com/pachterlab/kallisto/archive/v0.42.2.1.tar.gz) and I
> install kallisto no problem. I would rather use the newer version but I
> thought I should suggest a potential bug. Also, can you do an in situ
> upgrade of kallisto?
>
> James
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pachterlab/kallisto/issues/83>.
>


-- 


Harold


Please excuse any errors in syntax or grammar. I probably dictated this
email using speech recognition.

**Comment by jamespblloyd** [comment]
Ah, I am not sure what 'Move the kallisto source to ~/src/kallisto' means. I don't remember doing that to get v0.42.2.1 to work. Also, I know it is not a general problem with v0.42.3 on ubuntu as I just got kallisto v0.42.3 working on a ubuntu v14 laptop for the roton in my lab. Thanks for the reply!

**Comment by pimentel** [comment]
it seems to me like from the code that you posted above that you extracted kallisto into /usr/local/bin/kallisto. so when you type `make kallisto` it tries to install it into `/usr/local/bin/kallisto` but something already exists there (the source code which you unpacked). so instead of unpacking the source at `/usr/local/bin/kallisto`, unpack the source code in your home directory (and remove everything at `/usr/local/bin/kallisto`). sorry if I misunderstood the issue. 

anyway, it seems like you have resolved the issue, so I am going to close it for now. if it is still an issue, please feel free to reopen this.
