### ISSUE TITLE
mpi.h is not autodetected

### ISSUE THREAD

**Issue by mortya** [pachterlab/kallisto#91]
On CentOS6 and CentOS7, trying to build kallisto with the declared dependencies results in errors.  Here is the CentOS7 error:
````
[  6%] Building CXX object src/CMakeFiles/kallisto_core.dir/Bootstrap.cpp.o
In file included from /usr/local/hdf5/1.8.14/include/hdf5.h:24:0,
                 from /usr/local/kallisto/0.42.4/src/kallisto-0.42.4/src/h5utils.h:13,
                 from /usr/local/kallisto/0.42.4/src/kallisto-0.42.4/src/H5Writer.h:6,
                 from /usr/local/kallisto/0.42.4/src/kallisto-0.42.4/src/Bootstrap.h:12,
                 from /usr/local/kallisto/0.42.4/src/kallisto-0.42.4/src/Bootstrap.cpp:1:
/usr/local/hdf5/1.8.14/include/H5public.h:61:20: fatal error: mpi.h: No such file or directory
 #   include <mpi.h>
                    ^
compilation terminated.
make[2]: *** [src/CMakeFiles/kallisto_core.dir/Bootstrap.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/kallisto_core.dir/all] Error 2
make: *** [all] Error 2
````

This is easily fixed.  I'll submit a pull request.

**Comment by pmelsted** [comment]
kallisto is not dependent on mpi. Depending on how the hdf5 libraries were configured they might depend on mpi, in which case either the package manager or the user installing the libs should have a) made sure mpi.h is available b) configured hdf5 to not use mpi.

Choice b) is our preferred option when installing hdf5 as a user as pointed out in https://pachterlab.github.io/kallisto/local_build.html

This is not an error in the kallisto code or configuration.

**Comment by mortya** [comment]
With respect to option (a): we're using mpich/mpich2 as supplied by CentOS.  They don't put it in the default gcc search path.  Not an option for us.

With respect to option (b): our hdf5 installation supports many other software packages, not just kallisto.  I would prefer not to rebuild it with kallisto-specific option, since that might break it for other purposes.  I could do a separate hdf5 build specific to kallisto.  But I suspect that maintaining this small local patch would be a easier and cleaner.

Thanks for the prompt reply.

**Comment by pmelsted** [comment]
Option b is best for those that don't have hdf5 and non-root access. In your case I would directly modify the cmake files as in your pull request for your local copy, but we can't require everyone to have mpi if since it's not necessary.

**Comment by mortya** [comment]
Presumably, if the REQUIRED were dropped from `find_package( MPI  REQUIRED )` and the else, then it would autodetect MPI for cases like mine without breaking the build for cases where MPI isn't needed.
