### ISSUE TITLE
No documentation for -s option in kallisto quant in the online manual

### ISSUE THREAD

**Issue by gdevailly** [pachterlab/kallisto#93]
Hello,

when trying to use kallisto quant with single end RNA seq data, it complains the following:
> Error: cannot supply mean/sd without supplying both -l and -s
> Error: fragment length mean and sd must be supplied for single-end reads using -l and -s

despite **-l** argument being properly provided. The main point being that the **-s** argument, even if well explained by the error message, is not described in the online manual yet:
https://pachterlab.github.io/kallisto/manual.html 

Thanks,
Guillaume Devailly

**Comment by gdevailly** [comment]
Oops, my bad. I am still using 0.42.3. -s argument must have been removed in 0.42.4. Sorry about that.

**Comment by pimentel** [comment]
hi @gdevailly thanks for the bug report. as you have noticed,  -s has been updated and now is in the documentation.


Best,

Harold
