### ISSUE TITLE
failed to compile on RHEL4

### ISSUE THREAD

**Issue by nick-webster** [pachterlab/kallisto#94]
Hi, I have kallisto running on my iMac and it works great.  I recently tried to install kallisto on an older Dell Poweredge server running RHEL4 so I could do alignments in the background.  Cmake and hdf5 installed OK, then I tried building from the kallisto source code (the binary didn't work).  Cmake seemed to run OK, but the install failed at the make step.  Here's what I get:

[GeneChip@172 build]$ cmake -DCMAKE_INSTALL_PREFIX=$HOME ..
-- The C compiler identification is GNU 3.4.6
-- The CXX compiler identification is GNU 3.4.6
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
shared build
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found HDF5: /home/GeneChip/lib/libhdf5.so;/usr/lib64/librt.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.8.16") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.1.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/GeneChip/bioinformatics/kallisto-0.42.4/build
[GeneChip@172 build]$ make
Scanning dependencies of target kallisto_core
[  5%] Building CXX object src/CMakeFiles/kallisto_core.dir/Bootstrap.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [src/CMakeFiles/kallisto_core.dir/Bootstrap.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/kallisto_core.dir/all] Error 2
make: *** [all] Error 2
[GeneChip@172 build]$

Any ideas as to what is failing?  Is it just that the OS is too old?

Thanks,  Nick

**Comment by pimentel** [comment]
Hi Nick,

Unfortunately your compiler is far too old. We require gcc >= 4.8.


Thanks,
Harold
